<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Free.Shared.Ribbon\Free.Shared.Ribbon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Ribbon" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FreeX.Ribbon.Definitions.Tests" />
  </ItemGroup>

</Project>
