namespace FreeX.Ribbon.Definitions;

/// <summary>Generated Home-tab dropdown menus (extracted from the original ribbon XAML).</summary>
public static class HomeRibbonMenus
{
    public static void Paste(RibbonMenuBuilder m) => m.Item("Paste", "Paste", "P", "P").Item("Paste Values", "Values", "V", "V").Item("Paste Formulas", "Formulas", "F", "F").Item("Paste Formatting", "Formatting", "R", "R").Item("Keep Source Column Widths", "Keep Source Column Widths", "W", "W").Item("Values & Source Formatting", "Values & Source Formatting", "A", "A").Item("Transpose Paste", "Transpose", "T", "T").Item("Paste Link", "Paste Link", "L", "L").Item("Picture", "Picture", "I", "I").Item("Linked Picture", "Linked Picture", "K", "K").Separator().Item("Paste Special", "Paste Special...", "S", "S");
    public static void Underline(RibbonMenuBuilder m) => m.Item("Underline", "Underline", "U").Item("Double Underline", "Double underline", "D");
    public static void Borders(RibbonMenuBuilder m) => HomeBorderMenuCatalog.Build(m);
    public static void Orientation(RibbonMenuBuilder m) => m.Item("Horizontal", "Horizontal", "H").Item("Angle Counterclockwise", "Angle Counterclockwise", "A").Item("Angle Clockwise", "Angle Clockwise", "C").Item("Vertical Text", "Vertical Text", "V").Item("Rotate Text Up", "Rotate Text Up", "U").Item("Rotate Text Down", "Rotate Text Down", "D");
    public static void MergeCenter(RibbonMenuBuilder m) => m.Item("Merge & Center", "Merge & Center", "C").Item("Merge Across", "Merge Across", "A").Item("Merge Cells", "Merge Cells", "M").Item("Unmerge Cells", "Unmerge Cells", "U");
    public static void AccountingNumberFormat(RibbonMenuBuilder m) => m.Item("Accounting Number Format US Dollar", "US Dollar ($)", "D").Item("Accounting Number Format Euro", "Euro (€)", "E").Item("Accounting Number Format British Pound", "British Pound (£)", "P").Item("Accounting Number Format Japanese Yen", "Japanese Yen (¥)", "Y").Separator().Item("More Accounting Formats", "More Accounting Formats...", "M");
    public static void ConditionalFormatting(RibbonMenuBuilder m) => m.Submenu("Highlight Cells Rules", "H", sm => sm.Item("Greater Than", "Greater Than...", "HG").Item("Less Than", "Less Than...", "HL").Item("Between", "Between...", "HB").Item("Equal To", "Equal To...", "HE").Item("Text that Contains", "Text that Contains...", "HT").Item("A Date Occurring", "A Date Occurring...", "HD").Item("Duplicate Values", "Duplicate Values...", "HU")).Submenu("Top/Bottom Rules", "T", sm => sm.Item("Top 10 Items", "Top 10 Items...", "TT").Item("Top 10%", "Top 10%...", "TP").Item("Bottom 10 Items", "Bottom 10 Items...", "TB").Item("Bottom 10%", "Bottom 10%...", "BP").Item("Above Average", "Above Average...", "TA").Item("Below Average", "Below Average...", "TL")).Item("Data Bars", "Data Bars...", "D").Item("Color Scales", "Color Scales...", "C").Submenu("Icon Sets", "I", sm => sm.Item("3 Arrows", "3 Arrows", "I3").Item("3 Arrows (Gray)", "3 Arrows (Gray)", "IG").Item("4 Arrows", "4 Arrows", "I4").Item("4 Arrows (Gray)", "4 Arrows (Gray)", "IH").Item("5 Arrows", "5 Arrows", "I5").Item("5 Arrows (Gray)", "5 Arrows (Gray)", "IJ").Separator().Item("3 Traffic Lights", "3 Traffic Lights", "IT").Item("3 Traffic Lights (Rimmed)", "3 Traffic Lights (Rimmed)", "IR").Item("3 Signs", "3 Signs", "IS").Item("3 Symbols", "3 Symbols", "IY").Item("3 Symbols (Uncircled)", "3 Symbols (Uncircled)", "IU").Item("3 Flags", "3 Flags", "IF").Separator().Item("4 Traffic Lights", "4 Traffic Lights", "IL").Item("4 Red To Black", "4 Red To Black", "IB").Separator().Item("4 Ratings", "4 Ratings", "I9").Item("5 Ratings", "5 Ratings", "IA").Item("5 Quarters", "5 Quarters", "IQ").Item("5 Boxes", "5 Boxes", "IX").Separator().Item("More Rules", "More Rules...", "IM")).Separator().Item("New Rule", "New Rule...", "N").Item("New Formula Rule", "New Formula Rule...", "F").Item("Clear Rules", "Clear Rules", "R").Item("Manage Rules", "Manage Rules...", "M");
    public static void CellStyles(RibbonMenuBuilder m) => m.Item("Normal", "Normal", "NM").Separator().Item("Good", "Good", "GD").Item("Bad", "Bad", "BD").Item("Neutral", "Neutral", "NT").Separator().Item("Input", "Input", "IN").Item("Output", "Output", "OP").Item("Calculation", "Calculation", "CA").Item("Check Cell", "Check Cell", "CK").Item("Linked Cell", "Linked Cell", "LK").Item("Explanatory Text", "Explanatory Text", "EX").Separator().Item("Heading 1", "Heading 1", "H1").Item("Heading 2", "Heading 2", "H2").Item("Note", "Note", "NO").Item("Warning Text", "Warning Text", "WT").Item("Total", "Total", "TT").Separator().Item("20% - Accent 1", "20% - Accent 1", "A1").Item("20% - Accent 2", "20% - Accent 2", "A2").Item("20% - Accent 3", "20% - Accent 3", "A3").Item("20% - Accent 4", "20% - Accent 4", "A4").Item("20% - Accent 5", "20% - Accent 5", "A5").Item("20% - Accent 6", "20% - Accent 6", "A6").Item("40% - Accent 1", "40% - Accent 1", "B1").Item("40% - Accent 2", "40% - Accent 2", "B2").Item("40% - Accent 3", "40% - Accent 3", "B3").Item("40% - Accent 4", "40% - Accent 4", "B4").Item("40% - Accent 5", "40% - Accent 5", "B5").Item("40% - Accent 6", "40% - Accent 6", "B6").Item("60% - Accent 1", "60% - Accent 1", "C1").Item("60% - Accent 2", "60% - Accent 2", "C2").Item("60% - Accent 3", "60% - Accent 3", "C3").Item("60% - Accent 4", "60% - Accent 4", "C4").Item("60% - Accent 5", "60% - Accent 5", "C5").Item("60% - Accent 6", "60% - Accent 6", "C6");
    public static void Insert(RibbonMenuBuilder m) => m.Item("Insert Cells", "Insert Cells...", "C").Item("Insert Sheet Rows", "Insert Sheet Rows", "R").Item("Insert Sheet Columns", "Insert Sheet Columns", "O").Item("Insert Sheet", "Insert Sheet", "S");
    public static void Delete(RibbonMenuBuilder m) => m.Item("Delete Cells", "Delete Cells...", "C").Item("Delete Sheet Rows", "Delete Sheet Rows", "R").Item("Delete Sheet Columns", "Delete Sheet Columns", "O").Item("Delete Sheet", "Delete Sheet", "S");
    public static void Format(RibbonMenuBuilder m) => m.Item("Row Height", "Row Height...", "R").Item("AutoFit Row Height", "AutoFit Row Height", "A").Separator().Item("Column Width", "Column Width...", "C").Item("AutoFit Column Width", "AutoFit Column Width", "W").Separator().Item("Hide Rows", "Hide Rows", "H").Item("Unhide Rows", "Unhide Rows", "U").Item("Hide Columns", "Hide Columns", "D").Item("Unhide Columns", "Unhide Columns", "N").Separator().Item("Rename Sheet", "Rename Sheet", "E").Item("Tab Color", "Tab Color", "TC").Item("Hide Sheet", "Hide Sheet", "S").Item("Unhide Sheet", "Unhide Sheet...", "Y").Separator().Item("Protect Sheet", "Protect Sheet...", "P").Item("Lock Cell", "Lock Cell", "L").Separator().Item("Format Cells", "Format Cells...", "F");
    public static void AutoSum(RibbonMenuBuilder m) => m.Item("Sum", "Sum", "S").Item("Average", "Average", "A").Item("Count Numbers", "Count Numbers", "C").Item("Count All", "Count All", "T").Item("Max", "Max", "X").Item("Min", "Min", "M").Separator().Item("More Functions", "More Functions...", "F");
    public static void Fill(RibbonMenuBuilder m) => m.Item("Down", "Down", "D").Item("Right", "Right", "R").Item("Up", "Up", "U").Item("Left", "Left", "L").Separator().Item("Series", "Series...", "S").Item("Flash Fill", "Flash Fill", "F");
    public static void Clear(RibbonMenuBuilder m) => m.Item("Clear All", "Clear All", "A").Item("Clear Formats", "Clear Formats", "F").Item("Clear Contents", "Clear Contents", "C").Item("Clear Comments and Notes", "Clear Comments and Notes", "M").Item("Clear Hyperlinks", "Clear Hyperlinks", "H");
    public static void SortFilter(RibbonMenuBuilder m) => m.Item("Sort A to Z", "Sort A to Z", "A").Item("Sort Z to A", "Sort Z to A", "Z").Item("Custom Sort", "Custom Sort...", "S").Separator().Item("Filter", "Filter", "F").Item("Clear", "Clear", "C").Item("Reapply", "Reapply", "R");
    public static void FindSelect(RibbonMenuBuilder m) => m.Item("Find", "Find...", "F").Item("Replace", "Replace...", "R").Separator().Item("Go To", "Go To...", "G").Item("Go To Special", "Go To Special...", "S").Separator().Item("Formulas", "Formulas", "O").Item("Notes", "Notes", "N").Item("Conditional Formatting", "Conditional Formatting", "C").Item("Constants", "Constants", "T").Item("Data Validation", "Data Validation", "V").Separator().Item("Select Objects", "Select Objects", "J").Item("Selection Pane", "Selection Pane...", "P");
}
