using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;

namespace FreeX.Ribbon.Avalonia;

/// <summary>
/// Minimal but recognizable Avalonia icon set for <see cref="RibbonCommandIconKind"/>.
/// Each kind maps to a glyph rendered as a <see cref="TextBlock"/>. This is intentionally
/// lightweight (no SVG paths) — the WPF renderer owns the full vector set; here we only need
/// the cross-platform ribbon to read recognizably.
/// </summary>
internal static class AvaloniaRibbonIcons
{
    /// <summary>Builds an icon glyph control for the given kind at the requested pixel size.</summary>
    public static Control Build(RibbonCommandIconKind kind, double size)
    {
        return new TextBlock
        {
            Text = Glyph(kind),
            FontSize = size,
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Center,
        };
    }

    /// <summary>Maps an icon kind to a recognizable glyph. Exposed for tests.</summary>
    public static string Glyph(RibbonCommandIconKind kind) => kind switch
    {
        RibbonCommandIconKind.Accessibility => "♿",
        RibbonCommandIconKind.Align => "≡",
        RibbonCommandIconKind.Book => "\U0001F4D6",
        RibbonCommandIconKind.Border => "□",
        RibbonCommandIconKind.Bold => "B",
        RibbonCommandIconKind.BringForward => "⬆",
        RibbonCommandIconKind.ChartArea => "◢",
        RibbonCommandIconKind.PivotTable => "⊞",
        RibbonCommandIconKind.Table => "⊞",
        RibbonCommandIconKind.ChartColumn => "ὌA",
        RibbonCommandIconKind.ChartLine => "↗",
        RibbonCommandIconKind.ChartPie => "◕",
        RibbonCommandIconKind.ChartScatter => "⋯",
        RibbonCommandIconKind.ChevronDown => "▾",
        RibbonCommandIconKind.Collapse => "−",
        RibbonCommandIconKind.Color => "\U0001F3A8",
        RibbonCommandIconKind.Comma => ",",
        RibbonCommandIconKind.Comment => "\U0001F4AC",
        RibbonCommandIconKind.Consolidate => "⊕",
        RibbonCommandIconKind.Copy => "⧉",
        RibbonCommandIconKind.Clear => "⌫",
        RibbonCommandIconKind.Currency => "$",
        RibbonCommandIconKind.Cut => "✂",
        RibbonCommandIconKind.Date => "\U0001F4C5",
        RibbonCommandIconKind.Decimal => ".0",
        RibbonCommandIconKind.Delete => "✖",
        RibbonCommandIconKind.Effects => "✨",
        RibbonCommandIconKind.Ellipse => "◯",
        RibbonCommandIconKind.Expand => "+",
        RibbonCommandIconKind.Feedback => "✍",
        RibbonCommandIconKind.Fill => "\U0001F58C",
        RibbonCommandIconKind.Filter => "⯇",
        RibbonCommandIconKind.FormatPainter => "\U0001F58C",
        RibbonCommandIconKind.Financial => "¤",
        RibbonCommandIconKind.Flash => "⚡",
        RibbonCommandIconKind.Font => "A",
        RibbonCommandIconKind.Freeze => "❄",
        RibbonCommandIconKind.Function => "ƒ",
        RibbonCommandIconKind.GetData => "⤓",
        RibbonCommandIconKind.Grid => "▦",
        RibbonCommandIconKind.Group => "▣",
        RibbonCommandIconKind.HeaderFooter => "☰",
        RibbonCommandIconKind.Help => "?",
        RibbonCommandIconKind.History => "↺",
        RibbonCommandIconKind.Insert => "➕",
        RibbonCommandIconKind.Info => "ℹ",
        RibbonCommandIconKind.Italic => "I",
        RibbonCommandIconKind.Label => "\U0001F3F7",
        RibbonCommandIconKind.Line => "─",
        RibbonCommandIconKind.Link => "\U0001F517",
        RibbonCommandIconKind.List => "☰",
        RibbonCommandIconKind.Logical => "⊨",
        RibbonCommandIconKind.Margins => "⤢",
        RibbonCommandIconKind.Math => "∑",
        RibbonCommandIconKind.Merge => "⇹",
        RibbonCommandIconKind.More => "⋯",
        RibbonCommandIconKind.Next => "▶",
        RibbonCommandIconKind.Number => "#",
        RibbonCommandIconKind.Orientation => "↻",
        RibbonCommandIconKind.Page => "\U0001F4C4",
        RibbonCommandIconKind.PageBreak => "✂",
        RibbonCommandIconKind.Paste => "\U0001F4CB",
        RibbonCommandIconKind.Percent => "%",
        RibbonCommandIconKind.Picture => "\U0001F5BC",
        RibbonCommandIconKind.Pin => "\U0001F4CC",
        RibbonCommandIconKind.Previous => "◀",
        RibbonCommandIconKind.Print => "\U0001F5A8",
        RibbonCommandIconKind.Protect => "\U0001F512",
        RibbonCommandIconKind.Recent => "⏱",
        RibbonCommandIconKind.Rectangle => "▭",
        RibbonCommandIconKind.Connector => "—",
        RibbonCommandIconKind.Triangle => "△",
        RibbonCommandIconKind.Diamond => "◇",
        RibbonCommandIconKind.Parallelogram => "▱",
        RibbonCommandIconKind.Trapezoid => "⏢",
        RibbonCommandIconKind.Pentagon => "⬠",
        RibbonCommandIconKind.Hexagon => "⬡",
        RibbonCommandIconKind.Octagon => "⬢",
        RibbonCommandIconKind.Cross => "✚",
        RibbonCommandIconKind.ArrowRight => "→",
        RibbonCommandIconKind.ArrowLeft => "←",
        RibbonCommandIconKind.ArrowUp => "↑",
        RibbonCommandIconKind.ArrowDown => "↓",
        RibbonCommandIconKind.ArrowLeftRight => "↔",
        RibbonCommandIconKind.ArrowUpDown => "↕",
        RibbonCommandIconKind.PlusSign => "+",
        RibbonCommandIconKind.MinusSign => "−",
        RibbonCommandIconKind.MultiplySign => "×",
        RibbonCommandIconKind.DivideSign => "÷",
        RibbonCommandIconKind.EqualSign => "=",
        RibbonCommandIconKind.NotEqualSign => "≠",
        RibbonCommandIconKind.FlowchartProcess => "▭",
        RibbonCommandIconKind.FlowchartDecision => "◇",
        RibbonCommandIconKind.FlowchartData => "▱",
        RibbonCommandIconKind.FlowchartDocument => "\U0001F4C4",
        RibbonCommandIconKind.FlowchartTerminator => "⬭",
        RibbonCommandIconKind.Star => "★",
        RibbonCommandIconKind.Explosion => "\U0001F4A5",
        RibbonCommandIconKind.RibbonShape => "\U0001F397",
        RibbonCommandIconKind.Wave => "〰",
        RibbonCommandIconKind.Callout => "\U0001F5E8",
        RibbonCommandIconKind.LineCallout => "\U0001F5E8",
        RibbonCommandIconKind.Redo => "↻",
        RibbonCommandIconKind.Refresh => "↻",
        RibbonCommandIconKind.Rotate => "⟳",
        RibbonCommandIconKind.Ruler => "\U0001F4CF",
        RibbonCommandIconKind.Save => "\U0001F4BE",
        RibbonCommandIconKind.Scale => "⇲",
        RibbonCommandIconKind.Search => "\U0001F50D",
        RibbonCommandIconKind.SendBackward => "⬇",
        RibbonCommandIconKind.Share => "↪",
        RibbonCommandIconKind.Size => "⤢",
        RibbonCommandIconKind.Sort => "⇅",
        RibbonCommandIconKind.SortAscending => "↑",
        RibbonCommandIconKind.SortDescending => "↓",
        RibbonCommandIconKind.Sparkline => "≈",
        RibbonCommandIconKind.Spelling => "✓",
        RibbonCommandIconKind.Strikethrough => "S̶",
        RibbonCommandIconKind.Sum => "∑",
        RibbonCommandIconKind.Symbol => "Ω",
        RibbonCommandIconKind.Target => "◎",
        RibbonCommandIconKind.TextBox => "Ⓣ",
        RibbonCommandIconKind.TextColumns => "‖",
        RibbonCommandIconKind.TextFunction => "ƒ",
        RibbonCommandIconKind.Theme => "\U0001F3A8",
        RibbonCommandIconKind.Translate => "文",
        RibbonCommandIconKind.Underline => "U",
        RibbonCommandIconKind.Undo => "↺",
        RibbonCommandIconKind.Ungroup => "□",
        RibbonCommandIconKind.View => "\U0001F441",
        RibbonCommandIconKind.Warning => "⚠",
        RibbonCommandIconKind.Watch => "⏲",
        RibbonCommandIconKind.Window => "▢",
        RibbonCommandIconKind.WindowClose => "✕",
        RibbonCommandIconKind.WindowMaximize => "□",
        RibbonCommandIconKind.WindowRestore => "▧",
        RibbonCommandIconKind.WindowMinimize => "–",
        RibbonCommandIconKind.Wrap => "↵",
        RibbonCommandIconKind.Zoom => "\U0001F50E",
        _ => "■",
    };
}
