<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FreeX.Ribbon.Avalonia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeX.Ribbon\FreeX.Ribbon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FreeX.App.Avalonia.Tests" />
  </ItemGroup>

</Project>
