internal enum WorkbookValidationWorkflow
{
    DirectExcel,
    FreeXSaveThenExcel
}

internal sealed record WorkbookSmokeInput(
    string SourcePath,
    WorkbookValidationWorkflow Workflow,
    string Description,
    bool GenerateWithExcel = false,
    CorpusManifestRow? CorpusRow = null,
    WorkbookSmokeExpectations? Expectations = null);

internal sealed record WorkbookSmokeExpectations(
    int MinFreeXPreSaveFormulaCells = 0,
    int MinFreeXPreSaveNamedRanges = 0,
    int MinFreeXPreSaveStructuredTables = 0,
    int MinFreeXPreSaveCharts = 0,
    int MinFreeXPreSaveDataValidations = 0,
    int MinFreeXPreSaveConditionalFormats = 0,
    int MinFreeXPreSaveHyperlinks = 0,
    int MinFreeXPreSaveComments = 0,
    int MinFreeXPreSavePictures = 0,
    int MinFreeXPreSaveSparklines = 0,
    int MinFreeXPreSaveTextBoxes = 0,
    int MinFreeXPreSaveDrawingShapes = 0,
    int MinFreeXPreSaveProtectedSheets = 0,
    int MinFreeXPreSaveStructureProtection = 0,
    int MinExcelOpenedFormulaCells = 0,
    int MinExcelOpenedNamedRanges = 0,
    int MinExcelOpenedStructuredTables = 0,
    int MinExcelOpenedCharts = 0,
    int MinExcelOpenedDataValidationCells = 0,
    int MinExcelOpenedConditionalFormats = 0,
    int MinExcelOpenedHyperlinks = 0,
    int MinExcelOpenedComments = 0,
    int MinExcelOpenedProtectedSheets = 0,
    int MinExcelOpenedStructureProtection = 0,
    int MinExcelOpenedPictures = 0,
    int MinExcelOpenedSparklines = 0,
    int MinExcelOpenedTextBoxes = 0,
    int MinExcelOpenedDrawingShapes = 0,
    int MinExcelOpenedShapes = 0,
    int MinExcelOpenedPrintAreaSheets = 0,
    int MinExcelOpenedPrintTitleSheets = 0,
    int MinExcelOpenedLandscapeSheets = 0,
    int MinExcelOpenedScaleToFitSheets = 0,
    int MinExcelOpenedPrintOptionsSheets = 0,
    int MinExcelOpenedHeaderFooterSheets = 0,
    int MinExcelOpenedManualPageBreaks = 0,
    int MinExcelOpenedAllowEditRanges = 0,
    int MinExcelReopenedFormulaCells = 0,
    int MinExcelReopenedNamedRanges = 0,
    int MinExcelReopenedStructuredTables = 0,
    int MinExcelReopenedCharts = 0,
    int MinExcelReopenedDataValidationCells = 0,
    int MinExcelReopenedConditionalFormats = 0,
    int MinExcelReopenedHyperlinks = 0,
    int MinExcelReopenedComments = 0,
    int MinExcelReopenedProtectedSheets = 0,
    int MinExcelReopenedStructureProtection = 0,
    int MinExcelReopenedPictures = 0,
    int MinExcelReopenedSparklines = 0,
    int MinExcelReopenedTextBoxes = 0,
    int MinExcelReopenedDrawingShapes = 0,
    int MinExcelReopenedShapes = 0,
    int MinExcelReopenedPrintAreaSheets = 0,
    int MinExcelReopenedPrintTitleSheets = 0,
    int MinExcelReopenedLandscapeSheets = 0,
    int MinExcelReopenedScaleToFitSheets = 0,
    int MinExcelReopenedPrintOptionsSheets = 0,
    int MinExcelReopenedHeaderFooterSheets = 0,
    int MinExcelReopenedManualPageBreaks = 0,
    int MinExcelReopenedAllowEditRanges = 0,
    int MinFreeXReopenedFormulaCells = 0,
    int MinFreeXReopenedNamedRanges = 0,
    int MinFreeXReopenedStructuredTables = 0,
    int MinFreeXReopenedCharts = 0,
    int MinFreeXReopenedDataValidations = 0,
    int MinFreeXReopenedConditionalFormats = 0,
    int MinFreeXReopenedHyperlinks = 0,
    int MinFreeXReopenedComments = 0,
    int MinFreeXReopenedPictures = 0,
    int MinFreeXReopenedSparklines = 0,
    int MinFreeXReopenedTextBoxes = 0,
    int MinFreeXReopenedDrawingShapes = 0,
    int MinFreeXReopenedProtectedSheets = 0,
    int MinFreeXReopenedStructureProtection = 0,
    int MinFreeXPreSavePivotTables = 0,
    int MinFreeXPreSavePivotCaches = 0,
    int MinExcelOpenedPivotTables = 0,
    int MinExcelReopenedPivotTables = 0,
    int MinFreeXReopenedPivotTables = 0,
    int MinFreeXReopenedPivotCaches = 0,
    bool RequireNoFreeXLoadWarnings = false);

internal sealed record WorkbookSmokeResult(
    bool Success,
    WorkbookSmokeInput Input,
    string? StagedPath,
    string? FreeXSavedPath,
    string? ExcelSavedPath,
    ExcelWorkbookSummary? Opened,
    ExcelWorkbookSummary? Reopened,
    FreeXWorkbookSummary? FreeXPreSave,
    IReadOnlyList<string> FreeXPreSaveWarnings,
    FreeXWorkbookSummary? FreeXReopenedExcelSave,
    IReadOnlyList<string> FreeXReopenedExcelSaveWarnings,
    string? Error)
{
    public static WorkbookSmokeResult Pass(
        WorkbookSmokeInput input,
        string stagedPath,
        string? freeXSavedPath,
        string? ExcelSavedPath,
        ExcelWorkbookSummary opened,
        ExcelWorkbookSummary? Reopened,
        FreeXWorkbookSummary? freeXPreSave,
        IReadOnlyList<string> freeXPreSaveWarnings,
        FreeXWorkbookSummary? FreeXReopenedExcelSave,
        IReadOnlyList<string> freeXReopenedExcelSaveWarnings) =>
        new(
            true,
            input,
            stagedPath,
            freeXSavedPath,
            ExcelSavedPath,
            opened,
            Reopened,
            freeXPreSave,
            freeXPreSaveWarnings,
            FreeXReopenedExcelSave,
            freeXReopenedExcelSaveWarnings,
            null);

    public static WorkbookSmokeResult Fail(WorkbookSmokeInput input, string? freeXSavedPath, string error) =>
        new(false, input, null, freeXSavedPath, null, null, null, null, Array.Empty<string>(), null, Array.Empty<string>(), error);
}

internal sealed record ExcelWorkbookSummary(
    int WorksheetCount,
    int NamedRangeCount,
    int ChartCount,
    int DataValidationCellCount,
    int ConditionalFormatCount,
    int HyperlinkCount,
    int CommentCount,
    int ProtectedSheetCount,
    int StructureProtectionCount,
    int PictureCount,
    int SparklineCount,
    int TextBoxCount,
    int DrawingShapeCount,
    int ShapeCount,
    int PrintAreaSheetCount,
    int PrintTitleSheetCount,
    int LandscapeSheetCount,
    int ScaleToFitSheetCount,
    int PrintOptionsSheetCount,
    int HeaderFooterSheetCount,
    int ManualPageBreakCount,
    int AllowEditRangeCount,
    int FormulaCellCount,
    int StructuredTableCount,
    int PivotTableCount);
internal sealed record FreeXWorkbookSummary(
    int SheetCount,
    int CellCount,
    int FormulaCellCount,
    int NamedRangeCount,
    int ChartCount,
    int StructuredTableCount,
    int DataValidationCount,
    int ConditionalFormatCount,
    int HyperlinkCount,
    int CommentCount,
    int PictureCount,
    int SparklineCount,
    int TextBoxCount,
    int DrawingShapeCount,
    int ProtectedSheetCount,
    int StructureProtectionCount,
    int PivotTableCount,
    int PivotCacheCount);
internal sealed record FreeXLoadSummaryResult(FreeXWorkbookSummary Summary, IReadOnlyList<string> Warnings);
internal sealed record FreeXSaveResult(string SavedPath, FreeXWorkbookSummary Summary, IReadOnlyList<string> LoadWarnings);
internal sealed record ExcelSaveReopenResult(
    string ExcelSavedPath,
    ExcelWorkbookSummary Opened,
    ExcelWorkbookSummary Reopened);
internal sealed record ExcelSmokeSummary(
    int Total,
    int Passed,
    int Failed,
    IReadOnlyList<WorkbookSmokeResult> Results);

internal sealed record CorpusManifestRow(
    string Id,
    string RelativePath,
    string SourceType,
    string SourceUrl,
    string RetrievedOn,
    string License,
    string FeatureTags,
    string ExpectedWarnings,
    string ExpectedStatus,
    string Notes);

internal sealed record CorpusManifestSkip(
    CorpusManifestRow Row,
    string Reason,
    string? FullPath);

internal sealed record CorpusManifestSelection(
    string ManifestPath,
    IReadOnlyList<WorkbookSmokeInput> Inputs,
    IReadOnlyList<CorpusManifestSkip> Skipped);
