<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\FreeP.App.Host\FreeP.App.Host.csproj" />
    <ProjectReference Include="..\..\..\shared\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
    <ProjectReference Include="..\..\..\shared\Free.Shared.Shell\Free.Shared.Shell.csproj" />
  </ItemGroup>
</Project>
