using System.Text;
using Free.Shared.Shell;
using Free.ToolsShared;

return GeneratedEvidenceToolRunner.Run(
    args,
    new GeneratedEvidenceToolSpec(
        "FreeW.slnx",
        Path.Combine("docs", "parity", "freew-backstage-parity-20260720.md"),
        BuildReport));

static string BuildReport()
{
    var wpf = BuildAuthorityPlan();
    var avalonia = BuildAuthorityPlan();
    if (!wpf.SequenceEqual(avalonia))
        throw new InvalidOperationException("WPF authority and Avalonia Backstage plans differ.");

    var builder = new StringBuilder();
    builder.AppendLine("# FreeW Backstage Parity Evidence");
    builder.AppendLine();
    builder.AppendLine("> Generated by `tools/FreeW.BackstageParityEvidence` from `SisterBackstageEntryPlanner`. Do not edit by hand.");
    builder.AppendLine();
    builder.AppendLine("WPF is the semantic authority. `Import PDF (text only)` is included because the current WPF host exposes it as a direct Backstage command.");
    builder.AppendLine();
    builder.AppendLine("## Rail Contract");
    builder.AppendLine();
    builder.AppendLine("| Position | Label | Kind | Group | WPF | Avalonia |");
    builder.AppendLine("| ---: | --- | --- | --- | --- | --- |");
    for (var index = 0; index < wpf.Count; index++)
    {
        var entry = wpf[index];
        var label = entry.Kind == SisterBackstageEntryKind.Divider ? "separator" : entry.Label;
        var group = entry.DockBottom ? "bottom" : "top";
        builder.AppendLine($"| {index + 1} | {label} | {entry.Kind} | {group} | matched | matched |");
    }

    builder.AppendLine();
    builder.AppendLine("## Lifecycle And State");
    builder.AppendLine();
    builder.AppendLine("| Contract | WPF authority | Avalonia realization |");
    builder.AppendLine("| --- | --- | --- |");
    builder.AppendLine("| Back / Escape | Hide Backstage and return to the document host | Shared frame hides the modal and restores prior owner focus |");
    builder.AppendLine("| Pane activation | Keep Backstage open, select the rail row, replace pane content | Matched by shared frame state |");
    builder.AppendLine("| Direct command | Dismiss Backstage before invoking host callback | Matched by shared frame command dispatch |");
    builder.AppendLine("| Save | Save current document, falling back to Save As when untitled | Host-backed and distinct from Save a Copy |");
    builder.AppendLine("| Save a Copy | Write a separate file without changing active path or dirty state | Host-backed and covered by dialog-free state tests |");
    builder.AppendLine("| Close | Close through the window Closing dirty gate | Host callback calls `Close`; shared file workflow owns Save/Don't Save/Cancel |");
    builder.AppendLine("| Properties | Edit Title, Author, Subject, Keywords, and Comments from Info | Host-backed Avalonia dialog marks accepted edits dirty |");

    builder.AppendLine();
    builder.AppendLine("## Platform Capabilities");
    builder.AppendLine();
    builder.AppendLine("| Capability | WPF | Avalonia |");
    builder.AppendLine("| --- | --- | --- |");
    builder.AppendLine("| Print pane | Native `PrintDialog` plus print preview | Capability-gated CUPS printer discovery/submission plus print preview fallback |");
    builder.AppendLine("| PDF export | Host-backed | Host-backed |");
    builder.AppendLine("| XPS export | Native WPF XPS writer | Not exposed; no false XPS action is rendered |");
    builder.AppendLine("| Import PDF text | Direct current-authority command | Host-backed direct command |");

    builder.AppendLine();
    builder.AppendLine("## Authoritative Tests");
    builder.AppendLine();
    builder.AppendLine("- WPF `SisterBackstageEntryBuilderTests` locks exact order, entry kind, and docking.");
    builder.AppendLine("- WPF `FileLifecycleTests` locks Save a Copy path/dirty preservation and the close dirty gate.");
    builder.AppendLine("- Avalonia `BackstageViewTests` locks the realized rail, pane/direct state, Back/Escape, callbacks, Properties, and platform capability truthfulness.");
    builder.AppendLine("- Avalonia `CupsPrintServiceTests` and `PrintLifecycleTests` lock the existing CUPS route's capability gate, cancellation results, command routing, and owner-focus restoration.");
    builder.AppendLine();
    builder.AppendLine("## Remaining Platform Gaps");
    builder.AppendLine();
    builder.AppendLine("- On Linux/macOS hosts without a supported CUPS service, direct print remains deferred while preview and PDF remain available.");
    builder.AppendLine("- Avalonia has no user-facing XPS export route; XPS remains WPF-only at the application surface and the portable writer remains internal/shared code.");
    builder.AppendLine("- Foreground OS validation of printer dialogs, file pickers, modal focus restoration, and accessibility announcement order remains platform-runner evidence, not headless proof.");
    builder.AppendLine("- Cloud places, account-backed sharing, and online template/search services remain outside this local Backstage slice.");
    return builder.ToString();
}

static IReadOnlyList<SisterBackstageEntryPlan<string>> BuildAuthorityPlan()
{
    static string Pane() => "pane";
    static void Command() { }

    return SisterBackstageEntryPlanner.Build(new SisterBackstageEntryPlanSpec<string>(
        Pane,
        Command,
        Command,
        Command,
        Command,
        Pane,
        Pane,
        Pane)
    {
        Print = Command,
        SaveCopy = Command,
        Close = Command,
        BuildHomePane = Pane,
        UseNewPane = true,
        BuildOpenPane = Pane,
        ImportPdfText = Command,
        BuildSharePane = Pane,
        BuildSaveAsPane = Pane,
        BuildPrintPane = Pane,
        BuildExportPane = Pane,
        BuildAccountPane = Pane,
        HideRecentPane = true,
    });
}
