using System.Text;
using Free.Shared.Shell;

var root = FindRepositoryRoot();
var outputPath = GetOption("--output") is { } configuredOutput
    ? Path.GetFullPath(configuredOutput, Environment.CurrentDirectory)
    : Path.Combine(root, "docs", "parity", "freew-backstage-parity-20260720.md");
var report = BuildReport();

if (args.Contains("--check", StringComparer.Ordinal))
{
    if (!File.Exists(outputPath) ||
        !string.Equals(File.ReadAllText(outputPath), report, StringComparison.Ordinal))
    {
        Console.Error.WriteLine($"Generated evidence is stale: {outputPath}");
        Environment.ExitCode = 1;
    }
    else
    {
        Console.WriteLine($"Generated evidence is current: {outputPath}");
    }

    return;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, report, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated evidence: {outputPath}");
return;

string? GetOption(string name)
{
    var index = Array.IndexOf(args, name);
    if (index < 0)
        return null;
    if (index + 1 >= args.Length)
        throw new ArgumentException($"Missing value after {name}.");
    return args[index + 1];
}

static string FindRepositoryRoot()
{
    for (var current = new DirectoryInfo(AppContext.BaseDirectory);
         current is not null;
         current = current.Parent)
    {
        if (File.Exists(Path.Combine(current.FullName, "FreeW.slnx")))
            return current.FullName;
    }

    throw new InvalidOperationException("Could not locate the repository root containing FreeW.slnx.");
}

static string BuildReport()
{
    var wpf = BuildAuthorityPlan();
    var avalonia = BuildAuthorityPlan();
    if (!wpf.SequenceEqual(avalonia))
        throw new InvalidOperationException("WPF authority and Avalonia Backstage plans differ.");

    var builder = new StringBuilder();
    builder.AppendLine("# FreeW Backstage Parity Evidence");
    builder.AppendLine();
    builder.AppendLine("> Generated by `tools/FreeW.BackstageParityEvidence` from `SisterBackstageEntryPlanner`. Do not edit by hand.");
    builder.AppendLine();
    builder.AppendLine("WPF is the semantic authority. `Import PDF (text only)` is included because the current WPF host exposes it as a direct Backstage command.");
    builder.AppendLine();
    builder.AppendLine("## Rail Contract");
    builder.AppendLine();
    builder.AppendLine("| Position | Label | Kind | Group | WPF | Avalonia |");
    builder.AppendLine("| ---: | --- | --- | --- | --- | --- |");
    for (var index = 0; index < wpf.Count; index++)
    {
        var entry = wpf[index];
        var label = entry.Kind == SisterBackstageEntryKind.Divider ? "separator" : entry.Label;
        var group = entry.DockBottom ? "bottom" : "top";
        builder.AppendLine($"| {index + 1} | {label} | {entry.Kind} | {group} | matched | matched |");
    }

    builder.AppendLine();
    builder.AppendLine("## Lifecycle And State");
    builder.AppendLine();
    builder.AppendLine("| Contract | WPF authority | Avalonia realization |");
    builder.AppendLine("| --- | --- | --- |");
    builder.AppendLine("| Back / Escape | Hide Backstage and return to the document host | Shared frame hides the modal and restores prior owner focus |");
    builder.AppendLine("| Pane activation | Keep Backstage open, select the rail row, replace pane content | Matched by shared frame state |");
    builder.AppendLine("| Direct command | Dismiss Backstage before invoking host callback | Matched by shared frame command dispatch |");
    builder.AppendLine("| Save | Save current document, falling back to Save As when untitled | Host-backed and distinct from Save a Copy |");
    builder.AppendLine("| Save a Copy | Write a separate file without changing active path or dirty state | Host-backed and covered by dialog-free state tests |");
    builder.AppendLine("| Close | Close through the window Closing dirty gate | Host callback calls `Close`; shared file workflow owns Save/Don't Save/Cancel |");
    builder.AppendLine("| Properties | Edit Title, Author, Subject, Keywords, and Comments from Info | Host-backed Avalonia dialog marks accepted edits dirty |");

    builder.AppendLine();
    builder.AppendLine("## Platform Capabilities");
    builder.AppendLine();
    builder.AppendLine("| Capability | WPF | Avalonia |");
    builder.AppendLine("| --- | --- | --- |");
    builder.AppendLine("| Print pane | Native `PrintDialog` plus print preview | Print preview available; direct native print explicitly deferred |");
    builder.AppendLine("| PDF export | Host-backed | Host-backed |");
    builder.AppendLine("| XPS export | Native WPF XPS writer | Not exposed; no false XPS action is rendered |");
    builder.AppendLine("| Import PDF text | Direct current-authority command | Host-backed direct command |");

    builder.AppendLine();
    builder.AppendLine("## Authoritative Tests");
    builder.AppendLine();
    builder.AppendLine("- WPF `SisterBackstageEntryBuilderTests` locks exact order, entry kind, and docking.");
    builder.AppendLine("- WPF `FileLifecycleTests` locks Save a Copy path/dirty preservation and the close dirty gate.");
    builder.AppendLine("- Avalonia `BackstageViewTests` locks the realized rail, pane/direct state, Back/Escape, callbacks, Properties, and platform capability truthfulness.");
    builder.AppendLine();
    builder.AppendLine("## Remaining Platform Gaps");
    builder.AppendLine();
    builder.AppendLine("- Avalonia has no native printer-selection service in the current target; direct print remains deferred while preview and PDF are available.");
    builder.AppendLine("- Avalonia has no XPS writer; XPS remains WPF-only and is omitted from the Avalonia Export pane.");
    builder.AppendLine("- Foreground OS validation of printer dialogs, file pickers, modal focus restoration, and accessibility announcement order remains platform-runner evidence, not headless proof.");
    builder.AppendLine("- Cloud places, account-backed sharing, and online template/search services remain outside this local Backstage slice.");
    return builder.ToString();
}

static IReadOnlyList<SisterBackstageEntryPlan<string>> BuildAuthorityPlan()
{
    static string Pane() => "pane";
    static void Command() { }

    return SisterBackstageEntryPlanner.Build(new SisterBackstageEntryPlanSpec<string>(
        Pane,
        Command,
        Command,
        Command,
        Command,
        Pane,
        Pane,
        Pane)
    {
        Print = Command,
        SaveCopy = Command,
        Close = Command,
        BuildHomePane = Pane,
        UseNewPane = true,
        BuildOpenPane = Pane,
        ImportPdfText = Command,
        BuildSharePane = Pane,
        BuildSaveAsPane = Pane,
        BuildPrintPane = Pane,
        BuildExportPane = Pane,
        BuildAccountPane = Pane,
        HideRecentPane = true,
    });
}
