<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FreeP.App.Presentation.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeP.App.Localization\FreeP.App.Localization.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Drawing\Free.Shared.Drawing.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.IO\Free.Shared.IO.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Pdf\Free.Shared.Pdf.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Ribbon\Free.Shared.Ribbon.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Shell\Free.Shared.Shell.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Theme\Free.Shared.Theme.csproj" />
    <ProjectReference Include="..\FreeP.Core.IO\FreeP.Core.IO.csproj" />
    <ProjectReference Include="..\FreeP.Core.Model\FreeP.Core.Model.csproj" />
  </ItemGroup>

</Project>
