<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Free.Shared.Drawing\Free.Shared.Drawing.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.IO\Free.Shared.IO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Drawing" />
  </ItemGroup>

</Project>
