using System.Collections.Generic;
using System.Windows.Controls;

namespace FreeX.App.Host;

// Auto-generated hidden control backplane. These named controls used to live in the
// hand-authored ribbon XAML; the visible ribbon is now declarative (RibbonWpfRenderer).
// They remain as invisible state/handler holders so existing code compiles and runs;
// their state is mirrored onto the rendered ribbon by WireDeclarativeStateSync, and they
// serve as the 'sender' for handlers invoked through the native command registry.
public partial class MainWindow
{
    private readonly System.Windows.Controls.StackPanel HomeRibbonPanel = new();
    private readonly System.Windows.Controls.ComboBox FontNameBox = new();
    private readonly System.Windows.Controls.ComboBox FontSizeBox = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton BoldButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ItalicButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton UnderlineButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton StrikeButton = new();
    private readonly System.Windows.Controls.Button BordersMenuButton = new();
    private readonly System.Windows.Shapes.Rectangle FillColorBar = new();
    private readonly System.Windows.Shapes.Rectangle FontColorBar = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignTopBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignMiddleBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignBottomBtn = new();
    private readonly System.Windows.Controls.Button OrientationPickerButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton WrapTextBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignLeftBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignCenterBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton AlignRightBtn = new();
    private readonly System.Windows.Controls.ComboBox NumberFormatBox = new();
    private readonly System.Windows.Controls.ContextMenu FormatTableGalleryMenu = new();
    private readonly System.Windows.Controls.Button ShapesBtn = new();
    private readonly System.Windows.Controls.ComboBox PageLayoutScaleWidthBox = new();
    private readonly System.Windows.Controls.ComboBox PageLayoutScaleHeightBox = new();
    private readonly System.Windows.Controls.ComboBox PageLayoutScalePercentBox = new();
    private readonly System.Windows.Controls.CheckBox PageLayoutViewGridlinesChk = new();
    private readonly System.Windows.Controls.CheckBox PageLayoutPrintGridlinesChk = new();
    private readonly System.Windows.Controls.CheckBox PageLayoutViewHeadingsChk = new();
    private readonly System.Windows.Controls.CheckBox PageLayoutPrintHeadingsChk = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ShowFormulasButton = new();
    private readonly System.Windows.Controls.Button ReviewNewThreadedCommentButton = new();
    private readonly System.Windows.Controls.Button ReviewDeleteThreadedCommentButton = new();
    private readonly System.Windows.Controls.Button ReviewPreviousThreadedCommentButton = new();
    private readonly System.Windows.Controls.Button ReviewNextThreadedCommentButton = new();
    private readonly System.Windows.Controls.Button ReviewNewNoteButton = new();
    private readonly System.Windows.Controls.Button ReviewEditNoteButton = new();
    private readonly System.Windows.Controls.Button ReviewDeleteNoteButton = new();
    private readonly System.Windows.Controls.Button ReviewPreviousNoteButton = new();
    private readonly System.Windows.Controls.Button ReviewNextNoteButton = new();
    private readonly System.Windows.Controls.Button ProtectSheetButton = new();
    private readonly System.Windows.Controls.Button ProtectWorkbookButton = new();
    private readonly System.Windows.Controls.Button AllowEditRangesButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ViewNormalButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ViewPageBreakPreviewButton = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ViewPageLayoutButton = new();
    private readonly System.Windows.Controls.CheckBox ViewGridlinesChk = new();
    private readonly System.Windows.Controls.CheckBox ViewHeadersChk = new();
    private readonly System.Windows.Controls.CheckBox ViewRulerChk = new();
    private readonly System.Windows.Controls.CheckBox ViewFormulaBarChk = new();
    private readonly System.Windows.Controls.Button ViewNewWindowBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton SplitViewBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ViewSideBySideBtn = new();
    private readonly System.Windows.Controls.Primitives.ToggleButton ViewSynchronousScrollingBtn = new();
    private readonly System.Windows.Controls.Button ViewSwitchWindowsBtn = new();
    private readonly System.Windows.Controls.Button ViewHideWindowBtn = new();
    private readonly System.Windows.Controls.Button ViewUnhideWindowBtn = new();
    private readonly System.Windows.Controls.Button ViewResetWindowPositionBtn = new();
    private readonly System.Windows.Controls.Button ShapeFormatGradientButton = new();
    private readonly System.Windows.Controls.Button ShapeFormatEffectsButton = new();
    private readonly System.Windows.Controls.Button PictureFormatCropButton = new();
    private readonly System.Windows.Controls.MenuItem PictureFormatCropMenuItem = new();
    private readonly System.Windows.Controls.MenuItem PictureFormatResetCropMenuItem = new();
    private readonly System.Windows.Controls.CheckBox TableDesignTotalRowBtn = new();
    private readonly System.Windows.Controls.CheckBox TableDesignFirstColumnBtn = new();
    private readonly System.Windows.Controls.CheckBox TableDesignLastColumnBtn = new();
    private readonly System.Windows.Controls.CheckBox TableDesignBandedRowsBtn = new();
    private readonly System.Windows.Controls.CheckBox TableDesignBandedColumnsBtn = new();
    private readonly System.Windows.Controls.CheckBox TableDesignFilterButtonBtn = new();
    private readonly System.Windows.Controls.ContextMenu TableDesignStyleGalleryMenu = new();
    private readonly AutomationInvokeButton HelpOnlineButton = new();

    /// <summary>Backplane controls that carry a ribbon CommandName, keyed by it.</summary>
    private readonly Dictionary<string, Control> RibbonBackplaneControls = new(System.StringComparer.Ordinal);

    private void InitializeRibbonControlBackplane()
    {
        RibbonMetadata.SetCommandName(FontNameBox, "Font");
        RibbonBackplaneControls["Font"] = FontNameBox;
        RibbonMetadata.SetCommandName(FontSizeBox, "Font Size");
        RibbonBackplaneControls["Font Size"] = FontSizeBox;
        RibbonMetadata.SetCommandName(BoldButton, "Bold");
        RibbonBackplaneControls["Bold"] = BoldButton;
        RibbonMetadata.SetCommandName(ItalicButton, "Italic");
        RibbonBackplaneControls["Italic"] = ItalicButton;
        RibbonMetadata.SetCommandName(UnderlineButton, "Underline");
        RibbonBackplaneControls["Underline"] = UnderlineButton;
        RibbonMetadata.SetCommandName(StrikeButton, "Strikethrough");
        RibbonBackplaneControls["Strikethrough"] = StrikeButton;
        RibbonMetadata.SetCommandName(BordersMenuButton, "Borders");
        RibbonBackplaneControls["Borders"] = BordersMenuButton;
        RibbonMetadata.SetCommandName(AlignTopBtn, "Top Align");
        RibbonBackplaneControls["Top Align"] = AlignTopBtn;
        RibbonMetadata.SetCommandName(AlignMiddleBtn, "Middle Align");
        RibbonBackplaneControls["Middle Align"] = AlignMiddleBtn;
        RibbonMetadata.SetCommandName(AlignBottomBtn, "Bottom Align");
        RibbonBackplaneControls["Bottom Align"] = AlignBottomBtn;
        RibbonMetadata.SetCommandName(OrientationPickerButton, "Orientation");
        RibbonBackplaneControls["Orientation"] = OrientationPickerButton;
        RibbonMetadata.SetCommandName(WrapTextBtn, "Wrap Text");
        RibbonBackplaneControls["Wrap Text"] = WrapTextBtn;
        RibbonMetadata.SetCommandName(AlignLeftBtn, "Align Left");
        RibbonBackplaneControls["Align Left"] = AlignLeftBtn;
        RibbonMetadata.SetCommandName(AlignCenterBtn, "Center");
        RibbonBackplaneControls["Center"] = AlignCenterBtn;
        RibbonMetadata.SetCommandName(AlignRightBtn, "Align Right");
        RibbonBackplaneControls["Align Right"] = AlignRightBtn;
        RibbonMetadata.SetCommandName(NumberFormatBox, "Number Format");
        RibbonBackplaneControls["Number Format"] = NumberFormatBox;
        RibbonMetadata.SetCommandName(ShapesBtn, "Shapes");
        RibbonBackplaneControls["Shapes"] = ShapesBtn;
        RibbonMetadata.SetCommandName(PageLayoutScaleWidthBox, "Scale Width");
        RibbonBackplaneControls["Scale Width"] = PageLayoutScaleWidthBox;
        RibbonMetadata.SetCommandName(PageLayoutScaleHeightBox, "Scale Height");
        RibbonBackplaneControls["Scale Height"] = PageLayoutScaleHeightBox;
        RibbonMetadata.SetCommandName(PageLayoutScalePercentBox, "Scale Percent");
        RibbonBackplaneControls["Scale Percent"] = PageLayoutScalePercentBox;
        RibbonMetadata.SetCommandName(PageLayoutViewGridlinesChk, "View Gridlines");
        RibbonBackplaneControls["View Gridlines"] = PageLayoutViewGridlinesChk;
        RibbonMetadata.SetCommandName(PageLayoutPrintGridlinesChk, "Print Gridlines");
        RibbonBackplaneControls["Print Gridlines"] = PageLayoutPrintGridlinesChk;
        RibbonMetadata.SetCommandName(PageLayoutViewHeadingsChk, "View Headings");
        RibbonBackplaneControls["View Headings"] = PageLayoutViewHeadingsChk;
        RibbonMetadata.SetCommandName(PageLayoutPrintHeadingsChk, "Print Headings");
        RibbonBackplaneControls["Print Headings"] = PageLayoutPrintHeadingsChk;
        RibbonMetadata.SetCommandName(ShowFormulasButton, "Show Formulas");
        RibbonBackplaneControls["Show Formulas"] = ShowFormulasButton;
        RibbonMetadata.SetCommandName(ReviewNewThreadedCommentButton, "New Comment");
        RibbonBackplaneControls["New Comment"] = ReviewNewThreadedCommentButton;
        RibbonMetadata.SetCommandName(ReviewDeleteThreadedCommentButton, "Delete Comment");
        RibbonBackplaneControls["Delete Comment"] = ReviewDeleteThreadedCommentButton;
        RibbonMetadata.SetCommandName(ReviewPreviousThreadedCommentButton, "Previous Comment");
        RibbonBackplaneControls["Previous Comment"] = ReviewPreviousThreadedCommentButton;
        RibbonMetadata.SetCommandName(ReviewNextThreadedCommentButton, "Next Comment");
        RibbonBackplaneControls["Next Comment"] = ReviewNextThreadedCommentButton;
        RibbonMetadata.SetCommandName(ReviewNewNoteButton, "New Note");
        RibbonBackplaneControls["New Note"] = ReviewNewNoteButton;
        RibbonMetadata.SetCommandName(ReviewEditNoteButton, "Edit Note");
        RibbonBackplaneControls["Edit Note"] = ReviewEditNoteButton;
        RibbonMetadata.SetCommandName(ReviewDeleteNoteButton, "Delete Note");
        RibbonBackplaneControls["Delete Note"] = ReviewDeleteNoteButton;
        RibbonMetadata.SetCommandName(ReviewPreviousNoteButton, "Previous Note");
        RibbonBackplaneControls["Previous Note"] = ReviewPreviousNoteButton;
        RibbonMetadata.SetCommandName(ReviewNextNoteButton, "Next Note");
        RibbonBackplaneControls["Next Note"] = ReviewNextNoteButton;
        RibbonMetadata.SetCommandName(ProtectSheetButton, "Protect Sheet");
        RibbonBackplaneControls["Protect Sheet"] = ProtectSheetButton;
        RibbonMetadata.SetCommandName(ProtectWorkbookButton, "Protect Workbook");
        RibbonBackplaneControls["Protect Workbook"] = ProtectWorkbookButton;
        RibbonMetadata.SetCommandName(AllowEditRangesButton, "Allow Users to Edit Ranges");
        RibbonBackplaneControls["Allow Users to Edit Ranges"] = AllowEditRangesButton;
        RibbonMetadata.SetCommandName(ViewNormalButton, "Normal");
        RibbonBackplaneControls["Normal"] = ViewNormalButton;
        RibbonMetadata.SetCommandName(ViewPageBreakPreviewButton, "Page Break Preview");
        RibbonBackplaneControls["Page Break Preview"] = ViewPageBreakPreviewButton;
        RibbonMetadata.SetCommandName(ViewPageLayoutButton, "Page Layout");
        RibbonBackplaneControls["Page Layout"] = ViewPageLayoutButton;
        RibbonMetadata.SetCommandName(ViewGridlinesChk, "Gridlines");
        RibbonBackplaneControls["Gridlines"] = ViewGridlinesChk;
        RibbonMetadata.SetCommandName(ViewHeadersChk, "Headings");
        RibbonBackplaneControls["Headings"] = ViewHeadersChk;
        RibbonMetadata.SetCommandName(ViewRulerChk, "Ruler");
        RibbonBackplaneControls["Ruler"] = ViewRulerChk;
        RibbonMetadata.SetCommandName(ViewFormulaBarChk, "Formula Bar");
        RibbonBackplaneControls["Formula Bar"] = ViewFormulaBarChk;
        RibbonMetadata.SetCommandName(ViewNewWindowBtn, "New Window");
        RibbonBackplaneControls["New Window"] = ViewNewWindowBtn;
        RibbonMetadata.SetCommandName(SplitViewBtn, "Split");
        RibbonBackplaneControls["Split"] = SplitViewBtn;
        RibbonMetadata.SetCommandName(ViewSideBySideBtn, "View Side by Side");
        RibbonBackplaneControls["View Side by Side"] = ViewSideBySideBtn;
        RibbonMetadata.SetCommandName(ViewSynchronousScrollingBtn, "Synchronous Scrolling");
        RibbonBackplaneControls["Synchronous Scrolling"] = ViewSynchronousScrollingBtn;
        RibbonMetadata.SetCommandName(ViewSwitchWindowsBtn, "Switch Windows");
        RibbonBackplaneControls["Switch Windows"] = ViewSwitchWindowsBtn;
        RibbonMetadata.SetCommandName(ViewHideWindowBtn, "Hide");
        RibbonBackplaneControls["Hide"] = ViewHideWindowBtn;
        RibbonMetadata.SetCommandName(ViewUnhideWindowBtn, "Unhide");
        RibbonBackplaneControls["Unhide"] = ViewUnhideWindowBtn;
        RibbonMetadata.SetCommandName(ViewResetWindowPositionBtn, "Reset Window Position");
        RibbonBackplaneControls["Reset Window Position"] = ViewResetWindowPositionBtn;
        RibbonMetadata.SetCommandName(ShapeFormatGradientButton, "Shape Gradient");
        RibbonBackplaneControls["Shape Gradient"] = ShapeFormatGradientButton;
        RibbonMetadata.SetCommandName(ShapeFormatEffectsButton, "Shape Effects");
        RibbonBackplaneControls["Shape Effects"] = ShapeFormatEffectsButton;
        RibbonMetadata.SetCommandName(PictureFormatCropButton, "Crop Picture");
        RibbonBackplaneControls["Crop Picture"] = PictureFormatCropButton;
        RibbonMetadata.SetCommandName(PictureFormatCropMenuItem, "Crop");
        RibbonBackplaneControls["Crop"] = PictureFormatCropMenuItem;
        RibbonMetadata.SetCommandName(PictureFormatResetCropMenuItem, "Reset Crop");
        RibbonBackplaneControls["Reset Crop"] = PictureFormatResetCropMenuItem;
        RibbonMetadata.SetCommandName(TableDesignTotalRowBtn, "Total Row");
        RibbonBackplaneControls["Total Row"] = TableDesignTotalRowBtn;
        RibbonMetadata.SetCommandName(TableDesignFirstColumnBtn, "First Column");
        RibbonBackplaneControls["First Column"] = TableDesignFirstColumnBtn;
        RibbonMetadata.SetCommandName(TableDesignLastColumnBtn, "Last Column");
        RibbonBackplaneControls["Last Column"] = TableDesignLastColumnBtn;
        RibbonMetadata.SetCommandName(TableDesignBandedRowsBtn, "Banded Rows");
        RibbonBackplaneControls["Banded Rows"] = TableDesignBandedRowsBtn;
        RibbonMetadata.SetCommandName(TableDesignBandedColumnsBtn, "Banded Columns");
        RibbonBackplaneControls["Banded Columns"] = TableDesignBandedColumnsBtn;
        RibbonMetadata.SetCommandName(TableDesignFilterButtonBtn, "Filter Button");
        RibbonBackplaneControls["Filter Button"] = TableDesignFilterButtonBtn;
        RibbonMetadata.SetCommandName(HelpOnlineButton, "Help Online");
        RibbonBackplaneControls["Help Online"] = HelpOnlineButton;
    }
}
