using FreeX.App.Presentation.PivotUI;
using FreeX.Core.Model;

namespace FreeX.App.Host;

// WPF localization helpers stay here. Option order, fallback labels, validation metadata, number-format
// catalog/input rules, index/base-field/show-values-as resolution, caption generation, and result building
// delegate to the portable PivotValueFieldPlanner so the logic is single-sourced for Avalonia/macOS.
public static class PivotValueFieldSettingsDialogPlanner
{
    public static string AutomaticBaseFieldLabel =>
        UiText.Get(PivotValueFieldPlanner.AutomaticBaseField.ResourceKey);

    public static readonly (string Label, string Value)[] SummaryFunctions =
        LocalizeOptions(PivotValueFieldPlanner.SummaryFunctions);

    public static readonly (string Label, PivotShowValuesAs Value)[] ShowValuesAsOptions =
        LocalizeOptions(PivotValueFieldPlanner.ShowValuesAsOptions);

    public static int FindSummaryFunctionIndex(string? summaryFunction) =>
        PivotValueFieldPlanner.FindSummaryFunctionIndex(summaryFunction);

    public static int FindShowValuesAsIndex(PivotShowValuesAs showValuesAs) =>
        PivotValueFieldPlanner.FindShowValuesAsIndex(showValuesAs);

    public static int FindBaseFieldIndex(int? baseFieldIndex, int sourceHeaderCount) =>
        PivotValueFieldPlanner.FindBaseFieldIndex(baseFieldIndex, sourceHeaderCount);

    public static int FindNumberFormatPresetIndex(int? numberFormatId)
        => PivotValueFieldPlanner.FindNumberFormatPresetIndex(numberFormatId);

    public static string SummaryFunctionFromIndex(int selectedIndex) =>
        PivotValueFieldPlanner.SummaryFunctionFromIndex(selectedIndex);

    public static PivotShowValuesAs ShowValuesAsFromIndex(int selectedIndex) =>
        PivotValueFieldPlanner.ShowValuesAsFromIndex(selectedIndex);

    public static bool ShowValuesAsRequiresBaseField(PivotShowValuesAs showValuesAs) =>
        PivotValueFieldPlanner.ShowValuesAsRequiresBaseField(showValuesAs);

    public static int? ResolveBaseFieldIndex(PivotShowValuesAs showValuesAs, int selectedIndex) =>
        PivotValueFieldPlanner.ResolveBaseFieldIndex(showValuesAs, selectedIndex);

    public static string? ResolveBaseItem(PivotShowValuesAs showValuesAs, string? text) =>
        PivotValueFieldPlanner.ResolveBaseItem(showValuesAs, text);

    public static bool TryValidateShowValuesAs(
        PivotShowValuesAs showValuesAs,
        int? baseFieldIndex,
        string? baseItem,
        out string? error)
    {
        var validationError = PivotValueFieldPlanner.ValidateShowValuesAs(showValuesAs, baseFieldIndex, baseItem);
        var errorPlan = PivotValueFieldPlanner.DescribeValidationError(validationError);
        if (errorPlan is null)
        {
            error = null;
            return true;
        }

        error = UiText.Get(errorPlan.ResourceKey);
        return false;
    }

    public static PivotDataFieldModel CreateResult(
        PivotDataFieldModel initialField,
        IReadOnlyList<string>? sourceHeaders,
        string? customName,
        int summaryFunctionIndex,
        int showValuesAsIndex,
        int baseFieldSelectedIndex,
        string? baseItemText,
        int? numberFormatId,
        string? numberFormatCode)
    {
        return PivotValueFieldPlanner.CreateResult(
            initialField,
            sourceHeaders ?? [],
            customName,
            summaryFunctionIndex,
            showValuesAsIndex,
            baseFieldSelectedIndex,
            baseItemText,
            numberFormatId,
            numberFormatCode);
    }

    public static PivotDataFieldModel CreateResult(
        PivotDataFieldModel initialField,
        string? customName,
        int summaryFunctionIndex,
        int showValuesAsIndex,
        int baseFieldSelectedIndex,
        string? baseItemText,
        int? numberFormatId,
        string? numberFormatCode) =>
        CreateResult(
            initialField,
            sourceHeaders: [],
            customName,
            summaryFunctionIndex,
            showValuesAsIndex,
            baseFieldSelectedIndex,
            baseItemText,
            numberFormatId,
            numberFormatCode);

    public static string ResolveResultName(
        PivotDataFieldModel initialField,
        IReadOnlyList<string> sourceHeaders,
        string? customName,
        string summaryFunction) =>
        PivotValueFieldPlanner.ResolveResultName(initialField, sourceHeaders, customName, summaryFunction);

    public static bool IsAutoGeneratedCaption(PivotDataFieldModel field, IReadOnlyList<string> sourceHeaders) =>
        PivotValueFieldPlanner.IsAutoGeneratedCaption(field, sourceHeaders);

    public static string CreateDefaultCaption(
        IReadOnlyList<string> sourceHeaders,
        int sourceFieldIndex,
        string summaryFunction) =>
        PivotValueFieldPlanner.CreateDefaultCaption(sourceHeaders, sourceFieldIndex, summaryFunction);

    public static string CreateDefaultCaption(string sourceCaption, string summaryFunction) =>
        PivotValueFieldPlanner.CreateDefaultCaption(sourceCaption, summaryFunction);

    private static (string Label, TValue Value)[] LocalizeOptions<TValue>(
        IReadOnlyList<PivotValueFieldOption<TValue>> sharedOptions) =>
        sharedOptions
            .Select(option => (UiText.Get(option.ResourceKey), option.Value))
            .ToArray();
}
