<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FreeX.Core.Calc\FreeX.Core.Calc.csproj" />
    <ProjectReference Include="..\FreeX.Core.Commands\FreeX.Core.Commands.csproj" />
    <ProjectReference Include="..\FreeX.Core.Formula\FreeX.Core.Formula.csproj" />
    <ProjectReference Include="..\FreeX.Core.IO\FreeX.Core.IO.csproj" />
    <ProjectReference Include="..\FreeX.Core.Model\FreeX.Core.Model.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
</Project>
