<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\tools\Free.ToolsShared\Free.ToolsShared.csproj" />
    <ProjectReference Include="..\..\FreeW.Core.Model\FreeW.Core.Model.csproj" />
    <ProjectReference Include="..\..\FreeW.Core.IO\FreeW.Core.IO.csproj" />
  </ItemGroup>

</Project>
