using FreeX.Core.Formula;
using FreeX.Core.Model;
using FluentAssertions;

namespace FreeX.Core.Formula.Tests;

/// <summary>
/// R55-render-number-format-display-5-1: a multi-section format's negative section is always
/// formatted against Math.Abs(value) (SelectPositionalSection already does this), so any leading
/// '-' surviving in the formatted text can only be an author-literal character written into that
/// section's format code (e.g. the "-0" in "0;-0") -- never .NET's own auto-generated sign, which
/// can only occur for a genuinely negative input. NumberFormatter previously stripped that literal
/// '-' whenever the rounded digits were all zero, treating an author-literal minus the same as a
/// genuine negative-zero artifact and silently dropping the sign the user explicitly wrote.
/// </summary>
public class R55_NumberFormatterLiteralNegativeSectionSignTests
{
    [Fact]
    public void NegativeValueRoundingToZero_WithLiteralMinusInNegativeSection_KeepsTheLiteralSign()
    {
        // "0;-0" applied to -0.4: 0.4 rounds to "0" under "0", but the negative section's literal
        // '-' must survive -- Excel shows "-0", not "0".
        NumberFormatter.Format(new NumberValue(-0.4), "0;-0").Should().Be("-0");
    }

    [Fact]
    public void NegativeValueRoundingToZero_TwoDecimalLiteralMinus_KeepsTheLiteralSign()
    {
        NumberFormatter.Format(new NumberValue(-0.001), "0.00;-0.00").Should().Be("-0.00");
    }

    [Fact]
    public void PositiveValueRoundingToZero_NoNegativeSection_SiblingNoRegression()
    {
        // A positive value routes to the positive section ("0"), which has no literal minus at
        // all -- unaffected by the fix, still just "0".
        NumberFormatter.Format(new NumberValue(0.4), "0;-0").Should().Be("0");
    }

    [Fact]
    public void GenuineAutoGeneratedNegativeZero_SingleSectionFormat_StillStripsTheSign_SiblingNoRegression()
    {
        // A single-section format has no negative section at all -- FormatNumber's own top-level
        // sign tracking (separate from the ApplyNumericFormat change here) still strips the
        // auto-generated "-" for a tiny negative value that rounds to zero under "0.00", since
        // there is no literal '-' anywhere in this format to preserve.
        NumberFormatter.Format(new NumberValue(-0.001), "0.00").Should().Be("0.00");
    }
}
