<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FreeX.Core.Model\FreeX.Core.Model.csproj" />
    <ProjectReference Include="..\FreeX.Core.Formula\FreeX.Core.Formula.csproj" />
    <ProjectReference Include="..\FreeX.Core.Calc\FreeX.Core.Calc.csproj" />
    <ProjectReference Include="..\FreeX.Core.Commands\FreeX.Core.Commands.csproj" />
    <ProjectReference Include="..\FreeX.Core.IO\FreeX.Core.IO.csproj" />
    <ProjectReference Include="..\FreeX.App.Presentation\FreeX.App.Presentation.csproj" />
    <ProjectReference Include="..\FreeX.App.Localization\FreeX.App.Localization.csproj" />
    <ProjectReference Include="..\FreeX.App.Services\FreeX.App.Services.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Drawing\Free.Shared.Drawing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FreeX.App.UI.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Drawing" />
    <Using Include="FreeX.App.Localization.LocalizedUiText" Alias="UiText" />
  </ItemGroup>

</Project>
