using FreeX.Core.Model;

namespace FreeX.Core.IO;

/// <summary>
/// Backlog item "editAs-preserve" investigation note: <c>xdr:twoCellAnchor/@editAs</c>
/// (<c>twoCell</c>|<c>oneCell</c>|<c>absolute</c>) controls a drawing object's move/resize behavior when its
/// spanned rows/columns are resized. For picture/shape/text-box objects loaded from a source .xlsx (the only
/// case where a real <c>twoCellAnchor</c> XML element exists; freshly-authored objects are always written as
/// <c>oneCellAnchor</c>, which has no <c>editAs</c> attribute in the schema), the ORIGINAL anchor element --
/// <c>editAs</c> included -- is preserved verbatim by <c>XlsxWorksheetDrawingPartMerger</c>/
/// <c>XlsxSourceDrawingGeometryRewriter</c> rather than being regenerated by this applier's caller, so a
/// save-then-reload already keeps <c>editAs</c> unchanged (see <c>Backlog_editAs_preserve_Tests</c> for the
/// round-trip proof). The one place <c>editAs</c> is genuinely dropped ON SAVE is chart anchors -- charts have
/// no verbatim-preservation path and <c>XlsxWorksheetChartWriter</c> always regenerates their anchor XML
/// without ever writing <c>editAs</c> -- but fixing that needs a new <see cref="ChartModel"/> field, which is
/// out of this file's edit scope. DEFERRED (see <c>Backlog_editAs_preserve_Tests</c>'s
/// <c>XlsxAdapter_ChartTwoCellAnchorEditAs_IsCurrentlyDroppedOnSave_DeferredGap</c> test for the pinned gap).
/// <para>
/// R127-editas-shift-gate: the backlog item above only ever scoped the SAVE round-trip of the raw XML
/// attribute -- it explicitly did not model <c>editAs</c> on <see cref="PictureModel"/>/
/// <see cref="DrawingShapeModel"/>/<see cref="TextBoxModel"/> or implement the actual move/resize-on-shift
/// behavior it describes ("that is a much larger, separately-scoped modeling change", per that backlog's own
/// doc comment). That left a real, separate bug: <c>RowColumnShiftHelpers.ShiftPictures</c>/
/// <c>ShiftDrawingShapes</c>/<c>ShiftTextBoxes</c> unconditionally moved+resized every picture/shape/text box
/// on row/column insert-delete, using twoCellAnchor "move and size with cells" semantics even for a source
/// anchor that declared oneCellAnchor ("move but don't size") or absoluteAnchor ("don't move or size") --
/// silently corrupting an in-session picture/shape/text box's geometry (and, downstream, what
/// <c>XlsxSourceDrawingGeometryRewriter</c>'s save-time skip-gate then writes back into the preserved anchor's
/// <c>from</c>/<c>to</c>/<c>ext</c> child elements) even though the anchor element's own <c>editAs</c>
/// attribute itself kept round-tripping correctly. <see cref="ApplyToPicture"/>/<see cref="ApplyToTextBox"/>/
/// <see cref="ApplyToShape"/> now capture <c>anchor.Kind</c> onto the model's own <c>DrawingAnchorKind</c>
/// field (mirroring <see cref="ApplyToChart"/>'s existing <c>chart.DrawingAnchorKind = anchor.Kind</c>), and
/// <c>RowColumnShiftHelpers</c> gates the move/resize on it exactly like it already does for charts.
/// </para>
/// </summary>
internal static class XlsxDrawingAnchorApplier
{
    // Excel's real ceilings (1,048,576 rows x 16,384 columns), expressed zero-based to match the
    // reader's FromColumnZeroBased/ToColumnZeroBased/FromRowZeroBased/ToRowZeroBased fields. The writer
    // side already caps at these same 1-based limits (see XlsxSourceDrawingGeometryRewriter.MaxColumnIndex/
    // MaxRowIndex, XlsxWorksheetChartWriter.MaxColumnIndex/MaxRowIndex). A source file can contain a
    // schema-valid but absurd index (e.g. col 3,000,000,000) that is correctly ordered relative to its
    // partner marker; without clamping, SumColumnPixels/SumRowPixels below would loop billions of times
    // and hang the load. Clamping here matches Excel effectively ignoring/truncating such a value.
    private const uint MaxColumnIndexZeroBased = 16383;
    private const uint MaxRowIndexZeroBased = 1048575;

    private static uint ClampColumn(uint zeroBased) => Math.Min(zeroBased, MaxColumnIndexZeroBased);

    private static uint ClampRow(uint zeroBased) => Math.Min(zeroBased, MaxRowIndexZeroBased);

    public static void ApplyToChart(ChartModel chart, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        var fromColumn = ClampColumn(anchor.FromColumnZeroBased);
        var fromRow = ClampRow(anchor.FromRowZeroBased);

        chart.DrawingAnchorKind = anchor.Kind;
        chart.Left = anchor.AbsoluteLeft ?? (SumColumnPixels(sheet, 1, fromColumn) + anchor.FromColumnOffset);
        chart.Top = anchor.AbsoluteTop ?? (SumRowPixels(sheet, 1, fromRow) + anchor.FromRowOffset);

        var width = anchor.Width ?? (
            SumColumnPixels(sheet, fromColumn + 1, ZeroBasedSpan(fromColumn, ClampColumn(anchor.ToColumnZeroBased!.Value)))
            + anchor.ToColumnOffset!.Value
            - anchor.FromColumnOffset);
        var height = anchor.Height ?? (
            SumRowPixels(sheet, fromRow + 1, ZeroBasedSpan(fromRow, ClampRow(anchor.ToRowZeroBased!.Value)))
            + anchor.ToRowOffset!.Value
            - anchor.FromRowOffset);
        if (width > 0)
            chart.Width = width;
        if (height > 0)
            chart.Height = height;
    }

    public static void ApplyToPicture(PictureModel picture, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        // R127-editas-shift-gate: mirrors ApplyToChart's `chart.DrawingAnchorKind = anchor.Kind` --
        // see this file's top doc comment for why the picture model needs its own copy of this now.
        picture.DrawingAnchorKind = anchor.Kind;
        var (width, height) = GetAnchorSize(anchor, sheet);
        if (width > 0)
            picture.Width = width;
        if (height > 0)
            picture.Height = height;
        // R94-hidden-span fix: capture the baseline as whatever Width/Height actually ended up being
        // after load -- including the retained class-default when the anchor's own span fell entirely
        // within hidden rows/columns (GetAnchorSize returns 0 for that axis, so the `> 0` guard above
        // left the model at its default rather than a fabricated small size). Gating this capture on
        // `width > 0`/`height > 0` too (as it originally was) left SourceLoadedWidthPixels/HeightPixels
        // null for such a picture, which defeats XlsxSourceDrawingGeometryRewriter.RewriteAnchorGeometry's
        // save-time skip-gate (it compares this baseline against the CURRENT live Width/Height, and null
        // never compares equal) -- forcing a bogus recompute that walks the sheet using the retained
        // default 240x140 size and relocates the object's `to` marker to an unrelated, distant cell even
        // though the picture itself was never touched. Recording the POST-guard value here instead means
        // the baseline trivially matches the live value for an untouched picture (hidden-span or not),
        // so the save-time skip-gate fires correctly and the original `to` marker is preserved verbatim.
        picture.SourceLoadedWidthPixels = picture.Width;
        picture.SourceLoadedHeightPixels = picture.Height;
        // For an absoluteAnchor the caller resolves Anchor to the sheet's origin cell (row 1/col
        // 1, pixel (0,0)), so applying the anchor's absolute pixel position as the sub-cell offset
        // reproduces the intended on-sheet position, mirroring how ApplyToChart applies
        // AbsoluteLeft/AbsoluteTop directly (see lines 30-31 above).
        picture.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        picture.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    public static void ApplyToTextBox(TextBoxModel textBox, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        // R127-editas-shift-gate: see the matching comment in ApplyToPicture.
        textBox.DrawingAnchorKind = anchor.Kind;
        var (width, height) = GetAnchorSize(anchor, sheet);
        if (width > 0)
            textBox.Width = width;
        if (height > 0)
            textBox.Height = height;
        // R94-hidden-span fix: see the matching comment in ApplyToPicture -- always capture the baseline
        // as the POST-guard Width/Height (including the retained default when the span is entirely
        // hidden) rather than only when GetAnchorSize produced a positive value, so the save-time
        // skip-gate in XlsxSourceDrawingGeometryRewriter.RewriteAnchorGeometry can tell "never touched"
        // apart from "genuinely resized" for a hidden-span text box too.
        textBox.SourceLoadedWidthPixels = textBox.Width;
        textBox.SourceLoadedHeightPixels = textBox.Height;
        // See the comment in ApplyToPicture: an absoluteAnchor's Anchor cell is the sheet origin
        // (pixel (0,0)), so the absolute pixel position doubles as the correct sub-cell offset.
        textBox.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        textBox.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    public static void ApplyToShape(
        DrawingShapeModel shape,
        XlsxDrawingAnchor? anchor,
        Sheet sheet,
        double? xfrmWidthPixels = null,
        double? xfrmHeightPixels = null)
    {
        if (anchor is null)
            return;

        // R127-editas-shift-gate: see the matching comment in ApplyToPicture.
        shape.DrawingAnchorKind = anchor.Kind;

        // Prefer the pre-rotation size from <a:xfrm><a:ext cx cy> when available.
        // For rotated shapes the outer anchor extent is the bounding box of the rotated shape,
        // not the shape's own unrotated dimensions, so we must use the xfrm extent instead.
        // For line-like shapes (Line, ElbowConnector, CurvedConnector), the xfrm cx/cy may be
        // zero along one axis (e.g. a perfectly horizontal line has cy=0); in that case we still
        // prefer the xfrm values so the shape renders as a flat line rather than a diagonal.
        double width, height;
        var isLineLike = DrawingShapeKindSupport.IsLineLike(shape.Kind);
        if (xfrmWidthPixels.HasValue && xfrmHeightPixels.HasValue &&
            (xfrmWidthPixels is > 0 || isLineLike) &&
            (xfrmHeightPixels is > 0 || isLineLike))
        {
            width = xfrmWidthPixels.Value;
            height = xfrmHeightPixels.Value;
        }
        else
        {
            (width, height) = GetAnchorSize(anchor, sheet);
        }

        if (width > 0)
            shape.Width = width;
        if (isLineLike)
        {
            shape.Height = Math.Max(0, height);   // allow flat (zero-height) lines
        }
        else if (height > 0)
        {
            shape.Height = height;
        }
        // R94-hidden-span fix: see the matching comment in ApplyToPicture -- always capture the baseline
        // as the POST-guard Width/Height (including the retained default when the anchor-derived span is
        // entirely hidden) rather than only when the computed value was positive, so the save-time
        // skip-gate in XlsxSourceDrawingGeometryRewriter.RewriteAnchorGeometry can tell "never touched"
        // apart from "genuinely resized" for a hidden-span shape too. This also covers the xfrm-preferred
        // branch above (xfrmWidthPixels/xfrmHeightPixels), which is unaffected since that width/height is
        // never zero-due-to-hidden-span in the first place -- the baseline still just mirrors whatever
        // Width/Height the shape ended up with.
        shape.SourceLoadedWidthPixels = shape.Width;
        shape.SourceLoadedHeightPixels = shape.Height;
        // See the comment in ApplyToPicture: an absoluteAnchor's Anchor cell is the sheet origin
        // (pixel (0,0)), so the absolute pixel position doubles as the correct sub-cell offset.
        shape.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        shape.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    /// <summary>
    /// Computes the effective rendered width/height (in DIP pixels) for a drawing anchor, preferring the
    /// anchor's own explicit extent (oneCellAnchor/absoluteAnchor <c>ext</c>, or precomputed EMU->pixel width/
    /// height) and otherwise deriving it from the twoCellAnchor's to/from cell span. Shared by both the
    /// load-time anchor applier and the patch-safe source-vs-current geometry comparison, so a resize is
    /// measured identically whichever path is exercised.
    /// </summary>
    internal static (double Width, double Height) GetAnchorSize(XlsxDrawingAnchor anchor, Sheet sheet)
    {
        var fromColumn = ClampColumn(anchor.FromColumnZeroBased);
        var fromRow = ClampRow(anchor.FromRowZeroBased);

        var width = anchor.Width ?? (
            SumColumnPixels(sheet, fromColumn + 1, ZeroBasedSpan(fromColumn, ClampColumn(anchor.ToColumnZeroBased!.Value)))
            + anchor.ToColumnOffset!.Value
            - anchor.FromColumnOffset);
        var height = anchor.Height ?? (
            SumRowPixels(sheet, fromRow + 1, ZeroBasedSpan(fromRow, ClampRow(anchor.ToRowZeroBased!.Value)))
            + anchor.ToRowOffset!.Value
            - anchor.FromRowOffset);
        return (width, height);
    }

    /// <summary>
    /// Number of whole rows/columns spanned from <paramref name="fromZeroBased"/> to
    /// <paramref name="toZeroBased"/>, clamped to zero when the 'to' marker does not come after the
    /// 'from' marker on this axis. A twoCellAnchor whose markers are inverted on only one axis (e.g. a
    /// hand-edited or non-Excel-authored file where <c>to/col</c> &lt; <c>from/col</c> but <c>to/row</c>
    /// &gt; <c>from/row</c>) is accepted by the reader's validity check, which only rejects an anchor
    /// invalid on BOTH axes at once. Without this clamp, the plain `to - from` subtraction on these
    /// unsigned coordinates underflows to a value near <see cref="uint.MaxValue"/>, and the SumColumnPixels/
    /// SumRowPixels loop below would then iterate on the order of 4 billion times -- hanging the app on
    /// what should be a fast file load -- instead of simply treating the malformed span as zero-width.
    /// </summary>
    private static uint ZeroBasedSpan(uint fromZeroBased, uint toZeroBased) =>
        toZeroBased > fromZeroBased ? toZeroBased - fromZeroBased : 0u;

    private static double SumColumnPixels(Sheet sheet, uint firstColumn, uint count)
    {
        double width = 0;
        for (var offset = 0u; offset < count; offset++)
        {
            var col = firstColumn + offset;
            if (!sheet.IsColEffectivelyHidden(col))
                width += sheet.ColumnWidths.GetValueOrDefault(col, sheet.DefaultColumnWidth) * 8;
        }

        return width;
    }

    private static double SumRowPixels(Sheet sheet, uint firstRow, uint count)
    {
        double height = 0;
        for (var offset = 0u; offset < count; offset++)
        {
            var row = firstRow + offset;
            if (!sheet.IsRowEffectivelyHidden(row))
                height += sheet.RowHeights.GetValueOrDefault(row, sheet.DefaultRowHeight);
        }

        return height;
    }
}
