using FreeX.Core.Model;

namespace FreeX.Core.IO;

/// <summary>
/// Backlog item "editAs-preserve" investigation note: <c>xdr:twoCellAnchor/@editAs</c>
/// (<c>twoCell</c>|<c>oneCell</c>|<c>absolute</c>) controls a drawing object's move/resize behavior when its
/// spanned rows/columns are resized. This applier deliberately does NOT read or model that attribute -- it
/// only derives a rendered pixel size/position from the anchor's cell span (<see cref="GetAnchorSize"/>) --
/// and it does not need to: for picture/shape/text-box objects loaded from a source .xlsx (the only case
/// where a real <c>twoCellAnchor</c> XML element exists; freshly-authored objects are always written as
/// <c>oneCellAnchor</c>, which has no <c>editAs</c> attribute in the schema), the ORIGINAL anchor element --
/// <c>editAs</c> included -- is preserved verbatim by <c>XlsxWorksheetDrawingPartMerger</c>/
/// <c>XlsxSourceDrawingGeometryRewriter</c> rather than being regenerated by this applier's caller, so a
/// save-then-reload already keeps <c>editAs</c> unchanged (see <c>Backlog_editAs_preserve_Tests</c> for the
/// round-trip proof). The one place <c>editAs</c> is genuinely dropped is chart anchors -- charts have no
/// verbatim-preservation path and <c>XlsxWorksheetChartWriter</c> always regenerates their anchor XML
/// without ever writing <c>editAs</c> -- but fixing that needs a new <see cref="ChartModel"/> field, which is
/// out of this file's edit scope. DEFERRED (see <c>Backlog_editAs_preserve_Tests</c>'s
/// <c>XlsxAdapter_ChartTwoCellAnchorEditAs_IsCurrentlyDroppedOnSave_DeferredGap</c> test for the pinned gap).
/// </summary>
internal static class XlsxDrawingAnchorApplier
{
    // Excel's real ceilings (1,048,576 rows x 16,384 columns), expressed zero-based to match the
    // reader's FromColumnZeroBased/ToColumnZeroBased/FromRowZeroBased/ToRowZeroBased fields. The writer
    // side already caps at these same 1-based limits (see XlsxSourceDrawingGeometryRewriter.MaxColumnIndex/
    // MaxRowIndex, XlsxWorksheetChartWriter.MaxColumnIndex/MaxRowIndex). A source file can contain a
    // schema-valid but absurd index (e.g. col 3,000,000,000) that is correctly ordered relative to its
    // partner marker; without clamping, SumColumnPixels/SumRowPixels below would loop billions of times
    // and hang the load. Clamping here matches Excel effectively ignoring/truncating such a value.
    private const uint MaxColumnIndexZeroBased = 16383;
    private const uint MaxRowIndexZeroBased = 1048575;

    private static uint ClampColumn(uint zeroBased) => Math.Min(zeroBased, MaxColumnIndexZeroBased);

    private static uint ClampRow(uint zeroBased) => Math.Min(zeroBased, MaxRowIndexZeroBased);

    public static void ApplyToChart(ChartModel chart, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        var fromColumn = ClampColumn(anchor.FromColumnZeroBased);
        var fromRow = ClampRow(anchor.FromRowZeroBased);

        chart.DrawingAnchorKind = anchor.Kind;
        chart.Left = anchor.AbsoluteLeft ?? (SumColumnPixels(sheet, 1, fromColumn) + anchor.FromColumnOffset);
        chart.Top = anchor.AbsoluteTop ?? (SumRowPixels(sheet, 1, fromRow) + anchor.FromRowOffset);

        var width = anchor.Width ?? (
            SumColumnPixels(sheet, fromColumn + 1, ZeroBasedSpan(fromColumn, ClampColumn(anchor.ToColumnZeroBased!.Value)))
            + anchor.ToColumnOffset!.Value
            - anchor.FromColumnOffset);
        var height = anchor.Height ?? (
            SumRowPixels(sheet, fromRow + 1, ZeroBasedSpan(fromRow, ClampRow(anchor.ToRowZeroBased!.Value)))
            + anchor.ToRowOffset!.Value
            - anchor.FromRowOffset);
        if (width > 0)
            chart.Width = width;
        if (height > 0)
            chart.Height = height;
    }

    public static void ApplyToPicture(PictureModel picture, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        var (width, height) = GetAnchorSize(anchor, sheet);
        if (width > 0)
            picture.Width = width;
        if (height > 0)
            picture.Height = height;
        // For an absoluteAnchor the caller resolves Anchor to the sheet's origin cell (row 1/col
        // 1, pixel (0,0)), so applying the anchor's absolute pixel position as the sub-cell offset
        // reproduces the intended on-sheet position, mirroring how ApplyToChart applies
        // AbsoluteLeft/AbsoluteTop directly (see lines 30-31 above).
        picture.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        picture.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    public static void ApplyToTextBox(TextBoxModel textBox, XlsxDrawingAnchor? anchor, Sheet sheet)
    {
        if (anchor is null)
            return;

        var (width, height) = GetAnchorSize(anchor, sheet);
        if (width > 0)
            textBox.Width = width;
        if (height > 0)
            textBox.Height = height;
        // See the comment in ApplyToPicture: an absoluteAnchor's Anchor cell is the sheet origin
        // (pixel (0,0)), so the absolute pixel position doubles as the correct sub-cell offset.
        textBox.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        textBox.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    public static void ApplyToShape(
        DrawingShapeModel shape,
        XlsxDrawingAnchor? anchor,
        Sheet sheet,
        double? xfrmWidthPixels = null,
        double? xfrmHeightPixels = null)
    {
        if (anchor is null)
            return;

        // Prefer the pre-rotation size from <a:xfrm><a:ext cx cy> when available.
        // For rotated shapes the outer anchor extent is the bounding box of the rotated shape,
        // not the shape's own unrotated dimensions, so we must use the xfrm extent instead.
        // For line-like shapes (Line, ElbowConnector, CurvedConnector), the xfrm cx/cy may be
        // zero along one axis (e.g. a perfectly horizontal line has cy=0); in that case we still
        // prefer the xfrm values so the shape renders as a flat line rather than a diagonal.
        double width, height;
        var isLineLike = DrawingShapeKindSupport.IsLineLike(shape.Kind);
        if (xfrmWidthPixels.HasValue && xfrmHeightPixels.HasValue &&
            (xfrmWidthPixels is > 0 || isLineLike) &&
            (xfrmHeightPixels is > 0 || isLineLike))
        {
            width = xfrmWidthPixels.Value;
            height = xfrmHeightPixels.Value;
        }
        else
        {
            (width, height) = GetAnchorSize(anchor, sheet);
        }

        if (width > 0)
            shape.Width = width;
        if (isLineLike)
            shape.Height = Math.Max(0, height);   // allow flat (zero-height) lines
        else if (height > 0)
            shape.Height = height;
        // See the comment in ApplyToPicture: an absoluteAnchor's Anchor cell is the sheet origin
        // (pixel (0,0)), so the absolute pixel position doubles as the correct sub-cell offset.
        shape.AnchorOffsetX = anchor.AbsoluteLeft ?? anchor.FromColumnOffset;
        shape.AnchorOffsetY = anchor.AbsoluteTop ?? anchor.FromRowOffset;
    }

    /// <summary>
    /// Computes the effective rendered width/height (in DIP pixels) for a drawing anchor, preferring the
    /// anchor's own explicit extent (oneCellAnchor/absoluteAnchor <c>ext</c>, or precomputed EMU->pixel width/
    /// height) and otherwise deriving it from the twoCellAnchor's to/from cell span. Shared by both the
    /// load-time anchor applier and the patch-safe source-vs-current geometry comparison, so a resize is
    /// measured identically whichever path is exercised.
    /// </summary>
    internal static (double Width, double Height) GetAnchorSize(XlsxDrawingAnchor anchor, Sheet sheet)
    {
        var fromColumn = ClampColumn(anchor.FromColumnZeroBased);
        var fromRow = ClampRow(anchor.FromRowZeroBased);

        var width = anchor.Width ?? (
            SumColumnPixels(sheet, fromColumn + 1, ZeroBasedSpan(fromColumn, ClampColumn(anchor.ToColumnZeroBased!.Value)))
            + anchor.ToColumnOffset!.Value
            - anchor.FromColumnOffset);
        var height = anchor.Height ?? (
            SumRowPixels(sheet, fromRow + 1, ZeroBasedSpan(fromRow, ClampRow(anchor.ToRowZeroBased!.Value)))
            + anchor.ToRowOffset!.Value
            - anchor.FromRowOffset);
        return (width, height);
    }

    /// <summary>
    /// Number of whole rows/columns spanned from <paramref name="fromZeroBased"/> to
    /// <paramref name="toZeroBased"/>, clamped to zero when the 'to' marker does not come after the
    /// 'from' marker on this axis. A twoCellAnchor whose markers are inverted on only one axis (e.g. a
    /// hand-edited or non-Excel-authored file where <c>to/col</c> &lt; <c>from/col</c> but <c>to/row</c>
    /// &gt; <c>from/row</c>) is accepted by the reader's validity check, which only rejects an anchor
    /// invalid on BOTH axes at once. Without this clamp, the plain `to - from` subtraction on these
    /// unsigned coordinates underflows to a value near <see cref="uint.MaxValue"/>, and the SumColumnPixels/
    /// SumRowPixels loop below would then iterate on the order of 4 billion times -- hanging the app on
    /// what should be a fast file load -- instead of simply treating the malformed span as zero-width.
    /// </summary>
    private static uint ZeroBasedSpan(uint fromZeroBased, uint toZeroBased) =>
        toZeroBased > fromZeroBased ? toZeroBased - fromZeroBased : 0u;

    private static double SumColumnPixels(Sheet sheet, uint firstColumn, uint count)
    {
        double width = 0;
        for (var offset = 0u; offset < count; offset++)
        {
            var col = firstColumn + offset;
            if (!sheet.IsColEffectivelyHidden(col))
                width += sheet.ColumnWidths.GetValueOrDefault(col, sheet.DefaultColumnWidth) * 8;
        }

        return width;
    }

    private static double SumRowPixels(Sheet sheet, uint firstRow, uint count)
    {
        double height = 0;
        for (var offset = 0u; offset < count; offset++)
        {
            var row = firstRow + offset;
            if (!sheet.IsRowEffectivelyHidden(row))
                height += sheet.RowHeights.GetValueOrDefault(row, sheet.DefaultRowHeight);
        }

        return height;
    }
}
