<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Free.Shared.Drawing\Free.Shared.Drawing.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Localization\Free.Shared.Localization.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Shell\Free.Shared.Shell.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Ribbon\Free.Shared.Ribbon.csproj" />
    <ProjectReference Include="..\FreeX.Ribbon.Definitions\FreeX.Ribbon.Definitions.csproj" />
    <ProjectReference Include="..\FreeX.Core.Model\FreeX.Core.Model.csproj" />
    <ProjectReference Include="..\FreeX.Core.IO\FreeX.Core.IO.csproj" />
    <ProjectReference Include="..\FreeX.Core.Calc\FreeX.Core.Calc.csproj" />
    <ProjectReference Include="..\FreeX.Core.Formula\FreeX.Core.Formula.csproj" />
    <ProjectReference Include="..\FreeX.Core.Commands\FreeX.Core.Commands.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Drawing" />
  </ItemGroup>

</Project>
