<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Free.Shared.Ribbon" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\CommandTestInfrastructure\TestCommandContext.cs" Link="TestCommandContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FreeX.App.Host\FreeX.App.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Opc" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Free.Shared.AppServices" />
  </ItemGroup>
</Project>
