using System.Windows.Input;
using FluentAssertions;
using FreeX.Core.Commands;

namespace FreeX.App.Host.Tests;

public sealed partial class KeyboardShortcutMatcherTests
{
    [Theory]
    [InlineData(Key.N, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.NewWorkbook)]
    [InlineData(Key.O, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenWorkbook)]
    [InlineData(Key.F12, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenWorkbook)]
    [InlineData(Key.S, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SaveWorkbook)]
    [InlineData(Key.F12, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.SaveWorkbook)]
    [InlineData(Key.C, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Copy)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Copy)]
    [InlineData(Key.X, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Cut)]
    [InlineData(Key.Delete, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.Cut)]
    [InlineData(Key.V, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Paste)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.Paste)]
    [InlineData(Key.A, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SelectCurrentRegionOrAll)]
    [InlineData(Key.Z, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Undo)]
    [InlineData(Key.Back, Key.None, ModifierKeys.Alt, KeyboardCommandShortcut.Undo)]
    [InlineData(Key.Y, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Redo)]
    [InlineData(Key.Z, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.Redo)]
    [InlineData(Key.T, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CreateTable)]
    [InlineData(Key.L, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CreateTable)]
    [InlineData(Key.K, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.InsertHyperlink)]
    [InlineData(Key.Enter, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenHyperlink)]
    [InlineData(Key.D, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.FillDown)]
    [InlineData(Key.R, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.FillRight)]
    [InlineData(Key.E, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.FlashFill)]
    [InlineData(Key.OemSemicolon, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.InsertCurrentDate)]
    [InlineData(Key.OemSemicolon, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.InsertCurrentTime)]
    [InlineData(Key.Oem3, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.ToggleShowFormulas)]
    [InlineData(Key.D8, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.ToggleOutlineSymbols)]
    [InlineData(Key.PageUp, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.ActivatePreviousSheet)]
    [InlineData(Key.PageDown, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.ActivateNextSheet)]
    [InlineData(Key.PageUp, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SelectPreviousSheetGroup)]
    [InlineData(Key.PageDown, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SelectNextSheetGroup)]
    [InlineData(Key.D1, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenFormatCells)]
    [InlineData(Key.NumPad1, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenFormatCells)]
    [InlineData(Key.F, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Find)]
    [InlineData(Key.H, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.Replace)]
    [InlineData(Key.F3, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.NameManager)]
    [InlineData(Key.F3, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.CreateNamesFromSelection)]
    [InlineData(Key.F3, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.InsertFunction)]
    [InlineData(Key.F3, Key.None, ModifierKeys.None, KeyboardCommandShortcut.PasteName)]
    [InlineData(Key.F7, Key.None, ModifierKeys.None, KeyboardCommandShortcut.SpellCheck)]
    [InlineData(Key.F4, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CloseWorkbook)]
    [InlineData(Key.W, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CloseWorkbook)]
    [InlineData(Key.F5, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.RestoreWorkbookWindow)]
    [InlineData(Key.F7, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.MoveWorkbookWindow)]
    [InlineData(Key.F8, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SizeWorkbookWindow)]
    [InlineData(Key.F9, Key.None, ModifierKeys.None, KeyboardCommandShortcut.CalculateNow)]
    [InlineData(Key.F9, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.CalculateSheet)]
    [InlineData(Key.F9, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.CalculateFull)]
    [InlineData(Key.F9, Key.None, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.RebuildDependenciesAndCalculate)]
    [InlineData(Key.None, Key.F10, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.OpenErrorChecking)]
    [InlineData(Key.U, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.ToggleFormulaBarExpansion)]
    [InlineData(Key.Q, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.QuickAnalysis)]
    [InlineData(Key.P, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.OpenPrintPreview)]
    [InlineData(Key.F12, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.OpenPrintPreview)]
    [InlineData(Key.V, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.PasteValues)]
    [InlineData(Key.L, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.ToggleFilter)]
    [InlineData(Key.L, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ReapplyFilter)]
    [InlineData(Key.F5, Key.None, ModifierKeys.None, KeyboardCommandShortcut.GoTo)]
    [InlineData(Key.G, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.GoTo)]
    [InlineData(Key.None, Key.F1, ModifierKeys.Alt, KeyboardCommandShortcut.InsertEmbeddedChart)]
    [InlineData(Key.F11, Key.None, ModifierKeys.None, KeyboardCommandShortcut.InsertChartSheet)]
    [InlineData(Key.None, Key.OemPlus, ModifierKeys.Alt, KeyboardCommandShortcut.AutoSum)]
    [InlineData(Key.None, Key.Add, ModifierKeys.Alt, KeyboardCommandShortcut.AutoSum)]
    [InlineData(Key.None, Key.Right, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.GroupSelection)]
    [InlineData(Key.None, Key.Left, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.UngroupSelection)]
    [InlineData(Key.F, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.OpenFormatCellsFont)]
    [InlineData(Key.P, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.OpenFormatCellsFont)]
    [InlineData(Key.G, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.WorkbookStatistics)]
    [InlineData(Key.F2, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.NewNote)]
    [InlineData(Key.F2, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.NewThreadedComment)]
    [InlineData(Key.F12, Key.None, ModifierKeys.None, KeyboardCommandShortcut.SaveAs)]
    [InlineData(Key.F1, Key.None, ModifierKeys.None, KeyboardCommandShortcut.OpenHelp)]
    [InlineData(Key.F10, Key.None, ModifierKeys.None, KeyboardCommandShortcut.ShowKeyTips)]
    [InlineData(Key.F6, Key.None, ModifierKeys.None, KeyboardCommandShortcut.CycleShellFocus)]
    [InlineData(Key.F6, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.CycleShellFocus)]
    [InlineData(Key.F6, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SwitchToNextWorkbookWindow)]
    [InlineData(Key.Tab, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SwitchToNextWorkbookWindow)]
    [InlineData(Key.F6, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SwitchToPreviousWorkbookWindow)]
    [InlineData(Key.Tab, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SwitchToPreviousWorkbookWindow)]
    [InlineData(Key.F9, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.MinimizeWorkbookWindow)]
    [InlineData(Key.F10, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.MaximizeOrRestoreWorkbookWindow)]
    [InlineData(Key.F10, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.OpenContextMenu)]
    [InlineData(Key.Apps, Key.None, ModifierKeys.None, KeyboardCommandShortcut.OpenContextMenu)]
    [InlineData(Key.F2, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.EditInFormulaBar)]
    [InlineData(Key.F11, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.InsertWorksheet)]
    [InlineData(Key.None, Key.F1, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.InsertWorksheet)]
    [InlineData(Key.OemPlus, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomIn)]
    [InlineData(Key.Add, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomIn)]
    [InlineData(Key.OemMinus, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomOut)]
    [InlineData(Key.Subtract, Key.None, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomOut)]
    [InlineData(Key.OemQuotes, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CopyFormulaFromAbove)]
    [InlineData(Key.OemQuotes, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.CopyValueFromAbove)]
    [InlineData(Key.None, Key.Down, ModifierKeys.Alt, KeyboardCommandShortcut.OpenActiveDropdown)]
    [InlineData(Key.Back, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.ScrollActiveCellIntoView)]
    [InlineData(Key.OemPeriod, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CycleSelectionCorner)]
    [InlineData(Key.Decimal, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.CycleSelectionCorner)]
    [InlineData(Key.OemOpenBrackets, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SelectDirectPrecedents)]
    [InlineData(Key.OemCloseBrackets, Key.None, ModifierKeys.Control, KeyboardCommandShortcut.SelectDirectDependents)]
    [InlineData(Key.OemOpenBrackets, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SelectAllPrecedents)]
    [InlineData(Key.OemCloseBrackets, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SelectAllDependents)]
    [InlineData(Key.O, Key.None, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SelectCellsWithComments)]
    [InlineData(Key.None, Key.Oem1, ModifierKeys.Alt, KeyboardCommandShortcut.SelectVisibleCellsOnly)]
    [InlineData(Key.F2, Key.None, ModifierKeys.None, KeyboardCommandShortcut.EditCell)]
    [InlineData(Key.Delete, Key.None, ModifierKeys.None, KeyboardCommandShortcut.ClearSelection)]
    [InlineData(Key.Back, Key.None, ModifierKeys.None, KeyboardCommandShortcut.ClearSelectionAndEdit)]
    [InlineData(Key.Back, Key.None, ModifierKeys.Shift, KeyboardCommandShortcut.ClearSelectionAndEdit)]
    [InlineData(Key.F4, Key.None, ModifierKeys.None, KeyboardCommandShortcut.RepeatLastAction)]
    public void TryGetCommandShortcut_MapsCommonExcelShortcuts(
        Key key,
        Key systemKey,
        ModifierKeys modifiers,
        KeyboardCommandShortcut expected)
    {
        var result = KeyboardShortcutMatcher.TryGetCommandShortcut(key, systemKey, modifiers, out var shortcut);

        result.Should().BeTrue();
        shortcut.Should().Be(expected);
    }

    [Theory]
    [InlineData(Key.System, Key.Back, ModifierKeys.Alt, KeyboardCommandShortcut.Undo)]
    [InlineData(Key.System, Key.F12, ModifierKeys.Control, KeyboardCommandShortcut.OpenWorkbook)]
    [InlineData(Key.System, Key.F12, ModifierKeys.Shift, KeyboardCommandShortcut.SaveWorkbook)]
    [InlineData(Key.System, Key.F12, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.OpenPrintPreview)]
    [InlineData(Key.System, Key.F1, ModifierKeys.Alt, KeyboardCommandShortcut.InsertEmbeddedChart)]
    [InlineData(Key.System, Key.F1, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.InsertWorksheet)]
    [InlineData(Key.System, Key.OemPlus, ModifierKeys.Alt, KeyboardCommandShortcut.AutoSum)]
    [InlineData(Key.System, Key.Add, ModifierKeys.Alt, KeyboardCommandShortcut.AutoSum)]
    [InlineData(Key.System, Key.Down, ModifierKeys.Alt, KeyboardCommandShortcut.OpenActiveDropdown)]
    [InlineData(Key.System, Key.Right, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.GroupSelection)]
    [InlineData(Key.System, Key.Left, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.UngroupSelection)]
    [InlineData(Key.System, Key.Oem1, ModifierKeys.Alt, KeyboardCommandShortcut.SelectVisibleCellsOnly)]
    [InlineData(Key.System, Key.F9, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.CalculateFull)]
    [InlineData(Key.System, Key.F9, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.RebuildDependenciesAndCalculate)]
    [InlineData(Key.System, Key.F10, ModifierKeys.Alt | ModifierKeys.Shift, KeyboardCommandShortcut.OpenErrorChecking)]
    [InlineData(Key.System, Key.L, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ReapplyFilter)]
    [InlineData(Key.System, Key.OemPlus, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomIn)]
    [InlineData(Key.System, Key.Add, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomIn)]
    [InlineData(Key.System, Key.OemMinus, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomOut)]
    [InlineData(Key.System, Key.Subtract, ModifierKeys.Control | ModifierKeys.Alt, KeyboardCommandShortcut.ZoomOut)]
    [InlineData(Key.System, Key.F6, ModifierKeys.Control, KeyboardCommandShortcut.SwitchToNextWorkbookWindow)]
    [InlineData(Key.System, Key.F6, ModifierKeys.Control | ModifierKeys.Shift, KeyboardCommandShortcut.SwitchToPreviousWorkbookWindow)]
    public void TryGetCommandShortcut_MapsSystemKeyCommandShortcuts(
        Key key,
        Key systemKey,
        ModifierKeys modifiers,
        KeyboardCommandShortcut expected)
    {
        var result = KeyboardShortcutMatcher.TryGetCommandShortcut(key, systemKey, modifiers, out var shortcut);

        result.Should().BeTrue();
        shortcut.Should().Be(expected);
    }

    [Theory]
    [InlineData(Key.F4, ModifierKeys.Alt)]
    [InlineData(Key.F4, ModifierKeys.Shift)]
    [InlineData(Key.F5, ModifierKeys.Shift)]
    [InlineData(Key.F5, ModifierKeys.Alt)]
    [InlineData(Key.F7, ModifierKeys.Shift)]
    [InlineData(Key.F7, ModifierKeys.Alt)]
    [InlineData(Key.F11, ModifierKeys.Control)]
    [InlineData(Key.F11, ModifierKeys.Alt)]
    [InlineData(Key.F12, ModifierKeys.Alt)]
    public void TryGetCommandShortcut_PlainFunctionKeyCommandsRequireExactModifiers(Key key, ModifierKeys modifiers)
    {
        var result = KeyboardShortcutMatcher.TryGetCommandShortcut(key, Key.None, modifiers, out _);

        result.Should().BeFalse();
    }

    [Theory]
    [InlineData(Key.C, Key.None, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.C, Key.None, ModifierKeys.Control | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.C, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.X, Key.None, ModifierKeys.Control | ModifierKeys.Shift)]
    [InlineData(Key.X, Key.None, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.X, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.A, Key.None, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.A, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.N, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.O, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.S, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.T, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.K, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.D, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.R, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.E, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.PageUp, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.PageDown, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.D8, Key.None, ModifierKeys.Control | ModifierKeys.Shift)]
    [InlineData(Key.Y, Key.None, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Y, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Oem3, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemSemicolon, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemQuotes, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemOpenBrackets, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemCloseBrackets, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.P, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.L, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.V, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemSemicolon, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemQuotes, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemOpenBrackets, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.OemCloseBrackets, ModifierKeys.Control | ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F1, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F2, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F3, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F4, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F4, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F6, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F6, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.F6, Key.None, ModifierKeys.Alt)]
    [InlineData(Key.F6, Key.None, ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.F9, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F10, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F11, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F11, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F12, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.F12, ModifierKeys.Shift | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Apps, ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Back, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Back, ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.Back, Key.None, ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.Down, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.System, Key.Down, ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.Right, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.Left, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.System, Key.Oem1, ModifierKeys.Alt | ModifierKeys.Shift)]
    [InlineData(Key.F10, Key.None, ModifierKeys.Control | ModifierKeys.Shift)]
    [InlineData(Key.Apps, Key.None, ModifierKeys.Shift)]
    [InlineData(Key.Apps, Key.None, ModifierKeys.Control)]
    [InlineData(Key.Apps, Key.None, ModifierKeys.Alt)]
    public void TryGetCommandShortcut_DoesNotStealExtraModifierCombinations(Key key, Key systemKey, ModifierKeys modifiers)
    {
        var result = KeyboardShortcutMatcher.TryGetCommandShortcut(key, systemKey, modifiers, out _);

        result.Should().BeFalse();
    }

    [Theory]
    [InlineData(Key.L, Key.None, ModifierKeys.None)]
    [InlineData(Key.W, Key.None, ModifierKeys.None)]
    [InlineData(Key.NumPad1, Key.None, ModifierKeys.None)]
    [InlineData(Key.Add, Key.None, ModifierKeys.None)]
    [InlineData(Key.Add, Key.None, ModifierKeys.Control)]
    [InlineData(Key.P, Key.None, ModifierKeys.None)]
    [InlineData(Key.Subtract, Key.None, ModifierKeys.None)]
    [InlineData(Key.Subtract, Key.None, ModifierKeys.Control)]
    [InlineData(Key.Decimal, Key.None, ModifierKeys.None)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.None)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.Control | ModifierKeys.Shift)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.Control | ModifierKeys.Alt)]
    [InlineData(Key.Insert, Key.None, ModifierKeys.Shift | ModifierKeys.Alt)]
    public void TryGetCommandShortcut_AliasKeysRequireExactModifiers(Key key, Key systemKey, ModifierKeys modifiers)
    {
        var result = KeyboardShortcutMatcher.TryGetCommandShortcut(key, systemKey, modifiers, out _);

        result.Should().BeFalse();
    }
}
