using Free.Shared.Ribbon;

namespace FreeW.App.Presentation.Ribbon;

public enum FreeWRibbonCommandAction
{
    About,
    AcceptThis,
    AddToDictionary,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Allcaps,
    Bibliography,
    BlankPage,
    Bold,
    Bookmark,
    BookmarkManager,
    BordersShading,
    BuildingBlocksOrganizer,
    Bullets,
    Caption,
    CcCheckbox,
    CcCombo,
    CcDate,
    CcDropdown,
    CcRichtext,
    CcText,
    CellAlignBottomCenter,
    CellAlignBottomLeft,
    CellAlignBottomRight,
    CellAlignMiddleCenter,
    CellAlignMiddleLeft,
    CellAlignMiddleRight,
    CellAlignTopCenter,
    CellAlignTopLeft,
    CellAlignTopRight,
    CellTextDirectionHorizontal,
    CellTextDirectionRotate270,
    CellTextDirectionRotate90,
    ChangeCase,
    CharBorder,
    CharShading,
    Chart,
    ChartAxisTitles,
    ChartEditData,
    ChartSize,
    ChartSizeDialog,
    ChartTitle,
    ChartToggleLegend,
    CheckAccessibility,
    CheckUpdates,
    Citation,
    CitationStyle,
    ClearFormatting,
    ColumnBreak,
    Columns,
    ColumnsLeft,
    ColumnsMore,
    ColumnsOne,
    ColumnsRight,
    ColumnsThree,
    ColumnsTwo,
    Combine,
    Compare,
    Copy,
    CopyDiagnostics,
    CoverPage,
    CrossReference,
    CustomizeColors,
    CustomizeFonts,
    CustomMargins,
    CustomParagraphSpacing,
    Cut,
    Datetime,
    DeleteComment,
    DifferentFirstPage,
    DrawTable,
    DropCap,
    DropCap_Dropped,
    DropCap_InMargin,
    DropCap_None,
    DropCapDropped,
    DropCapInMargin,
    DropCapNone,
    DropCapOptions,
    EditHyperlink,
    Endnote,
    Equation,
    Eraser,
    Feedback,
    Field,
    Find,
    FontColor,
    FontDialog,
    FontFamily,
    FontSize,
    Footer,
    Footnote,
    FootnoteEndnoteOptions,
    FormatPainter,
    FormattingMarks,
    GrowFont,
    Header,
    HelpOnline,
    HfClose,
    HfDifferentFirstPage,
    HfDifferentOddEven,
    HfEditEvenFooter,
    HfEditEvenHeader,
    HfEditFirstFooter,
    HfEditFirstHeader,
    HfEditFooter,
    HfEditHeader,
    HfFooterFromBottom,
    HfGoToFooter,
    HfGoToHeader,
    HfHeaderFromTop,
    HfInsertDatetime,
    HfInsertField,
    HfInsertPageNumber,
    HfInsertPageNumberFooter,
    Highlight,
    HorizontalRule,
    Hyperlink,
    HyperlinkTooltip,
    Hyphenation,
    HyphenationAuto,
    HyphenationManual,
    HyphenationNone,
    HyphenationOptions,
    ImageAdjustDialog,
    ImageAlignCenter,
    ImageAlignLeft,
    ImageAlignRight,
    ImageAlignToMargin,
    ImageAlignToPage,
    ImageAltText,
    ImageBevelNone,
    ImageBorder,
    ImageBrightnessMinus20,
    ImageBrightnessMinus40,
    ImageBrightnessPlus20,
    ImageBrightnessPlus40,
    ImageColorDialog,
    ImageColortempCool,
    ImageColortempNeutral,
    ImageColortempWarm,
    ImageContrastMinus20,
    ImageContrastPlus20,
    ImageCrop,
    ImageDistributeH,
    ImageDistributeV,
    ImageRecolorBlackwhite,
    ImageRecolorGrayscale,
    ImageRecolorNone,
    ImageRecolorSepia,
    ImageRecolorWashout,
    ImageReflectionNone,
    ImageReset,
    ImageSaturation0,
    ImageSaturation200,
    ImageSaturation50,
    ImageShadowNone,
    ImageSize,
    ImageTransparency25,
    ImageTransparency50,
    ImageTransparency75,
    ImageTransparencyDialog,
    IndentDecrease,
    IndentIncrease,
    IndentLeft,
    IndentRight,
    IndexInsert,
    IndexMark,
    IndexRefresh,
    InsertCaption_Equation,
    InsertCaption_Figure,
    InsertCaption_Table,
    InsertFile,
    InsertIcon,
    InspectDocument,
    Italic,
    KeepLines,
    KeepWithNext,
    LegalNotices,
    LineNumbers,
    LineNumbersContinuous,
    LineNumbersNone,
    LineNumbersOptions,
    LineNumbersRestartPage,
    LineNumbersRestartSection,
    LineSpacing,
    LinkBookmark,
    ManageSources,
    ManageStyles,
    Margins,
    MarkAsFinal,
    MarkCitation,
    MergeAddressBlock,
    MergeCheckErrors,
    MergeData,
    MergeEditRecipients,
    MergeEmail,
    MergeEnvelopes,
    MergeField,
    MergeFilterSort,
    MergeFindRecipient,
    MergeFinish,
    MergeGreetingLine,
    MergeLabels,
    MergeMatchFields,
    MergeNextRecord,
    MergePreview,
    MergePreviewFirst,
    MergePreviewLast,
    MergePreviewNext,
    MergePreviewPrevious,
    MergeRecordNumber,
    MergeRuleAsk,
    MergeRuleFillIn,
    MergeRuleIf,
    MergeRuleNextRecordIf,
    MergeRuleRef,
    MergeRules,
    MergeRuleSet,
    MergeRuleSkipRecordIf,
    MergeSequenceNumber,
    MorePaperSizes,
    MultilevelDefine,
    MultilevelDemote,
    MultilevelList,
    MultilevelPromote,
    NewComment,
    NewStyle,
    NextChange,
    NextComment,
    NextEndnote,
    NextFootnote,
    Numbering,
    Object,
    ObjectGroup,
    ObjectUngroup,
    Orientation,
    PageBreak,
    PageColor,
    PageNumber,
    PageNumberBottom,
    PageNumberCurrent,
    PageNumberFormat,
    PageNumberTop,
    PageSetup,
    PageValign,
    ParaBorder,
    ParagraphDialog,
    ParaShading,
    Paste,
    PasteMerge,
    PastePlain,
    PasteSpecial,
    Picture,
    PreviousChange,
    PreviousComment,
    PreviousEndnote,
    PreviousFootnote,
    ReadAloud,
    Redo,
    RejectThis,
    RemoveHyperlink,
    Replace,
    ReplyComment,
    ResetStyleSet,
    ResolveComment,
    RestrictEditing,
    ReviewingPane,
    SaveQuickpart,
    ScreenClipping,
    SectionBreakContinuous,
    SectionBreakEvenPage,
    SectionBreakNextPage,
    SectionBreakOddPage,
    Select,
    SetProofingLanguage,
    ShapeAlignCenter,
    ShapeAlignLeft,
    ShapeAlignRight,
    ShapeAlignToMargin,
    ShapeAlignToPage,
    ShapeAltText,
    ShapeChangeEllipse,
    ShapeChangeRectangle,
    ShapeChangeRounded,
    ShapeConvertFreeform,
    ShapeDistributeH,
    ShapeDistributeV,
    ShapeEditPoints,
    ShapeEditShape,
    ShapeEffectBevel,
    ShapeEffectGlow,
    ShapeEffectReflection,
    ShapeEffects,
    ShapeEffectShadow,
    ShapeEffectsNone,
    ShapeEffectSoftEdge,
    ShapeSize,
    ShapeStylesGallery,
    ShapeTextDirection,
    ShapeTextHorizontal,
    ShapeTextRotate270,
    ShapeTextRotate90,
    ShowComments,
    ShowMarkupBalloons,
    ShowNotes,
    ShrinkFont,
    Size,
    Smallcaps,
    Smartart,
    SmartartAddShape,
    SmartartChangeStyle,
    SmartartDemote,
    SmartartEditText,
    SmartartMoveDown,
    SmartartMoveUp,
    SmartartPromote,
    SmartartRemoveShape,
    Sort,
    SpaceAfter,
    SpaceAfterToggle,
    SpaceBefore,
    SpaceBeforeToggle,
    SpellcheckToggle,
    SplitTable,
    StartMailMerge,
    StartMailMergeDirectory,
    StartMailMergeLetters,
    StartMailMergeNormal,
    Statistics,
    Strikethrough,
    Style,
    StyleClear,
    StyleHeading1,
    StyleHeading2,
    StyleHeading3,
    StyleNormal,
    StyleSet,
    StyleTitle,
    Subscript,
    Superscript,
    Symbol,
    Table,
    TableAutofitContents,
    TableAutofitFixed,
    TableAutofitWindow,
    TableBandedCols,
    TableBandedRows,
    TableCellMargins,
    TableColWidth,
    TableDelete,
    TableDeleteCol,
    TableDeleteRow,
    TableDistributeCols,
    TableDistributeRows,
    TableFirstColumn,
    TableFormula,
    TableHeaderRow,
    TableInsertAbove,
    TableInsertColLeft,
    TableLastColumn,
    TableLastRow,
    TableOfAuthorities,
    TableOfAuthoritiesRefresh,
    TableProperties,
    TableRepeatHeader,
    TableRowHeight,
    TableSelectCell,
    TableSelectCol,
    TableSelectRow,
    TableSelectTable,
    TableToText,
    TableViewGridlines,
    TabsDialog,
    TextToTable,
    Theme,
    ThemeColors,
    ThemeEffects,
    ThemeFonts,
    Thesaurus,
    Toc,
    TocRefresh,
    Tof,
    Tof_Equation,
    Tof_Figure,
    Tof_Table,
    TofRefresh,
    TofRefresh_Equation,
    TofRefresh_Figure,
    TofRefresh_Table,
    ToggleFieldCodes,
    Underline,
    Undo,
    UpdateFields,
    Watermark,
    WidowControl,
    Wordart,
}

public sealed record FreeWRibbonCommandRoute(
    string CommandId,
    FreeWRibbonCommandAction Action);

/// <summary>
/// Owns the portable mapping from FreeW ribbon ids to application actions. Renderers bind each
/// action to native editor, dialog, clipboard, file, focus, or window callbacks.
/// </summary>
public static class FreeWRibbonCommandWorkflow
{
    private static readonly FreeWRibbonCommandRoute[] RouteData =
    [
        new("freew.about", FreeWRibbonCommandAction.About),
        new("freew.accept-this", FreeWRibbonCommandAction.AcceptThis),
        new("freew.add-to-dictionary", FreeWRibbonCommandAction.AddToDictionary),
        new("freew.align-center", FreeWRibbonCommandAction.AlignCenter),
        new("freew.align-justify", FreeWRibbonCommandAction.AlignJustify),
        new("freew.align-left", FreeWRibbonCommandAction.AlignLeft),
        new("freew.align-right", FreeWRibbonCommandAction.AlignRight),
        new("freew.allcaps", FreeWRibbonCommandAction.Allcaps),
        new("freew.bibliography", FreeWRibbonCommandAction.Bibliography),
        new("freew.blank-page", FreeWRibbonCommandAction.BlankPage),
        new("freew.bold", FreeWRibbonCommandAction.Bold),
        new("freew.bookmark", FreeWRibbonCommandAction.Bookmark),
        new("freew.bookmark-manager", FreeWRibbonCommandAction.BookmarkManager),
        new("freew.borders-shading", FreeWRibbonCommandAction.BordersShading),
        new("freew.building-blocks-organizer", FreeWRibbonCommandAction.BuildingBlocksOrganizer),
        new("freew.bullets", FreeWRibbonCommandAction.Bullets),
        new("freew.caption", FreeWRibbonCommandAction.Caption),
        new("freew.cc-checkbox", FreeWRibbonCommandAction.CcCheckbox),
        new("freew.cc-combo", FreeWRibbonCommandAction.CcCombo),
        new("freew.cc-date", FreeWRibbonCommandAction.CcDate),
        new("freew.cc-dropdown", FreeWRibbonCommandAction.CcDropdown),
        new("freew.cc-richtext", FreeWRibbonCommandAction.CcRichtext),
        new("freew.cc-text", FreeWRibbonCommandAction.CcText),
        new("freew.cell-align-bottom-center", FreeWRibbonCommandAction.CellAlignBottomCenter),
        new("freew.cell-align-bottom-left", FreeWRibbonCommandAction.CellAlignBottomLeft),
        new("freew.cell-align-bottom-right", FreeWRibbonCommandAction.CellAlignBottomRight),
        new("freew.cell-align-middle-center", FreeWRibbonCommandAction.CellAlignMiddleCenter),
        new("freew.cell-align-middle-left", FreeWRibbonCommandAction.CellAlignMiddleLeft),
        new("freew.cell-align-middle-right", FreeWRibbonCommandAction.CellAlignMiddleRight),
        new("freew.cell-align-top-center", FreeWRibbonCommandAction.CellAlignTopCenter),
        new("freew.cell-align-top-left", FreeWRibbonCommandAction.CellAlignTopLeft),
        new("freew.cell-align-top-right", FreeWRibbonCommandAction.CellAlignTopRight),
        new("freew.cell-text-direction-horizontal", FreeWRibbonCommandAction.CellTextDirectionHorizontal),
        new("freew.cell-text-direction-rotate270", FreeWRibbonCommandAction.CellTextDirectionRotate270),
        new("freew.cell-text-direction-rotate90", FreeWRibbonCommandAction.CellTextDirectionRotate90),
        new("freew.change-case", FreeWRibbonCommandAction.ChangeCase),
        new("freew.char-border", FreeWRibbonCommandAction.CharBorder),
        new("freew.char-shading", FreeWRibbonCommandAction.CharShading),
        new("freew.chart", FreeWRibbonCommandAction.Chart),
        new("freew.chart-axis-titles", FreeWRibbonCommandAction.ChartAxisTitles),
        new("freew.chart-edit-data", FreeWRibbonCommandAction.ChartEditData),
        new("freew.chart-size", FreeWRibbonCommandAction.ChartSize),
        new("freew.chart-size-dialog", FreeWRibbonCommandAction.ChartSizeDialog),
        new("freew.chart-title", FreeWRibbonCommandAction.ChartTitle),
        new("freew.chart-toggle-legend", FreeWRibbonCommandAction.ChartToggleLegend),
        new("freew.check-accessibility", FreeWRibbonCommandAction.CheckAccessibility),
        new("freew.check-updates", FreeWRibbonCommandAction.CheckUpdates),
        new("freew.citation", FreeWRibbonCommandAction.Citation),
        new("freew.citation-style", FreeWRibbonCommandAction.CitationStyle),
        new("freew.clear-formatting", FreeWRibbonCommandAction.ClearFormatting),
        new("freew.column-break", FreeWRibbonCommandAction.ColumnBreak),
        new("freew.columns", FreeWRibbonCommandAction.Columns),
        new("freew.columns-left", FreeWRibbonCommandAction.ColumnsLeft),
        new("freew.columns-more", FreeWRibbonCommandAction.ColumnsMore),
        new("freew.columns-one", FreeWRibbonCommandAction.ColumnsOne),
        new("freew.columns-right", FreeWRibbonCommandAction.ColumnsRight),
        new("freew.columns-three", FreeWRibbonCommandAction.ColumnsThree),
        new("freew.columns-two", FreeWRibbonCommandAction.ColumnsTwo),
        new("freew.combine", FreeWRibbonCommandAction.Combine),
        new("freew.compare", FreeWRibbonCommandAction.Compare),
        new("freew.copy", FreeWRibbonCommandAction.Copy),
        new("freew.copy-diagnostics", FreeWRibbonCommandAction.CopyDiagnostics),
        new("freew.cover-page", FreeWRibbonCommandAction.CoverPage),
        new("freew.cross-reference", FreeWRibbonCommandAction.CrossReference),
        new("freew.customize-colors", FreeWRibbonCommandAction.CustomizeColors),
        new("freew.customize-fonts", FreeWRibbonCommandAction.CustomizeFonts),
        new("freew.custom-margins", FreeWRibbonCommandAction.CustomMargins),
        new("freew.custom-paragraph-spacing", FreeWRibbonCommandAction.CustomParagraphSpacing),
        new("freew.cut", FreeWRibbonCommandAction.Cut),
        new("freew.datetime", FreeWRibbonCommandAction.Datetime),
        new("freew.delete-comment", FreeWRibbonCommandAction.DeleteComment),
        new("freew.different-first-page", FreeWRibbonCommandAction.DifferentFirstPage),
        new("freew.draw-table", FreeWRibbonCommandAction.DrawTable),
        new("freew.drop-cap", FreeWRibbonCommandAction.DropCap),
        new("freew.drop-cap.dropped", FreeWRibbonCommandAction.DropCap_Dropped),
        new("freew.drop-cap.in-margin", FreeWRibbonCommandAction.DropCap_InMargin),
        new("freew.drop-cap.none", FreeWRibbonCommandAction.DropCap_None),
        new("freew.drop-cap-dropped", FreeWRibbonCommandAction.DropCapDropped),
        new("freew.drop-cap-in-margin", FreeWRibbonCommandAction.DropCapInMargin),
        new("freew.drop-cap-none", FreeWRibbonCommandAction.DropCapNone),
        new("freew.drop-cap-options", FreeWRibbonCommandAction.DropCapOptions),
        new("freew.edit-hyperlink", FreeWRibbonCommandAction.EditHyperlink),
        new("freew.endnote", FreeWRibbonCommandAction.Endnote),
        new("freew.equation", FreeWRibbonCommandAction.Equation),
        new("freew.eraser", FreeWRibbonCommandAction.Eraser),
        new("freew.feedback", FreeWRibbonCommandAction.Feedback),
        new("freew.field", FreeWRibbonCommandAction.Field),
        new("freew.find", FreeWRibbonCommandAction.Find),
        new("freew.font-color", FreeWRibbonCommandAction.FontColor),
        new("freew.font-dialog", FreeWRibbonCommandAction.FontDialog),
        new("freew.font-family", FreeWRibbonCommandAction.FontFamily),
        new("freew.font-size", FreeWRibbonCommandAction.FontSize),
        new("freew.footer", FreeWRibbonCommandAction.Footer),
        new("freew.footnote", FreeWRibbonCommandAction.Footnote),
        new("freew.footnote-endnote-options", FreeWRibbonCommandAction.FootnoteEndnoteOptions),
        new("freew.format-painter", FreeWRibbonCommandAction.FormatPainter),
        new("freew.formatting-marks", FreeWRibbonCommandAction.FormattingMarks),
        new("freew.grow-font", FreeWRibbonCommandAction.GrowFont),
        new("freew.header", FreeWRibbonCommandAction.Header),
        new("freew.help-online", FreeWRibbonCommandAction.HelpOnline),
        new("freew.hf-close", FreeWRibbonCommandAction.HfClose),
        new("freew.hf-different-first-page", FreeWRibbonCommandAction.HfDifferentFirstPage),
        new("freew.hf-different-odd-even", FreeWRibbonCommandAction.HfDifferentOddEven),
        new("freew.hf-edit-even-footer", FreeWRibbonCommandAction.HfEditEvenFooter),
        new("freew.hf-edit-even-header", FreeWRibbonCommandAction.HfEditEvenHeader),
        new("freew.hf-edit-first-footer", FreeWRibbonCommandAction.HfEditFirstFooter),
        new("freew.hf-edit-first-header", FreeWRibbonCommandAction.HfEditFirstHeader),
        new("freew.hf-edit-footer", FreeWRibbonCommandAction.HfEditFooter),
        new("freew.hf-edit-header", FreeWRibbonCommandAction.HfEditHeader),
        new("freew.hf-footer-from-bottom", FreeWRibbonCommandAction.HfFooterFromBottom),
        new("freew.hf-go-to-footer", FreeWRibbonCommandAction.HfGoToFooter),
        new("freew.hf-go-to-header", FreeWRibbonCommandAction.HfGoToHeader),
        new("freew.hf-header-from-top", FreeWRibbonCommandAction.HfHeaderFromTop),
        new("freew.hf-insert-datetime", FreeWRibbonCommandAction.HfInsertDatetime),
        new("freew.hf-insert-field", FreeWRibbonCommandAction.HfInsertField),
        new("freew.hf-insert-page-number", FreeWRibbonCommandAction.HfInsertPageNumber),
        new("freew.hf-insert-page-number-footer", FreeWRibbonCommandAction.HfInsertPageNumberFooter),
        new("freew.highlight", FreeWRibbonCommandAction.Highlight),
        new("freew.horizontal-rule", FreeWRibbonCommandAction.HorizontalRule),
        new("freew.hyperlink", FreeWRibbonCommandAction.Hyperlink),
        new("freew.hyperlink-tooltip", FreeWRibbonCommandAction.HyperlinkTooltip),
        new("freew.hyphenation", FreeWRibbonCommandAction.Hyphenation),
        new("freew.hyphenation-auto", FreeWRibbonCommandAction.HyphenationAuto),
        new("freew.hyphenation-manual", FreeWRibbonCommandAction.HyphenationManual),
        new("freew.hyphenation-none", FreeWRibbonCommandAction.HyphenationNone),
        new("freew.hyphenation-options", FreeWRibbonCommandAction.HyphenationOptions),
        new("freew.image-adjust-dialog", FreeWRibbonCommandAction.ImageAdjustDialog),
        new("freew.image-align-center", FreeWRibbonCommandAction.ImageAlignCenter),
        new("freew.image-align-left", FreeWRibbonCommandAction.ImageAlignLeft),
        new("freew.image-align-right", FreeWRibbonCommandAction.ImageAlignRight),
        new("freew.image-align-to-margin", FreeWRibbonCommandAction.ImageAlignToMargin),
        new("freew.image-align-to-page", FreeWRibbonCommandAction.ImageAlignToPage),
        new("freew.image-alt-text", FreeWRibbonCommandAction.ImageAltText),
        new("freew.image-bevel-none", FreeWRibbonCommandAction.ImageBevelNone),
        new("freew.image-border", FreeWRibbonCommandAction.ImageBorder),
        new("freew.image-brightness-minus20", FreeWRibbonCommandAction.ImageBrightnessMinus20),
        new("freew.image-brightness-minus40", FreeWRibbonCommandAction.ImageBrightnessMinus40),
        new("freew.image-brightness-plus20", FreeWRibbonCommandAction.ImageBrightnessPlus20),
        new("freew.image-brightness-plus40", FreeWRibbonCommandAction.ImageBrightnessPlus40),
        new("freew.image-color-dialog", FreeWRibbonCommandAction.ImageColorDialog),
        new("freew.image-colortemp-cool", FreeWRibbonCommandAction.ImageColortempCool),
        new("freew.image-colortemp-neutral", FreeWRibbonCommandAction.ImageColortempNeutral),
        new("freew.image-colortemp-warm", FreeWRibbonCommandAction.ImageColortempWarm),
        new("freew.image-contrast-minus20", FreeWRibbonCommandAction.ImageContrastMinus20),
        new("freew.image-contrast-plus20", FreeWRibbonCommandAction.ImageContrastPlus20),
        new("freew.image-crop", FreeWRibbonCommandAction.ImageCrop),
        new("freew.image-distribute-h", FreeWRibbonCommandAction.ImageDistributeH),
        new("freew.image-distribute-v", FreeWRibbonCommandAction.ImageDistributeV),
        new("freew.image-recolor-blackwhite", FreeWRibbonCommandAction.ImageRecolorBlackwhite),
        new("freew.image-recolor-grayscale", FreeWRibbonCommandAction.ImageRecolorGrayscale),
        new("freew.image-recolor-none", FreeWRibbonCommandAction.ImageRecolorNone),
        new("freew.image-recolor-sepia", FreeWRibbonCommandAction.ImageRecolorSepia),
        new("freew.image-recolor-washout", FreeWRibbonCommandAction.ImageRecolorWashout),
        new("freew.image-reflection-none", FreeWRibbonCommandAction.ImageReflectionNone),
        new("freew.image-reset", FreeWRibbonCommandAction.ImageReset),
        new("freew.image-saturation-0", FreeWRibbonCommandAction.ImageSaturation0),
        new("freew.image-saturation-200", FreeWRibbonCommandAction.ImageSaturation200),
        new("freew.image-saturation-50", FreeWRibbonCommandAction.ImageSaturation50),
        new("freew.image-shadow-none", FreeWRibbonCommandAction.ImageShadowNone),
        new("freew.image-size", FreeWRibbonCommandAction.ImageSize),
        new("freew.image-transparency-25", FreeWRibbonCommandAction.ImageTransparency25),
        new("freew.image-transparency-50", FreeWRibbonCommandAction.ImageTransparency50),
        new("freew.image-transparency-75", FreeWRibbonCommandAction.ImageTransparency75),
        new("freew.image-transparency-dialog", FreeWRibbonCommandAction.ImageTransparencyDialog),
        new("freew.indent-decrease", FreeWRibbonCommandAction.IndentDecrease),
        new("freew.indent-increase", FreeWRibbonCommandAction.IndentIncrease),
        new("freew.indent-left", FreeWRibbonCommandAction.IndentLeft),
        new("freew.indent-right", FreeWRibbonCommandAction.IndentRight),
        new("freew.index-insert", FreeWRibbonCommandAction.IndexInsert),
        new("freew.index-mark", FreeWRibbonCommandAction.IndexMark),
        new("freew.index-refresh", FreeWRibbonCommandAction.IndexRefresh),
        new("freew.insert-caption.equation", FreeWRibbonCommandAction.InsertCaption_Equation),
        new("freew.insert-caption.figure", FreeWRibbonCommandAction.InsertCaption_Figure),
        new("freew.insert-caption.table", FreeWRibbonCommandAction.InsertCaption_Table),
        new("freew.insert-file", FreeWRibbonCommandAction.InsertFile),
        new("freew.insert-icon", FreeWRibbonCommandAction.InsertIcon),
        new("freew.inspect-document", FreeWRibbonCommandAction.InspectDocument),
        new("freew.italic", FreeWRibbonCommandAction.Italic),
        new("freew.keep-lines", FreeWRibbonCommandAction.KeepLines),
        new("freew.keep-with-next", FreeWRibbonCommandAction.KeepWithNext),
        new("freew.legal-notices", FreeWRibbonCommandAction.LegalNotices),
        new("freew.line-numbers", FreeWRibbonCommandAction.LineNumbers),
        new("freew.line-numbers-continuous", FreeWRibbonCommandAction.LineNumbersContinuous),
        new("freew.line-numbers-none", FreeWRibbonCommandAction.LineNumbersNone),
        new("freew.line-numbers-options", FreeWRibbonCommandAction.LineNumbersOptions),
        new("freew.line-numbers-restart-page", FreeWRibbonCommandAction.LineNumbersRestartPage),
        new("freew.line-numbers-restart-section", FreeWRibbonCommandAction.LineNumbersRestartSection),
        new("freew.line-spacing", FreeWRibbonCommandAction.LineSpacing),
        new("freew.link-bookmark", FreeWRibbonCommandAction.LinkBookmark),
        new("freew.manage-sources", FreeWRibbonCommandAction.ManageSources),
        new("freew.manage-styles", FreeWRibbonCommandAction.ManageStyles),
        new("freew.margins", FreeWRibbonCommandAction.Margins),
        new("freew.mark-as-final", FreeWRibbonCommandAction.MarkAsFinal),
        new("freew.mark-citation", FreeWRibbonCommandAction.MarkCitation),
        new("freew.merge-address-block", FreeWRibbonCommandAction.MergeAddressBlock),
        new("freew.merge-check-errors", FreeWRibbonCommandAction.MergeCheckErrors),
        new("freew.merge-data", FreeWRibbonCommandAction.MergeData),
        new("freew.merge-edit-recipients", FreeWRibbonCommandAction.MergeEditRecipients),
        new("freew.merge-email", FreeWRibbonCommandAction.MergeEmail),
        new("freew.merge-envelopes", FreeWRibbonCommandAction.MergeEnvelopes),
        new("freew.merge-field", FreeWRibbonCommandAction.MergeField),
        new("freew.merge-filter-sort", FreeWRibbonCommandAction.MergeFilterSort),
        new("freew.merge-find-recipient", FreeWRibbonCommandAction.MergeFindRecipient),
        new("freew.merge-finish", FreeWRibbonCommandAction.MergeFinish),
        new("freew.merge-greeting-line", FreeWRibbonCommandAction.MergeGreetingLine),
        new("freew.merge-labels", FreeWRibbonCommandAction.MergeLabels),
        new("freew.merge-match-fields", FreeWRibbonCommandAction.MergeMatchFields),
        new("freew.merge-next-record", FreeWRibbonCommandAction.MergeNextRecord),
        new("freew.merge-preview", FreeWRibbonCommandAction.MergePreview),
        new("freew.merge-preview-first", FreeWRibbonCommandAction.MergePreviewFirst),
        new("freew.merge-preview-last", FreeWRibbonCommandAction.MergePreviewLast),
        new("freew.merge-preview-next", FreeWRibbonCommandAction.MergePreviewNext),
        new("freew.merge-preview-previous", FreeWRibbonCommandAction.MergePreviewPrevious),
        new("freew.merge-record-number", FreeWRibbonCommandAction.MergeRecordNumber),
        new("freew.merge-rule-ask", FreeWRibbonCommandAction.MergeRuleAsk),
        new("freew.merge-rule-fill-in", FreeWRibbonCommandAction.MergeRuleFillIn),
        new("freew.merge-rule-if", FreeWRibbonCommandAction.MergeRuleIf),
        new("freew.merge-rule-next-record-if", FreeWRibbonCommandAction.MergeRuleNextRecordIf),
        new("freew.merge-rule-ref", FreeWRibbonCommandAction.MergeRuleRef),
        new("freew.merge-rules", FreeWRibbonCommandAction.MergeRules),
        new("freew.merge-rule-set", FreeWRibbonCommandAction.MergeRuleSet),
        new("freew.merge-rule-skip-record-if", FreeWRibbonCommandAction.MergeRuleSkipRecordIf),
        new("freew.merge-sequence-number", FreeWRibbonCommandAction.MergeSequenceNumber),
        new("freew.more-paper-sizes", FreeWRibbonCommandAction.MorePaperSizes),
        new("freew.multilevel-define", FreeWRibbonCommandAction.MultilevelDefine),
        new("freew.multilevel-demote", FreeWRibbonCommandAction.MultilevelDemote),
        new("freew.multilevel-list", FreeWRibbonCommandAction.MultilevelList),
        new("freew.multilevel-promote", FreeWRibbonCommandAction.MultilevelPromote),
        new("freew.new-comment", FreeWRibbonCommandAction.NewComment),
        new("freew.new-style", FreeWRibbonCommandAction.NewStyle),
        new("freew.next-change", FreeWRibbonCommandAction.NextChange),
        new("freew.next-comment", FreeWRibbonCommandAction.NextComment),
        new("freew.next-endnote", FreeWRibbonCommandAction.NextEndnote),
        new("freew.next-footnote", FreeWRibbonCommandAction.NextFootnote),
        new("freew.numbering", FreeWRibbonCommandAction.Numbering),
        new("freew.object", FreeWRibbonCommandAction.Object),
        new("freew.object-group", FreeWRibbonCommandAction.ObjectGroup),
        new("freew.object-ungroup", FreeWRibbonCommandAction.ObjectUngroup),
        new("freew.orientation", FreeWRibbonCommandAction.Orientation),
        new("freew.page-break", FreeWRibbonCommandAction.PageBreak),
        new("freew.page-color", FreeWRibbonCommandAction.PageColor),
        new("freew.page-number", FreeWRibbonCommandAction.PageNumber),
        new("freew.page-number-bottom", FreeWRibbonCommandAction.PageNumberBottom),
        new("freew.page-number-current", FreeWRibbonCommandAction.PageNumberCurrent),
        new("freew.page-number-format", FreeWRibbonCommandAction.PageNumberFormat),
        new("freew.page-number-top", FreeWRibbonCommandAction.PageNumberTop),
        new("freew.page-setup", FreeWRibbonCommandAction.PageSetup),
        new("freew.page-valign", FreeWRibbonCommandAction.PageValign),
        new("freew.para-border", FreeWRibbonCommandAction.ParaBorder),
        new("freew.paragraph-dialog", FreeWRibbonCommandAction.ParagraphDialog),
        new("freew.para-shading", FreeWRibbonCommandAction.ParaShading),
        new("freew.paste", FreeWRibbonCommandAction.Paste),
        new("freew.paste-merge", FreeWRibbonCommandAction.PasteMerge),
        new("freew.paste-plain", FreeWRibbonCommandAction.PastePlain),
        new("freew.paste-special", FreeWRibbonCommandAction.PasteSpecial),
        new("freew.picture", FreeWRibbonCommandAction.Picture),
        new("freew.previous-change", FreeWRibbonCommandAction.PreviousChange),
        new("freew.previous-comment", FreeWRibbonCommandAction.PreviousComment),
        new("freew.previous-endnote", FreeWRibbonCommandAction.PreviousEndnote),
        new("freew.previous-footnote", FreeWRibbonCommandAction.PreviousFootnote),
        new("freew.read-aloud", FreeWRibbonCommandAction.ReadAloud),
        new("freew.redo", FreeWRibbonCommandAction.Redo),
        new("freew.reject-this", FreeWRibbonCommandAction.RejectThis),
        new("freew.remove-hyperlink", FreeWRibbonCommandAction.RemoveHyperlink),
        new("freew.replace", FreeWRibbonCommandAction.Replace),
        new("freew.reply-comment", FreeWRibbonCommandAction.ReplyComment),
        new("freew.reset-style-set", FreeWRibbonCommandAction.ResetStyleSet),
        new("freew.resolve-comment", FreeWRibbonCommandAction.ResolveComment),
        new("freew.restrict-editing", FreeWRibbonCommandAction.RestrictEditing),
        new("freew.reviewing-pane", FreeWRibbonCommandAction.ReviewingPane),
        new("freew.save-quickpart", FreeWRibbonCommandAction.SaveQuickpart),
        new("freew.screen-clipping", FreeWRibbonCommandAction.ScreenClipping),
        new("freew.section-break-continuous", FreeWRibbonCommandAction.SectionBreakContinuous),
        new("freew.section-break-even-page", FreeWRibbonCommandAction.SectionBreakEvenPage),
        new("freew.section-break-next-page", FreeWRibbonCommandAction.SectionBreakNextPage),
        new("freew.section-break-odd-page", FreeWRibbonCommandAction.SectionBreakOddPage),
        new("freew.select", FreeWRibbonCommandAction.Select),
        new("freew.set-proofing-language", FreeWRibbonCommandAction.SetProofingLanguage),
        new("freew.shape-align-center", FreeWRibbonCommandAction.ShapeAlignCenter),
        new("freew.shape-align-left", FreeWRibbonCommandAction.ShapeAlignLeft),
        new("freew.shape-align-right", FreeWRibbonCommandAction.ShapeAlignRight),
        new("freew.shape-align-to-margin", FreeWRibbonCommandAction.ShapeAlignToMargin),
        new("freew.shape-align-to-page", FreeWRibbonCommandAction.ShapeAlignToPage),
        new("freew.shape-alt-text", FreeWRibbonCommandAction.ShapeAltText),
        new("freew.shape-change-ellipse", FreeWRibbonCommandAction.ShapeChangeEllipse),
        new("freew.shape-change-rectangle", FreeWRibbonCommandAction.ShapeChangeRectangle),
        new("freew.shape-change-rounded", FreeWRibbonCommandAction.ShapeChangeRounded),
        new("freew.shape-convert-freeform", FreeWRibbonCommandAction.ShapeConvertFreeform),
        new("freew.shape-distribute-h", FreeWRibbonCommandAction.ShapeDistributeH),
        new("freew.shape-distribute-v", FreeWRibbonCommandAction.ShapeDistributeV),
        new("freew.shape-edit-points", FreeWRibbonCommandAction.ShapeEditPoints),
        new("freew.shape-edit-shape", FreeWRibbonCommandAction.ShapeEditShape),
        new("freew.shape-effect-bevel", FreeWRibbonCommandAction.ShapeEffectBevel),
        new("freew.shape-effect-glow", FreeWRibbonCommandAction.ShapeEffectGlow),
        new("freew.shape-effect-reflection", FreeWRibbonCommandAction.ShapeEffectReflection),
        new("freew.shape-effects", FreeWRibbonCommandAction.ShapeEffects),
        new("freew.shape-effect-shadow", FreeWRibbonCommandAction.ShapeEffectShadow),
        new("freew.shape-effects-none", FreeWRibbonCommandAction.ShapeEffectsNone),
        new("freew.shape-effect-soft-edge", FreeWRibbonCommandAction.ShapeEffectSoftEdge),
        new("freew.shape-size", FreeWRibbonCommandAction.ShapeSize),
        new("freew.shape-styles-gallery", FreeWRibbonCommandAction.ShapeStylesGallery),
        new("freew.shape-text-direction", FreeWRibbonCommandAction.ShapeTextDirection),
        new("freew.shape-text-horizontal", FreeWRibbonCommandAction.ShapeTextHorizontal),
        new("freew.shape-text-rotate270", FreeWRibbonCommandAction.ShapeTextRotate270),
        new("freew.shape-text-rotate90", FreeWRibbonCommandAction.ShapeTextRotate90),
        new("freew.show-comments", FreeWRibbonCommandAction.ShowComments),
        new("freew.show-markup-balloons", FreeWRibbonCommandAction.ShowMarkupBalloons),
        new("freew.show-notes", FreeWRibbonCommandAction.ShowNotes),
        new("freew.shrink-font", FreeWRibbonCommandAction.ShrinkFont),
        new("freew.size", FreeWRibbonCommandAction.Size),
        new("freew.smallcaps", FreeWRibbonCommandAction.Smallcaps),
        new("freew.smartart", FreeWRibbonCommandAction.Smartart),
        new("freew.smartart-add-shape", FreeWRibbonCommandAction.SmartartAddShape),
        new("freew.smartart-change-style", FreeWRibbonCommandAction.SmartartChangeStyle),
        new("freew.smartart-demote", FreeWRibbonCommandAction.SmartartDemote),
        new("freew.smartart-edit-text", FreeWRibbonCommandAction.SmartartEditText),
        new("freew.smartart-move-down", FreeWRibbonCommandAction.SmartartMoveDown),
        new("freew.smartart-move-up", FreeWRibbonCommandAction.SmartartMoveUp),
        new("freew.smartart-promote", FreeWRibbonCommandAction.SmartartPromote),
        new("freew.smartart-remove-shape", FreeWRibbonCommandAction.SmartartRemoveShape),
        new("freew.sort", FreeWRibbonCommandAction.Sort),
        new("freew.space-after", FreeWRibbonCommandAction.SpaceAfter),
        new("freew.space-after-toggle", FreeWRibbonCommandAction.SpaceAfterToggle),
        new("freew.space-before", FreeWRibbonCommandAction.SpaceBefore),
        new("freew.space-before-toggle", FreeWRibbonCommandAction.SpaceBeforeToggle),
        new("freew.spellcheck-toggle", FreeWRibbonCommandAction.SpellcheckToggle),
        new("freew.split-table", FreeWRibbonCommandAction.SplitTable),
        new("freew.start-mail-merge", FreeWRibbonCommandAction.StartMailMerge),
        new("freew.start-mail-merge-directory", FreeWRibbonCommandAction.StartMailMergeDirectory),
        new("freew.start-mail-merge-letters", FreeWRibbonCommandAction.StartMailMergeLetters),
        new("freew.start-mail-merge-normal", FreeWRibbonCommandAction.StartMailMergeNormal),
        new("freew.statistics", FreeWRibbonCommandAction.Statistics),
        new("freew.strikethrough", FreeWRibbonCommandAction.Strikethrough),
        new("freew.style", FreeWRibbonCommandAction.Style),
        new("freew.style-clear", FreeWRibbonCommandAction.StyleClear),
        new("freew.style-heading1", FreeWRibbonCommandAction.StyleHeading1),
        new("freew.style-heading2", FreeWRibbonCommandAction.StyleHeading2),
        new("freew.style-heading3", FreeWRibbonCommandAction.StyleHeading3),
        new("freew.style-normal", FreeWRibbonCommandAction.StyleNormal),
        new("freew.style-set", FreeWRibbonCommandAction.StyleSet),
        new("freew.style-title", FreeWRibbonCommandAction.StyleTitle),
        new("freew.subscript", FreeWRibbonCommandAction.Subscript),
        new("freew.superscript", FreeWRibbonCommandAction.Superscript),
        new("freew.symbol", FreeWRibbonCommandAction.Symbol),
        new("freew.table", FreeWRibbonCommandAction.Table),
        new("freew.table-autofit-contents", FreeWRibbonCommandAction.TableAutofitContents),
        new("freew.table-autofit-fixed", FreeWRibbonCommandAction.TableAutofitFixed),
        new("freew.table-autofit-window", FreeWRibbonCommandAction.TableAutofitWindow),
        new("freew.table-banded-cols", FreeWRibbonCommandAction.TableBandedCols),
        new("freew.table-banded-rows", FreeWRibbonCommandAction.TableBandedRows),
        new("freew.table-cell-margins", FreeWRibbonCommandAction.TableCellMargins),
        new("freew.table-col-width", FreeWRibbonCommandAction.TableColWidth),
        new("freew.table-delete", FreeWRibbonCommandAction.TableDelete),
        new("freew.table-delete-col", FreeWRibbonCommandAction.TableDeleteCol),
        new("freew.table-delete-row", FreeWRibbonCommandAction.TableDeleteRow),
        new("freew.table-distribute-cols", FreeWRibbonCommandAction.TableDistributeCols),
        new("freew.table-distribute-rows", FreeWRibbonCommandAction.TableDistributeRows),
        new("freew.table-first-column", FreeWRibbonCommandAction.TableFirstColumn),
        new("freew.table-formula", FreeWRibbonCommandAction.TableFormula),
        new("freew.table-header-row", FreeWRibbonCommandAction.TableHeaderRow),
        new("freew.table-insert-above", FreeWRibbonCommandAction.TableInsertAbove),
        new("freew.table-insert-col-left", FreeWRibbonCommandAction.TableInsertColLeft),
        new("freew.table-last-column", FreeWRibbonCommandAction.TableLastColumn),
        new("freew.table-last-row", FreeWRibbonCommandAction.TableLastRow),
        new("freew.table-of-authorities", FreeWRibbonCommandAction.TableOfAuthorities),
        new("freew.table-of-authorities-refresh", FreeWRibbonCommandAction.TableOfAuthoritiesRefresh),
        new("freew.table-properties", FreeWRibbonCommandAction.TableProperties),
        new("freew.table-repeat-header", FreeWRibbonCommandAction.TableRepeatHeader),
        new("freew.table-row-height", FreeWRibbonCommandAction.TableRowHeight),
        new("freew.table-select-cell", FreeWRibbonCommandAction.TableSelectCell),
        new("freew.table-select-col", FreeWRibbonCommandAction.TableSelectCol),
        new("freew.table-select-row", FreeWRibbonCommandAction.TableSelectRow),
        new("freew.table-select-table", FreeWRibbonCommandAction.TableSelectTable),
        new("freew.table-to-text", FreeWRibbonCommandAction.TableToText),
        new("freew.table-view-gridlines", FreeWRibbonCommandAction.TableViewGridlines),
        new("freew.tabs-dialog", FreeWRibbonCommandAction.TabsDialog),
        new("freew.text-to-table", FreeWRibbonCommandAction.TextToTable),
        new("freew.theme", FreeWRibbonCommandAction.Theme),
        new("freew.theme-colors", FreeWRibbonCommandAction.ThemeColors),
        new("freew.theme-effects", FreeWRibbonCommandAction.ThemeEffects),
        new("freew.theme-fonts", FreeWRibbonCommandAction.ThemeFonts),
        new("freew.thesaurus", FreeWRibbonCommandAction.Thesaurus),
        new("freew.toc", FreeWRibbonCommandAction.Toc),
        new("freew.toc-refresh", FreeWRibbonCommandAction.TocRefresh),
        new("freew.tof", FreeWRibbonCommandAction.Tof),
        new("freew.tof.equation", FreeWRibbonCommandAction.Tof_Equation),
        new("freew.tof.figure", FreeWRibbonCommandAction.Tof_Figure),
        new("freew.tof.table", FreeWRibbonCommandAction.Tof_Table),
        new("freew.tof-refresh", FreeWRibbonCommandAction.TofRefresh),
        new("freew.tof-refresh.equation", FreeWRibbonCommandAction.TofRefresh_Equation),
        new("freew.tof-refresh.figure", FreeWRibbonCommandAction.TofRefresh_Figure),
        new("freew.tof-refresh.table", FreeWRibbonCommandAction.TofRefresh_Table),
        new("freew.toggle-field-codes", FreeWRibbonCommandAction.ToggleFieldCodes),
        new("freew.underline", FreeWRibbonCommandAction.Underline),
        new("freew.undo", FreeWRibbonCommandAction.Undo),
        new("freew.update-fields", FreeWRibbonCommandAction.UpdateFields),
        new("freew.watermark", FreeWRibbonCommandAction.Watermark),
        new("freew.widow-control", FreeWRibbonCommandAction.WidowControl),
        new("freew.wordart", FreeWRibbonCommandAction.Wordart),
    ];

    private static readonly IReadOnlyDictionary<FreeWRibbonCommandAction, FreeWRibbonCommandRoute[]> RoutesByAction =
        RouteData
            .GroupBy(route => route.Action)
            .ToDictionary(group => group.Key, group => group.ToArray());

    public static IReadOnlyList<FreeWRibbonCommandRoute> Routes => RouteData;

    public static RibbonCommandId GetPrimaryCommandId(FreeWRibbonCommandAction action)
    {
        if (!RoutesByAction.TryGetValue(action, out var routes) || routes.Length == 0)
            throw new ArgumentOutOfRangeException(nameof(action), action, "Unknown FreeW ribbon action.");

        return routes[0].CommandId;
    }

    public static void Register(
        IRibbonCommandRegistry registry,
        FreeWRibbonCommandAction action,
        IRibbonCommand nativeCommand)
    {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentNullException.ThrowIfNull(nativeCommand);

        if (!RoutesByAction.TryGetValue(action, out var routes))
            throw new ArgumentOutOfRangeException(nameof(action), action, "Unknown FreeW ribbon action.");

        foreach (var route in routes)
            registry.Register(route.CommandId, nativeCommand);
    }

    public static IRibbonCommand RegisterAction(
        IRibbonCommandRegistry registry,
        FreeWRibbonCommandAction action,
        Action execute,
        Func<bool>? isEnabled = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(execute);
        var command = new DelegatedCommand(
            _ => execute(),
            isEnabled is null ? null : () => new RibbonCommandState(IsEnabled: isEnabled()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    public static IRibbonCommand RegisterValue(
        IRibbonCommandRegistry registry,
        FreeWRibbonCommandAction action,
        Action<string?> execute,
        Func<bool>? isEnabled = null,
        Func<string?>? getValue = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(execute);
        var command = new DelegatedCommand(
            context => execute(context.SelectedValue),
            isEnabled is null && getValue is null
                ? null
                : () => new RibbonCommandState(
                    IsEnabled: isEnabled?.Invoke() ?? true,
                    Value: getValue?.Invoke()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    public static IRibbonStatefulCommand RegisterToggle(
        IRibbonCommandRegistry registry,
        FreeWRibbonCommandAction action,
        Action toggle,
        Func<bool> isChecked,
        Func<bool>? isEnabled = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(toggle);
        ArgumentNullException.ThrowIfNull(isChecked);
        var command = new DelegatedCommand(
            _ => toggle(),
            () => new RibbonCommandState(
                IsEnabled: isEnabled?.Invoke() ?? true,
                IsChecked: isChecked()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    private sealed class DelegatedCommand(
        Action<RibbonCommandContext> execute,
        Func<RibbonCommandState>? getState,
        Action? prepareExecution) : IRibbonStatefulCommand
    {
        public void Execute(RibbonCommandContext context)
        {
            if (getState?.Invoke().IsEnabled == false)
                return;

            prepareExecution?.Invoke();
            execute(context);
        }

        public RibbonCommandState GetState() => getState?.Invoke() ?? RibbonCommandState.Default;
    }
}
