using FreeW.App.Presentation.Dialogs;
using FreeW.Core.Model;

namespace FreeW.App.Presentation.Ribbon;

/// <summary>
/// Renderer-neutral shell operations consumed by FreeW ribbon execution. Native hosts retain
/// ownership of file pickers, dialogs, panes, windows, focus, and control interaction.
/// </summary>
public sealed record FreeWRibbonHostExecutionPorts(
    Action Open,
    Action Save,
    Action Cut,
    Action Copy,
    Action Paste,
    Action Backstage,
    Action NewDocument,
    Action ToggleNavigationPane,
    Action ToggleReviewingPane,
    Action ToggleRevealFormatting,
    Action OpenFindReplaceDialog,
    Action SetPrintLayout,
    Action SetWebLayout,
    Action SetDraftView,
    Action OpenFontDialog,
    Action OpenParagraphDialog,
    Action OpenPageSetupDialog,
    Action ToggleOrientation,
    Action<string> ApplyMarginPreset,
    Action<string> ApplyPaperSize,
    Action InsertPicture,
    Action OpenWordCountDialog,
    Action<double?, double> ApplyZoom,
    Action? InsertObject = null,
    Func<bool>? IsPrintLayoutActive = null,
    Func<bool>? IsWebLayoutActive = null,
    Func<bool>? IsDraftViewActive = null,
    Func<bool>? IsNavigationPaneVisible = null,
    Func<bool>? IsReviewingPaneVisible = null,
    Func<bool>? IsRevealFormattingVisible = null,
    Action? OpenSymbolPickerDialog = null,
    Action? CaptureScreenClip = null,
    Action? OpenTabsDialog = null,
    Action? OpenBordersAndShadingDialog = null,
    Action? OpenCharacterBorderDialog = null,
    Action? OpenCharacterShadingDialog = null,
    Action? OpenCellShadingDialog = null,
    Action? OpenSortDialog = null,
    Action? OpenZoomDialog = null,
    Action? OpenPrintPreview = null,
    Action? NewWindow = null,
    Action? ArrangeAll = null,
    Action? ToggleSplit = null,
    Func<bool>? IsSplitActive = null,
    Action? ZoomOnePage = null,
    Action? ZoomPageWidth = null,
    Action? ToggleMultiplePages = null,
    Func<bool>? IsMultiplePagesActive = null,
    Action? ToggleSideToSide = null,
    Func<bool>? IsSideToSideActive = null,
    Action? OpenHyperlinkDialog = null,
    Action? OpenEditHyperlinkDialog = null,
    Action? OpenHyperlinkTooltipDialog = null,
    Action? OpenBookmarkDialog = null,
    Action? OpenLinkBookmarkDialog = null,
    Action? OpenQuickPartDialog = null,
    Action? SaveQuickPartSelection = null,
    Action? OpenBuildingBlocksOrganizer = null,
    Action? OpenFieldDialog = null,
    Action? OpenDrawTableDialog = null,
    Action? OpenSplitCellDialog = null,
    Action? InsertTextFromFile = null,
    Func<string, string?>? AskRecipientCsv = null,
    Func<IReadOnlyList<string>, string?>? AskMergeFieldName = null,
    Action<string>? ShowMailMergeInfo = null,
    Action? OpenPageBordersDialog = null,
    Action? OpenWatermarkDialog = null,
    Action? MarkAsFinal = null,
    Action? RestrictEditing = null,
    Action? InspectDocument = null,
    Action? CheckAccessibility = null,
    Action? ReplyComment = null,
    Action<IReadOnlyList<CommentListItem>>? ShowComments = null,
    Action? ToggleSpellcheck = null,
    Func<bool>? IsSpellcheckActive = null,
    Action? AddToDictionary = null,
    Action? OpenThesaurus = null,
    Action? SetProofingLanguage = null,
    Action? ToggleReadAloud = null,
    Func<bool>? IsReadAloudActive = null,
    Action? PreviousChange = null,
    Action? NextChange = null,
    Action? AcceptThisChange = null,
    Action? RejectThisChange = null,
    Action? CompareDocuments = null,
    Action? CombineDocuments = null,
    Action? SetOutlineView = null,
    Func<bool>? IsOutlineViewActive = null,
    Action? TogglePagedEditView = null,
    Func<bool>? IsPagedEditViewActive = null,
    Action? ImportPdfText = null,
    Action<ModelTableContext>? OpenTablePropertiesDialog = null,
    Action<TableFormulaDialogInitialState>? OpenTableFormulaDialog = null,
    Action? OpenLegalNotices = null,
    Action? OpenAbout = null,
    Action? PastePlainText = null,
    Action? PasteMergeFormatting = null,
    Action? OpenPasteSpecial = null,
    Action? OpenNewStyleDialog = null,
    Action? OpenManageStylesDialog = null,
    Action? OpenCrossReferenceDialog = null,
    Action? OpenCaptionDialog = null,
    Action? OpenCitationDialog = null,
    Action? OpenManageSourcesDialog = null,
    Action? OpenMarkIndexEntryDialog = null,
    Action? OpenInsertIndexDialog = null,
    Action? OpenUpdateIndexDialog = null,
    Action? OpenMarkCitationDialog = null,
    Func<ToaOptions?>? OpenTableOfAuthoritiesDialog = null,
    Action? ToggleReviewBalloons = null,
    Func<bool>? IsReviewBalloonsActive = null,
    Func<IReadOnlyList<string>, MailMergeRuleIfDialogResult?>? AskMergeRuleIf = null,
    Func<IReadOnlyList<string>, string, MailMergeRuleConditionDialogResult?>? AskMergeRuleCondition = null,
    Func<string, string, string?>? AskMergeRulePrompt = null,
    Func<string, string, MailMergeRuleNameValueDialogResult?>? AskMergeRuleNameValue = null,
    Action? OpenPageNumberFormatDialog = null,
    Action? OpenImageCropDialog = null,
    Action? OpenImageSizeDialog = null,
    Action? OpenImageAltTextDialog = null,
    Action? OpenImageBorderDialog = null,
    Action? OpenImageAdjustDialog = null,
    Action? OpenImagePositionDialog = null,
    Action? OpenShapePositionDialog = null,
    Action? OpenShapeSizeDialog = null,
    Action? OpenShapeAltTextDialog = null,
    Action? OpenInsertChartDialog = null,
    Action? OpenChartEditDataDialog = null,
    Action? OpenChartTitleDialog = null,
    Action? OpenChartAxisTitlesDialog = null,
    Action? OpenChartSizeDialog = null,
    Action? OpenInsertSmartArtDialog = null,
    Action? OpenIconPickerDialog = null,
    Action? OpenTableToTextDialog = null,
    Action? OpenSmartArtEditDialog = null,
    Action? OpenDateTimeDialog = null,
    Action? OpenTextToTableDialog = null,
    Action? OpenMultilevelListDialog = null,
    Action? OpenFootnoteDialog = null,
    Action? OpenEndnoteDialog = null,
    Action? ToggleNotesPane = null,
    Func<bool>? IsNotesPaneVisible = null,
    Action? OpenFootnoteEndnoteOptionsDialog = null,
    Action? OpenBookmarkManagerDialog = null,
    Action? ShowTableOfAuthoritiesDialog = null,
    Action? OpenColumnsDialog = null,
    Action? OpenCustomParagraphSpacingDialog = null,
    Action? OpenCustomizeThemeColorsDialog = null,
    Action? OpenCustomizeThemeFontsDialog = null,
    Action? OpenPageColorDialog = null,
    Action? OpenDropCapOptionsDialog = null,
    Action? OpenHyphenationOptionsDialog = null,
    Action? OpenManualHyphenationDialog = null,
    Action? OpenLineNumberOptionsDialog = null,
    Action? OpenCustomMarginsDialog = null,
    Action? OpenMorePaperSizesDialog = null,
    Action? OpenHelpOnline = null,
    Action? OpenFeedback = null,
    Action? CopyDiagnostics = null,
    Action? CheckForUpdates = null,
    Action? ToggleReadMode = null,
    Func<bool>? IsReadModeActive = null,
    Action<string>? ApplyReadModeColumnWidth = null,
    Action<string>? ApplyReadModePageColor = null,
    Func<bool, string, Task<string?>>? AskHeaderFooterText = null)
{
    public static FreeWRibbonHostExecutionPorts Empty { get; } = new(
        Open: Noop,
        Save: Noop,
        Cut: Noop,
        Copy: Noop,
        Paste: Noop,
        Backstage: Noop,
        NewDocument: Noop,
        ToggleNavigationPane: Noop,
        ToggleReviewingPane: Noop,
        ToggleRevealFormatting: Noop,
        OpenFindReplaceDialog: Noop,
        SetPrintLayout: Noop,
        SetWebLayout: Noop,
        SetDraftView: Noop,
        OpenFontDialog: Noop,
        OpenParagraphDialog: Noop,
        OpenPageSetupDialog: Noop,
        ToggleOrientation: Noop,
        ApplyMarginPreset: Ignore,
        ApplyPaperSize: Ignore,
        InsertPicture: Noop,
        OpenWordCountDialog: Noop,
        ApplyZoom: IgnoreZoom);

    private static void Noop()
    {
    }

    private static void Ignore(string value)
    {
    }

    private static void IgnoreZoom(double? absolute, double delta)
    {
    }
}
