<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeW.Core.Model\FreeW.Core.Model.csproj" />
    <ProjectReference Include="..\FreeW.Core.IO\FreeW.Core.IO.csproj" />
    <ProjectReference Include="..\FreeW.App.Localization\FreeW.App.Localization.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Drawing\Free.Shared.Drawing.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Shell\Free.Shared.Shell.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Theme\Free.Shared.Theme.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Ribbon\Free.Shared.Ribbon.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.IO\Free.Shared.IO.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Localization\Free.Shared.Localization.csproj" />
    <ProjectReference Include="..\..\tools\Free.ToolsShared\Free.ToolsShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.IO" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\FreeW.App.Host\Resources\thesaurus-en.txt"
                      LogicalName="FreeW.App.Presentation.Resources.thesaurus-en.txt" />
  </ItemGroup>

</Project>
