<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Free.Shared.Shell.Avalonia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

</Project>
