<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeP.App.Localization\FreeP.App.Localization.csproj" />
    <ProjectReference Include="..\FreeP.App.Presentation\FreeP.App.Presentation.csproj" />
    <ProjectReference Include="..\..\shared\Free.Shared.Ribbon\Free.Shared.Ribbon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Free.Shared.Ribbon" />
  </ItemGroup>

</Project>
