using System.Text;
using Free.ToolsShared;
using FreeP.App.Compositor;
using FreeP.Core.Model;

return GeneratedEvidenceToolRunner.Run(
    args,
    new GeneratedEvidenceToolSpec(
        "FreeP.slnx",
        Path.Combine("docs", "parity", "freep-random-transition-playback-20260720.md"),
        BuildReport));

static string BuildReport()
{
    var presentation = Presentation.CreateEmpty();
    presentation.SlideSizeCxEmu = 12_192_000;
    presentation.SlideSizeCyEmu = 6_858_000;
    presentation.Properties.Title = "FreeP Random parity evidence";
    presentation.Properties.Author = "FreeP";
    var slide = presentation.Slides[0];
    slide.Id = "rId2";
    slide.NumericId = 256;
    slide.Title = "Random transition";
    slide.Transition = new SlideTransition
    {
        Kind = TransitionKind.Random,
        Direction = TransitionDirection.Right,
        SplitOrientation = TransitionDirection.Vertical,
        DurationMs = 875,
        AdvanceOnClick = false,
        AdvanceAfterMs = 2_400,
        MorphOption = "byWord",
        WheelSpokeCount = 8
    };

    var randomPlan = SlideShowPlaybackPlanner.PlanTransition(
        presentation,
        slide,
        slide.Transition);
    var otherPlan = SlideShowPlaybackPlanner.PlanTransition(
        new SlideTransition { Kind = TransitionKind.Other });

    var builder = new StringBuilder();
    builder.AppendLine("# FreeP Random Transition Playback Evidence");
    builder.AppendLine();
    builder.AppendLine("> Generated by `tools/FreeP.RandomTransitionEvidence` from `SlideShowTransitionPlanner` and `SlideShowPlaybackPlanner`. Do not edit by hand.");
    builder.AppendLine();
    builder.AppendLine("## Authority");
    builder.AppendLine();
    builder.AppendLine("- PresentationML stores Random as the empty `p:random` transition element.");
    builder.AppendLine("- The Open XML contract chooses from transitions available in the rendering application and permits a different result each use.");
    builder.AppendLine("- FreeP retains `TransitionKind.Random` in the model/package, but its slideshow planner uses a stable deck/slide/transition seed so WPF and Avalonia execute the same available family.");
    builder.AppendLine("- Authority: [Microsoft Open XML RandomTransition](https://learn.microsoft.com/en-ca/dotnet/api/documentformat.openxml.presentation.randomtransition?view=openxml-2.9.1).");
    builder.AppendLine();
    builder.AppendLine("## Deterministic Sample");
    builder.AppendLine();
    builder.AppendLine($"- Stable seed: `{randomPlan.RandomSeed}`");
    builder.AppendLine($"- Resolved model kind: `{randomPlan.ResolvedKind}`");
    builder.AppendLine($"- Renderer-neutral family: `{randomPlan.SourceKind}`");
    builder.AppendLine($"- Playback action: `{randomPlan.ActionKind}`");
    builder.AppendLine($"- Preserved duration: `{randomPlan.DurationMs}` ms");
    builder.AppendLine();
    builder.AppendLine("## Candidate Set");
    builder.AppendLine();
    builder.AppendLine($"The ordered set has {SlideShowTransitionPlanner.RandomCandidateKinds.Count} entries, one representative per dedicated playback family. None, Random, Other, aliases, PushLike, and FadeFallback are excluded.");
    builder.AppendLine();
    builder.AppendLine("| Index | Model representative | Renderer-neutral family |");
    builder.AppendLine("| ---: | --- | --- |");
    for (var index = 0; index < SlideShowTransitionPlanner.RandomCandidateKinds.Count; index++)
    {
        var kind = SlideShowTransitionPlanner.RandomCandidateKinds[index];
        var family = SlideShowTransitionPlanner.Plan(
            new SlideTransition { Kind = kind }).PlaybackKind;
        builder.AppendLine($"| {index} | `{kind}` | `{family}` |");
    }

    builder.AppendLine();
    builder.AppendLine("## Fallback Classification");
    builder.AppendLine();
    builder.AppendLine("| Source kind | Resolved kind | Source family | Playback action | Classification |");
    builder.AppendLine("| --- | --- | --- | --- | --- |");
    builder.AppendLine($"| `Random` | `{randomPlan.ResolvedKind}` | `{randomPlan.SourceKind}` | `{randomPlan.ActionKind}` | Deterministic available-family selection |");
    builder.AppendLine($"| `Other` | `{otherPlan.ResolvedKind}` | `{otherPlan.SourceKind}` | `{otherPlan.ActionKind}` | Intentional unknown-transition fallback |");
    builder.AppendLine();
    builder.AppendLine("Exact remaining named transition fallbacks: `Other` only. Random does not recurse and never enters FadeFallback.");
    return builder.ToString();
}
