<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FreeW.App.Presentation\FreeW.App.Presentation.csproj" />
    <ProjectReference Include="..\..\FreeW.Core.Model\FreeW.Core.Model.csproj" />
    <ProjectReference Include="..\..\..\shared\Free.Shared.AppServices\Free.Shared.AppServices.csproj" />
  </ItemGroup>

</Project>
