param(
    [string]$MarkdownPath = "docs\parity\dialog-visual-evidence-summary.md",
    [string]$InventoryPath = "docs\parity\dialog-parity-inventory.json",
    [string]$WpfManifestPath = "docs\parity\dialog-visual-assets\wpf-capture\manifest.json",
    [string]$AvaloniaManifestPath = "docs\parity\dialog-visual-assets\avalonia-capture\manifest.json",
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath {
    param([Parameter(Mandatory = $true)][string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $repoRoot $Path
}

function ConvertTo-RepoRelativePath {
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    $fullRoot = [System.IO.Path]::GetFullPath($repoRoot).TrimEnd('\')
    if ($fullPath.StartsWith($fullRoot + "\", [System.StringComparison]::OrdinalIgnoreCase)) {
        return $fullPath.Substring($fullRoot.Length + 1).Replace('/', '\')
    }

    return $fullPath.Replace('/', '\')
}

function Escape-MarkdownCell {
    param([string]$Value)

    if ($null -eq $Value -or $Value.Length -eq 0) {
        return ""
    }

    $Value.Replace('|', '\|')
}

function Read-JsonFile {
    param([Parameter(Mandatory = $true)][string]$Path)

    $resolvedPath = Resolve-RepoPath $Path
    if (-not (Test-Path -LiteralPath $resolvedPath -PathType Leaf)) {
        throw "Required dialog evidence input was not found: $resolvedPath"
    }

    Get-Content -LiteralPath $resolvedPath -Raw | ConvertFrom-Json
}

function Test-ManifestPngExists {
    param(
        [Parameter(Mandatory = $true)]$Surface,
        [Parameter(Mandatory = $true)][string]$ManifestPath
    )

    $png = [string]$Surface.png
    if ([string]::IsNullOrWhiteSpace($png)) {
        return $false
    }

    $resolvedPngPath = if ([System.IO.Path]::IsPathRooted($png)) {
        $png
    }
    else {
        Join-Path (Split-Path -Parent (Resolve-RepoPath $ManifestPath)) $png
    }

    Test-Path -LiteralPath $resolvedPngPath -PathType Leaf
}

function Get-CapturedSurfaces {
    param(
        [Parameter(Mandatory = $true)]$Manifest,
        [string]$ManifestPath,
        [switch]$RequirePng
    )

    $capturedSurfaces = @($Manifest.surfaces) |
        Where-Object { $_.captured -eq $true }

    if ($RequirePng) {
        if ([string]::IsNullOrWhiteSpace($ManifestPath)) {
            throw "ManifestPath is required when RequirePng is set."
        }

        $capturedSurfaces = @($capturedSurfaces |
            Where-Object { Test-ManifestPngExists -Surface $_ -ManifestPath $ManifestPath })
    }

    $capturedSurfaces | Sort-Object -Property id
}

function Get-RouteFamily {
    param(
        [Parameter(Mandatory = $true)][string]$SurfaceId,
        [Parameter(Mandatory = $true)][string[]]$RouteIds
    )

    if ($RouteIds -contains $SurfaceId) {
        return $SurfaceId
    }

    $match = $RouteIds |
        Where-Object { $SurfaceId.StartsWith($_ + ".", [System.StringComparison]::Ordinal) } |
        Sort-Object -Property Length -Descending |
        Select-Object -First 1

    if ($null -ne $match) {
        return [string]$match
    }

    return $SurfaceId
}

$inventory = Read-JsonFile $InventoryPath
$wpfManifest = Read-JsonFile $WpfManifestPath
$avaloniaManifest = Read-JsonFile $AvaloniaManifestPath

$inventoryRows = @($inventory.rows)
$routeIds = @($inventoryRows | ForEach-Object { [string]$_.routeId })

$wpfSurfaces = @(Get-CapturedSurfaces -Manifest $wpfManifest -ManifestPath $WpfManifestPath -RequirePng)
$avaloniaSurfaces = @(Get-CapturedSurfaces $avaloniaManifest)

$wpfById = @{}
foreach ($surface in $wpfSurfaces) {
    $wpfById[[string]$surface.id] = $surface
}

$avaloniaById = @{}
foreach ($surface in $avaloniaSurfaces) {
    $avaloniaById[[string]$surface.id] = $surface
}

$pairedIds = @($wpfById.Keys | Where-Object { $avaloniaById.ContainsKey($_) } | Sort-Object)
$wpfOnlyIds = @($wpfById.Keys | Where-Object { -not $avaloniaById.ContainsKey($_) } | Sort-Object)
$avaloniaOnlyIds = @($avaloniaById.Keys | Where-Object { -not $wpfById.ContainsKey($_) } | Sort-Object)

$additionalGroups = $avaloniaOnlyIds |
    Group-Object { Get-RouteFamily -SurfaceId $_ -RouteIds $routeIds } |
    Sort-Object -Property Name

$multiSurfaceGroups = @($additionalGroups | Where-Object { $_.Count -gt 1 })
$singleSurfaceGroupCount = @($additionalGroups | Where-Object { $_.Count -eq 1 }).Count

$wpfManifestRelativePath = ConvertTo-RepoRelativePath (Resolve-RepoPath $WpfManifestPath)
$avaloniaManifestRelativePath = ConvertTo-RepoRelativePath (Resolve-RepoPath $AvaloniaManifestPath)
$inventoryRelativePath = ConvertTo-RepoRelativePath (Resolve-RepoPath $InventoryPath)

$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine("# Dialog visual evidence summary")
[void]$md.AppendLine()
[void]$md.AppendLine("Generated by tools/Generate-DialogVisualEvidenceSummary.ps1 from committed dialog capture manifests and the generated dialog parity inventory.")
[void]$md.AppendLine()
[void]$md.AppendLine("This is a compact evidence comparison, not a pixel-diff or functional parity claim. It answers whether the checked-in WPF and Avalonia capture manifests have matching committed PNG evidence for the named manifest surfaces.")
[void]$md.AppendLine()
[void]$md.AppendLine("Sources:")
[void]$md.AppendLine()
[void]$md.AppendLine("- $inventoryRelativePath")
[void]$md.AppendLine("- $wpfManifestRelativePath")
[void]$md.AppendLine("- $avaloniaManifestRelativePath")
[void]$md.AppendLine()
[void]$md.AppendLine("## Current inventory rollup")
[void]$md.AppendLine()
[void]$md.AppendLine("| Metric | Count |")
[void]$md.AppendLine("| --- | ---: |")
[void]$md.AppendLine("| Dialog routes | $($inventory.summary.totalRoutes) |")
[void]$md.AppendLine("| WPF capture evidence | $($inventory.summary.wpfCaptures) |")
[void]$md.AppendLine("| Avalonia capture evidence | $($inventory.summary.avaloniaCaptures) |")
[void]$md.AppendLine("| Avalonia harness routes | $($inventory.summary.avaloniaHarnessRoutes) |")
[void]$md.AppendLine("| Shared/presentation-backed routes | $($inventory.summary.sharedOrPresentationBacked) |")
[void]$md.AppendLine()
[void]$md.AppendLine("## Manifest comparison")
[void]$md.AppendLine()
[void]$md.AppendLine("| Metric | Count |")
[void]$md.AppendLine("| --- | ---: |")
[void]$md.AppendLine("| WPF captured manifest surfaces | $($wpfSurfaces.Count) |")
[void]$md.AppendLine("| Avalonia captured manifest surfaces | $($avaloniaSurfaces.Count) |")
[void]$md.AppendLine("| Paired captured surface ids | $($pairedIds.Count) |")
[void]$md.AppendLine("| WPF manifest ids without Avalonia pair | $($wpfOnlyIds.Count) |")
[void]$md.AppendLine("| Additional Avalonia captured surface ids | $($avaloniaOnlyIds.Count) |")
[void]$md.AppendLine()

if ($wpfOnlyIds.Count -gt 0) {
    [void]$md.AppendLine("WPF manifest ids without an Avalonia pair: $($wpfOnlyIds -join ', ').")
    [void]$md.AppendLine()
}

[void]$md.AppendLine("## Paired manifest surfaces")
[void]$md.AppendLine()
[void]$md.AppendLine("| Surface id | WPF PNG | Avalonia PNG |")
[void]$md.AppendLine("| --- | --- | --- |")
foreach ($id in $pairedIds) {
    $wpfPng = [string]$wpfById[$id].png
    $avaloniaPng = [string]$avaloniaById[$id].png
    [void]$md.AppendLine("| $(Escape-MarkdownCell $id) | $(Escape-MarkdownCell $wpfPng) | $(Escape-MarkdownCell $avaloniaPng) |")
}

[void]$md.AppendLine()
[void]$md.AppendLine("## Additional Avalonia manifest surfaces")
[void]$md.AppendLine()
[void]$md.AppendLine("Avalonia has $($avaloniaOnlyIds.Count) additional captured manifest surface ids across $($additionalGroups.Count) dialog route families. $singleSurfaceGroupCount families have a single additional surface; multi-surface families are listed below.")
[void]$md.AppendLine()
[void]$md.AppendLine("| Route family | Additional surface ids |")
[void]$md.AppendLine("| --- | --- |")
foreach ($group in $multiSurfaceGroups) {
    $ids = @($group.Group | Sort-Object)
    [void]$md.AppendLine("| $(Escape-MarkdownCell $group.Name) | $(Escape-MarkdownCell ($ids -join '<br>')) |")
}

$markdown = $md.ToString()
$resolvedMarkdownPath = Resolve-RepoPath $MarkdownPath

if ($Check) {
    $existingMarkdown = if (Test-Path -LiteralPath $resolvedMarkdownPath -PathType Leaf) { Get-Content -LiteralPath $resolvedMarkdownPath -Raw } else { "" }
    if ($existingMarkdown -ne $markdown) {
        throw "Dialog visual evidence summary is out of date. Run tools\Generate-DialogVisualEvidenceSummary.ps1 to refresh it."
    }

    Write-Host "Dialog visual evidence summary is up to date."
    return
}

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $resolvedMarkdownPath) | Out-Null
Set-Content -LiteralPath $resolvedMarkdownPath -Value $markdown -Encoding utf8 -NoNewline

Write-Host "WPF captured manifest surfaces: $($wpfSurfaces.Count)"
Write-Host "Avalonia captured manifest surfaces: $($avaloniaSurfaces.Count)"
Write-Host "Paired captured surface ids: $($pairedIds.Count)"
Write-Host "WPF-only manifest surface ids: $($wpfOnlyIds.Count)"
Write-Host "Additional Avalonia captured surface ids: $($avaloniaOnlyIds.Count)"
Write-Host "Wrote $(ConvertTo-RepoRelativePath $resolvedMarkdownPath)"
