param(
    [string]$JsonPath = "docs\parity\freew-command-inventory.json",
    [string]$MarkdownPath = "docs\parity\freew-command-inventory.md",
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath {
    param([Parameter(Mandatory = $true)][string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $repoRoot $Path
}

function Convert-ToXmlAttribute {
    param([Parameter(Mandatory = $true)][string]$Value)

    return [System.Security.SecurityElement]::Escape($Value)
}

function Test-FileContentMatches {
    param(
        [Parameter(Mandatory = $true)][string]$ExpectedPath,
        [Parameter(Mandatory = $true)][string]$ActualPath,
        [Parameter(Mandatory = $true)][string]$Label
    )

    if (-not (Test-Path -LiteralPath $ActualPath -PathType Leaf)) {
        throw "$Label is missing. Run tools\Generate-FreeWCommandInventory.ps1 to create it."
    }

    $expected = Get-Content -LiteralPath $ExpectedPath -Raw
    $actual = Get-Content -LiteralPath $ActualPath -Raw
    if ($expected -cne $actual) {
        throw "$Label is out of date. Run tools\Generate-FreeWCommandInventory.ps1 to refresh it."
    }
}

$resolvedJsonPath = Resolve-RepoPath $JsonPath
$resolvedMarkdownPath = Resolve-RepoPath $MarkdownPath
$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("freex-freew-command-inventory-" + [System.Guid]::NewGuid().ToString("N"))
$tempJsonPath = Join-Path $tempRoot "freew-command-inventory.json"
$tempMarkdownPath = Join-Path $tempRoot "freew-command-inventory.md"

New-Item -ItemType Directory -Path $tempRoot | Out-Null

try {
    $definitionsProject = Convert-ToXmlAttribute (Resolve-RepoPath "freew\FreeW.Ribbon.Definitions\FreeW.Ribbon.Definitions.csproj")
    $projectPath = Join-Path $tempRoot "FreeW.CommandInventory.Generator.csproj"
    $programPath = Join-Path $tempRoot "Program.cs"

    [IO.File]::WriteAllText($projectPath, @"
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$definitionsProject" />
  </ItemGroup>
</Project>
"@)

    [IO.File]::WriteAllText($programPath, @'
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Free.Shared.Ribbon;
using FreeW.Ribbon.Definitions;

if (args.Length != 3)
{
    throw new ArgumentException("Expected repository root, JSON output path, and Markdown output path.");
}

var inventory = FreeWCommandInventory.Build(args[0]);
var options = new JsonSerializerOptions
{
    WriteIndented = true,
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
};

File.WriteAllText(args[1], JsonSerializer.Serialize(inventory, options) + Environment.NewLine, Encoding.UTF8);
File.WriteAllText(args[2], FreeWCommandInventoryMarkdown.Build(inventory), Encoding.UTF8);

internal static class FreeWCommandInventory
{
    private const string WpfProfile = "WPF";
    private const string AvaloniaProfile = "Avalonia";

    private static readonly SourceLiteralFile[] SourceFiles =
    [
        new("wpfDefinitionSource", "WPF definition source", "freew/FreeW.Ribbon.Definitions/FreeWRibbon.cs"),
        new("avaloniaDefinitionSource", "Avalonia definition source", "freew/FreeW.Ribbon.Definitions/FreeWAvaloniaRibbonDefinition.cs"),
        new("wpfRegistrySource", "WPF registry source", "freew/FreeW.App.Host/Ribbon/FreeWRibbonCommands.cs"),
        new("avaloniaRegistrySource", "Avalonia registry source", "freew/FreeW.App.Avalonia/Ribbon/FreeWAvaloniaRibbonCommands.cs"),
    ];

    private static readonly ClassificationRule[] GapClassificationRules =
    [
        new("shared-profile", "Command is present in both compiled FreeW ribbon profiles."),
        new("profile-shape-only", "One-sided row is generated by menu, dropdown, combo, gallery, or palette shape rather than a missing direct behavior."),
        new("command-id-alias", "Equivalent or near-equivalent command is exposed by the other profile under a different generated command id."),
        new("platform-only", "Command belongs to a host, shell, or desktop-only surface and should not be counted as cross-platform behavior debt."),
        new("deferred", "Command belongs to a known richer Word slice that is intentionally not part of the current Avalonia profile surface."),
        new("actionable-gap", "Shared Word behavior appears in one compiled profile only and needs product follow-up."),
    ];

    private static readonly Dictionary<string, CommandBehaviorEvidence> BehaviorEvidenceCatalog = new(StringComparer.Ordinal)
    {
        ["freew.delete-comment"] = ReviewCommentEvidence(
            "Deletes the comment thread at the caret, clears anchor/reference runs, and keeps the operation undoable in both shells.",
            "ThreadedCommentCommandTests.DeleteCommentAtCaret_RemovesThreadRangeAndReference",
            "DocumentViewReviewTests.DeleteCommentAtCaret_removes_the_comment"),
        ["freew.previous-comment"] = ReviewCommentEvidence(
            "Moves to the previous comment thread in document order, including wraparound behavior in both shells.",
            "ThreadedCommentCommandTests.CommentNavigation_WrapsAndNoOpsWithoutComments",
            "DocumentViewCommentTests.NextPreviousComment_moves_caret_in_document_order_and_wraps"),
        ["freew.next-comment"] = ReviewCommentEvidence(
            "Moves to the next comment thread in document order, including wraparound and table-cell comment anchors in both shells.",
            "ThreadedCommentCommandTests.CommentNavigation_MovesBetweenThreadsInDocumentOrder",
            "DocumentViewCommentTests.NextPreviousComment_moves_caret_in_document_order_and_wraps"),
        ["freew.resolve-comment"] = ReviewCommentEvidence(
            "Toggles the resolved state for the comment thread at the caret through WPF editor behavior and Avalonia registry execution.",
            "ThreadedCommentCommandTests.ToggleResolveCommentAtCaret_TogglesResolved",
            "DocumentViewReviewTests.ResolveComment_registry_command_toggles_the_comment_at_the_caret"),
        ["freew.chart-toggle-legend"] = ChartCommandEvidence(
            "Toggles the selected chart legend through the WPF and Avalonia ribbon command registries, clears layout overrides where applicable, and keeps the change undoable.",
            "FreeWRibbonParityTests.ChartDesign_ToggleLegendRibbonCommandMutatesSelectedChartAndUndoRestoresIt",
            "ChartSmartArtContextualTabTests.ToggleChartLegend_command_clears_layout_override_and_reverts_on_undo"),
    };

    public static InventoryDocument Build(string repoRoot)
    {
        var wpf = Collect(FreeWRibbon.Build(FreeWRibbonCapabilities.Wpf), WpfProfile);
        var avalonia = Collect(FreeWRibbon.Build(FreeWRibbonCapabilities.Avalonia), AvaloniaProfile);
        var commandIds = wpf.Keys.Concat(avalonia.Keys)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();
        var sourceTexts = SourceFiles.ToDictionary(
            file => file.Id,
            file => ReadRepositoryFile(repoRoot, file.RelativePath),
            StringComparer.Ordinal);

        var commands = commandIds.Select(commandId =>
        {
            wpf.TryGetValue(commandId, out var wpfLocations);
            avalonia.TryGetValue(commandId, out var avaloniaLocations);
            var wpfPresent = wpfLocations is { Count: > 0 };
            var avaloniaPresent = avaloniaLocations is { Count: > 0 };
            var sourceLiteralEvidence = new SourceLiteralEvidence(
                WpfDefinitionSource: ContainsCommandLiteral(sourceTexts["wpfDefinitionSource"], commandId),
                AvaloniaDefinitionSource: ContainsCommandLiteral(sourceTexts["avaloniaDefinitionSource"], commandId),
                WpfRegistrySource: ContainsCommandLiteral(sourceTexts["wpfRegistrySource"], commandId),
                AvaloniaRegistrySource: ContainsCommandLiteral(sourceTexts["avaloniaRegistrySource"], commandId));
            var profileClassification = ClassifyProfile(wpfPresent, avaloniaPresent);
            var gapClassification = ClassifyGap(
                commandId,
                wpfPresent,
                avaloniaPresent,
                wpfLocations ?? Array.Empty<CommandLocation>(),
                avaloniaLocations ?? Array.Empty<CommandLocation>(),
                commandIds);
            return new CommandEntry(
                CommandId: commandId,
                Label: (wpfLocations ?? avaloniaLocations ?? throw new InvalidOperationException()).First().Label,
                WpfPresent: wpfPresent,
                AvaloniaPresent: avaloniaPresent,
                ProfileSurface: Surface(wpfPresent, avaloniaPresent),
                MissingProfile: MissingProfile(wpfPresent, avaloniaPresent),
                Classification: profileClassification.Name,
                GapClassification: gapClassification.Name,
                GapClassificationRule: gapClassification.Rule,
                Notes: gapClassification.Notes,
                WpfLocations: wpfLocations ?? Array.Empty<CommandLocation>(),
                AvaloniaLocations: avaloniaLocations ?? Array.Empty<CommandLocation>(),
                SourceLiteralEvidence: sourceLiteralEvidence,
                BehaviorEvidence: BehaviorEvidenceCatalog.GetValueOrDefault(commandId));
        }).ToArray();

        return new InventoryDocument(
            Schema: "freew.command-inventory.v4",
            SchemaVersion: 4,
            GeneratedBy: "tools/Generate-FreeWCommandInventory.ps1",
            TopologySource: "freew/FreeW.Ribbon.Definitions FreeWRibbon.Build(FreeWRibbonCapabilities.Wpf/Avalonia)",
            SourceLiteralEvidenceNote: "Source literal evidence records exact command-id text in source files only; it is not behavior proof and never creates inventory rows.",
            BehaviorEvidenceNote: "Behavior evidence links a bounded command row to focused WPF and Avalonia tests; it strengthens parity confidence but does not create inventory rows or change gap classification.",
            ClassificationNote: "Gap classifications are generated from explicit rule order: shared-profile, profile-shape-only, command-id-alias, platform-only, deferred, then actionable-gap.",
            ClassificationRules: GapClassificationRules,
            SourceLiteralFiles: SourceFiles.Select(file => new SourceLiteralFileEntry(file.Id, file.Label, file.RelativePath)).ToArray(),
            Summary: new InventorySummary(
                TotalCommands: commands.Length,
                Both: commands.Count(command => command.ProfileSurface == "both"),
                WpfOnly: commands.Count(command => command.ProfileSurface == "wpf-only"),
                AvaloniaOnly: commands.Count(command => command.ProfileSurface == "avalonia-only"),
                MissingWpf: commands.Count(command => command.MissingProfile == WpfProfile),
                MissingAvalonia: commands.Count(command => command.MissingProfile == AvaloniaProfile),
                ActionableMissingWpf: commands.Count(command => command.MissingProfile == WpfProfile && command.GapClassification == "actionable-gap"),
                ActionableMissingAvalonia: commands.Count(command => command.MissingProfile == AvaloniaProfile && command.GapClassification == "actionable-gap"),
                SharedProfile: commands.Count(command => command.GapClassification == "shared-profile"),
                ProfileShapeOnly: commands.Count(command => command.GapClassification == "profile-shape-only"),
                CommandIdAliases: commands.Count(command => command.GapClassification == "command-id-alias"),
                PlatformOnly: commands.Count(command => command.GapClassification == "platform-only"),
                Deferred: commands.Count(command => command.GapClassification == "deferred"),
                ActionableGaps: commands.Count(command => command.GapClassification == "actionable-gap"),
                BehaviorEvidenceRows: commands.Count(command => command.BehaviorEvidence is not null)),
            Commands: commands);
    }

    private static CommandBehaviorEvidence ReviewCommentEvidence(
        string summary,
        string wpfTest,
        string avaloniaTest) =>
        new(
            EvidenceId: "freew.review-comments.shared-behavior",
            Slice: "Review comments",
            Summary: summary,
            WpfEvidence: new BehaviorEvidenceLink(
                Path: "freew/FreeW.App.Host.Tests/ThreadedCommentCommandTests.cs",
                Test: wpfTest),
            AvaloniaEvidence: new BehaviorEvidenceLink(
                Path: avaloniaTest.StartsWith("DocumentViewCommentTests.", StringComparison.Ordinal)
                    ? "freew/FreeW.App.Avalonia.Tests/DocumentViewCommentTests.cs"
                    : "freew/FreeW.App.Avalonia.Tests/DocumentViewReviewTests.cs",
                Test: avaloniaTest));

    private static CommandBehaviorEvidence ChartCommandEvidence(
        string summary,
        string wpfTest,
        string avaloniaTest) =>
        new(
            EvidenceId: "freew.chart.shared-behavior",
            Slice: "Chart command behavior",
            Summary: summary,
            WpfEvidence: new BehaviorEvidenceLink(
                Path: "freew/FreeW.App.Host.Tests/FreeWRibbonParityTests.cs",
                Test: wpfTest),
            AvaloniaEvidence: new BehaviorEvidenceLink(
                Path: "freew/FreeW.App.Avalonia.Tests/ChartSmartArtContextualTabTests.cs",
                Test: avaloniaTest));

    private static IReadOnlyDictionary<string, IReadOnlyList<CommandLocation>> Collect(RibbonDefinition definition, string profile)
    {
        var locations = new Dictionary<string, List<CommandLocation>>(StringComparer.Ordinal);
        foreach (var tab in definition.Tabs)
        {
            foreach (var group in tab.Groups)
            {
                foreach (var control in group.Controls)
                    AddControl(locations, tab, group, control, profile);
            }
        }

        return locations.ToDictionary(
            pair => pair.Key,
            pair => (IReadOnlyList<CommandLocation>)pair.Value
                .OrderBy(location => location.TabId, StringComparer.Ordinal)
                .ThenBy(location => location.GroupId, StringComparer.Ordinal)
                .ThenBy(location => location.Label, StringComparer.Ordinal)
                .ThenBy(location => location.ControlType, StringComparer.Ordinal)
                .ThenBy(location => location.Layout, StringComparer.Ordinal)
                .ToArray(),
            StringComparer.Ordinal);
    }

    private static void AddControl(
        Dictionary<string, List<CommandLocation>> locations,
        RibbonTab tab,
        RibbonGroup group,
        RibbonControl control,
        string profile)
    {
        if (!string.IsNullOrEmpty(control.CommandId.Value))
        {
            AddLocation(locations, control.CommandId.Value, new CommandLocation(
                Profile: profile,
                TabId: tab.Id,
                Tab: tab.Header,
                GroupId: group.Id,
                Group: group.Header,
                Label: control.Label,
                ControlType: control.GetType().Name,
                Layout: control.PreferredLayout.ToString()));
        }

        foreach (var menuLocation in MenuLocations(control, tab, group, profile))
            AddLocation(locations, menuLocation.CommandId, menuLocation.Location);
    }

    private static IEnumerable<(string CommandId, CommandLocation Location)> MenuLocations(
        RibbonControl control,
        RibbonTab tab,
        RibbonGroup group,
        string profile)
    {
        var menu = control switch
        {
            RibbonSplitButton splitButton => splitButton.Menu,
            RibbonDropdown dropdown => dropdown.Menu,
            _ => null,
        };

        if (menu is null)
            yield break;

        foreach (var item in MenuItems(menu.Items))
        {
            if (item.CommandId is null)
                continue;

            yield return (item.CommandId.Value.Value, new CommandLocation(
                Profile: profile,
                TabId: tab.Id,
                Tab: tab.Header,
                GroupId: group.Id,
                Group: group.Header,
                Label: item.Header,
                ControlType: "RibbonMenuItem",
                Layout: "Menu"));
        }
    }

    private static IEnumerable<RibbonMenuItem> MenuItems(IEnumerable<RibbonMenuItem> items)
    {
        foreach (var item in items)
        {
            yield return item;
            foreach (var child in MenuItems(item.Children))
                yield return child;
        }
    }

    private static void AddLocation(
        Dictionary<string, List<CommandLocation>> locations,
        string commandId,
        CommandLocation location)
    {
        if (!locations.TryGetValue(commandId, out var existing))
        {
            existing = [];
            locations.Add(commandId, existing);
        }

        existing.Add(location);
    }

    private static Classification ClassifyProfile(bool wpfPresent, bool avaloniaPresent) =>
        (wpfPresent, avaloniaPresent) switch
        {
            (true, true) => new Classification("shared-profile", "Command is present in both compiled FreeW ribbon profiles."),
            (true, false) => new Classification("wpf-profile-only", "Command is present only in the compiled WPF FreeW ribbon profile."),
            (false, true) => new Classification("avalonia-profile-only", "Command is present only in the compiled Avalonia FreeW ribbon profile."),
            _ => throw new InvalidOperationException("Command row has no compiled profile location."),
        };

    private static GapClassification ClassifyGap(
        string commandId,
        bool wpfPresent,
        bool avaloniaPresent,
        IReadOnlyList<CommandLocation> wpfLocations,
        IReadOnlyList<CommandLocation> avaloniaLocations,
        IReadOnlyCollection<string> allCommandIds)
    {
        if (wpfPresent && avaloniaPresent)
            return new GapClassification("shared-profile", "shared-profile", "Command is present in both compiled FreeW ribbon profiles.");

        var locations = wpfPresent ? wpfLocations : avaloniaLocations;

        if (IsProfileShapeOnly(commandId, locations))
            return new GapClassification("profile-shape-only", "profile-shape-only", "Row is generated by a menu, dropdown, combo, gallery, or palette shape and is not direct missing behavior.");

        if (IsCommandIdAlias(commandId, allCommandIds))
            return new GapClassification("command-id-alias", "command-id-alias", "Other profile exposes the same or closest command intent under a different generated command id.");

        if (IsPlatformOnly(commandId, locations))
            return new GapClassification("platform-only", "platform-only", "Host, shell, or desktop-only command; track separately from shared Word behavior gaps.");

        if (IsDeferred(commandId, locations))
            return new GapClassification("deferred", "deferred", "Known richer Word slice that is intentionally outside the current generated Avalonia profile surface.");

        return new GapClassification("actionable-gap", "actionable-gap", "Shared Word command is present in only one compiled profile and needs follow-up.");
    }

    private static bool IsProfileShapeOnly(string commandId, IReadOnlyList<CommandLocation> locations) =>
        locations.Any(location => location.ControlType is "RibbonMenuItem" or "RibbonComboBox" or "RibbonDropdown" or "RibbonGallery") ||
        locations.Any(location => location.GroupId is
            "chart-colors" or
            "chart-quick-layout" or
            "chart-style" or
            "chart-styles" or
            "document-formatting" or
            "draw-borders" or
            "hf-position" or
            "picture-adjust" or
            "picture-size" or
            "picture-styles" or
            "smartart-colors" or
            "smartart-create-graphic" or
            "smartart-edit" or
            "smartart-layouts" or
            "smartart-styles" or
            "symbols" or
            "table-style") ||
        commandId.StartsWith("freew.chart-color-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.chart-colors-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.chart-quick-layout-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.chart-style-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.cover-page.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.cover-page-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.equation.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.font-color.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.page-color.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.para-spacing.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.quick-parts.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.shape-change-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.shape-effect-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.shape-fill-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.shape-outline-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.smartart-colors-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.smartart-layout-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.symbol.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.table-", StringComparison.Ordinal) && commandId.Contains("x", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.table-borders.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.theme.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.theme-colors.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.theme-fonts.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.watermark.", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.wordart-style-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.wordart-warp-", StringComparison.Ordinal);

    private static bool IsCommandIdAlias(string commandId, IReadOnlyCollection<string> allCommandIds) =>
        AliasPairs.Any(pair =>
            (string.Equals(pair.Left, commandId, StringComparison.Ordinal) && allCommandIds.Contains(pair.Right)) ||
            (string.Equals(pair.Right, commandId, StringComparison.Ordinal) && allCommandIds.Contains(pair.Left)));

    private static bool IsPlatformOnly(string commandId, IReadOnlyList<CommandLocation> locations) =>
        locations.Any(location => location.TabId == "file") ||
        locations.Any(location => location.TabId == "help") ||
        locations.Any(location => location.TabId == "view" && location.GroupId == "window" && commandId is not "freew.new-window" and not "freew.split");

    private static bool IsDeferred(string commandId, IReadOnlyList<CommandLocation> locations) =>
        locations.Any(location => location.TabId is
            "developer" or
            "header-footer-design" or
            "picture-format" or
            "drawing-format" or
            "chart-design" or
            "chart-format" or
            "smartart-design") ||
        commandId.StartsWith("freew.cc-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.hf-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.image-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.smartart-", StringComparison.Ordinal) ||
        commandId.StartsWith("freew.wordart-", StringComparison.Ordinal);

    private static readonly (string Left, string Right)[] AliasPairs =
    [
        ("freew.bookmark", "freew.insert-bookmark"),
        ("freew.caption", "freew.insert-caption"),
        ("freew.citation", "freew.insert-citation"),
        ("freew.cell-borders", "freew.table-borders"),
        ("freew.cell-shading", "freew.table-shading"),
        ("freew.find", "freew.find-replace-dialog"),
        ("freew.formatting-marks", "freew.show-hide-para"),
        ("freew.hyperlink", "freew.insert-hyperlink"),
        ("freew.merge-cells", "freew.table-merge-cells"),
        ("freew.page-border", "freew.page-borders"),
        ("freew.shape-textbox", "freew.text-box"),
        ("freew.shapes", "freew.shape"),
        ("freew.split", "freew.split-window"),
        ("freew.split-cell", "freew.table-split-cell"),
        ("freew.table", "freew.insert-table"),
        ("freew.table-insert-col", "freew.table-insert-col-right"),
        ("freew.table-insert-row", "freew.table-insert-below"),
        ("freew.zoom-in", "freew.zoom-dialog"),
        ("freew.zoom-out", "freew.zoom-dialog"),
    ];

    private static string Surface(bool wpfPresent, bool avaloniaPresent) =>
        wpfPresent && avaloniaPresent
            ? "both"
            : wpfPresent
                ? "wpf-only"
                : "avalonia-only";

    private static string MissingProfile(bool wpfPresent, bool avaloniaPresent) =>
        wpfPresent && avaloniaPresent
            ? "none"
            : wpfPresent
                ? AvaloniaProfile
                : WpfProfile;

    private static string ReadRepositoryFile(string repoRoot, string relativePath)
    {
        var path = Path.Combine(new[] { repoRoot }.Concat(relativePath.Split('/')).ToArray());
        return File.Exists(path)
            ? File.ReadAllText(path)
            : "";
    }

    private static bool ContainsCommandLiteral(string source, string commandId) =>
        Regex.IsMatch(
            source,
            $@"(?<![A-Za-z0-9_.-]){Regex.Escape(commandId)}(?![A-Za-z0-9_.-])",
            RegexOptions.CultureInvariant);
}

internal static class FreeWCommandInventoryMarkdown
{
    public static string Build(InventoryDocument inventory)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# FreeW WPF/Avalonia Command Inventory");
        builder.AppendLine();
        builder.AppendLine("Generated by `tools/Generate-FreeWCommandInventory.ps1` from compiled `FreeW.Ribbon.Definitions` profiles. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("Rows are created only from `FreeWRibbon.Build(FreeWRibbonCapabilities.Wpf)` and `FreeWRibbon.Build(FreeWRibbonCapabilities.Avalonia)`, including menu children. Source literal evidence columns show exact command-id text in source files only; they are not behavior proof and never create rows. Behavior evidence links a bounded command row to focused WPF and Avalonia tests; it strengthens parity confidence but does not create rows or change gap classification.");
        builder.AppendLine();
        builder.AppendLine(inventory.ClassificationNote);
        builder.AppendLine();
        builder.AppendLine("## Summary");
        builder.AppendLine();
        builder.AppendLine("| Total | Both profiles | WPF profile only | Avalonia profile only | Missing WPF profile | Missing Avalonia profile | Actionable missing WPF | Actionable missing Avalonia |");
        builder.AppendLine("|---:|---:|---:|---:|---:|---:|---:|---:|");
        builder.AppendLine($"| {inventory.Summary.TotalCommands} | {inventory.Summary.Both} | {inventory.Summary.WpfOnly} | {inventory.Summary.AvaloniaOnly} | {inventory.Summary.MissingWpf} | {inventory.Summary.MissingAvalonia} | {inventory.Summary.ActionableMissingWpf} | {inventory.Summary.ActionableMissingAvalonia} |");
        builder.AppendLine();
        builder.AppendLine("## Classification Counts");
        builder.AppendLine();
        builder.AppendLine("| Shared profile | Profile-shape only | Command-id aliases | Platform-only | Deferred | Actionable gaps | Behavior evidence rows |");
        builder.AppendLine("|---:|---:|---:|---:|---:|---:|---:|");
        builder.AppendLine($"| {inventory.Summary.SharedProfile} | {inventory.Summary.ProfileShapeOnly} | {inventory.Summary.CommandIdAliases} | {inventory.Summary.PlatformOnly} | {inventory.Summary.Deferred} | {inventory.Summary.ActionableGaps} | {inventory.Summary.BehaviorEvidenceRows} |");
        builder.AppendLine();
        builder.AppendLine("## Classification Rules");
        builder.AppendLine();
        builder.AppendLine("| Classification | Rule |");
        builder.AppendLine("|---|---|");
        foreach (var rule in inventory.ClassificationRules)
            builder.AppendLine($"| {Escape(rule.Name)} | {Escape(rule.Description)} |");
        builder.AppendLine();
        builder.AppendLine("## Matrix");
        builder.AppendLine();
        builder.AppendLine("| Command ID | Label | WPF profile | Avalonia profile | Missing profile | Profile classification | Gap classification | Rule | WPF locations | Avalonia locations | Source literal evidence | Behavior evidence | Notes |");
        builder.AppendLine("|---|---|---:|---:|---|---|---|---|---|---|---|---|---|");

        foreach (var command in inventory.Commands)
        {
            builder.AppendLine(
                $"| `{Escape(command.CommandId)}` | {Escape(command.Label)} | {YesNo(command.WpfPresent)} | {YesNo(command.AvaloniaPresent)} | {Escape(command.MissingProfile)} | {Escape(command.Classification)} | {Escape(command.GapClassification)} | {Escape(command.GapClassificationRule)} | {Escape(Locations(command.WpfLocations))} | {Escape(Locations(command.AvaloniaLocations))} | {Escape(SourceEvidence(command.SourceLiteralEvidence))} | {Escape(BehaviorEvidence(command.BehaviorEvidence))} | {Escape(command.Notes)} |");
        }

        return builder.ToString();
    }

    private static string Locations(IReadOnlyList<CommandLocation> locations) =>
        locations.Count == 0
            ? "-"
            : string.Join("<br>", locations.Select(location => $"{location.TabId}/{location.GroupId} ({location.ControlType}; {location.Layout})"));

    private static string SourceEvidence(SourceLiteralEvidence evidence)
    {
        var hits = new List<string>();
        if (evidence.WpfDefinitionSource)
            hits.Add("WPF definition source");
        if (evidence.AvaloniaDefinitionSource)
            hits.Add("Avalonia definition source");
        if (evidence.WpfRegistrySource)
            hits.Add("WPF registry source");
        if (evidence.AvaloniaRegistrySource)
            hits.Add("Avalonia registry source");

        return hits.Count == 0 ? "-" : string.Join("<br>", hits);
    }

    private static string BehaviorEvidence(CommandBehaviorEvidence? evidence) =>
        evidence is null
            ? "-"
            : $"{evidence.Slice}: {evidence.WpfEvidence.Test}<br>{evidence.AvaloniaEvidence.Test}";

    private static string YesNo(bool value) => value ? "Yes" : "No";

    private static string Escape(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", "", StringComparison.Ordinal)
            .Replace("\n", "<br>", StringComparison.Ordinal);
}

internal sealed record InventoryDocument(
    string Schema,
    int SchemaVersion,
    string GeneratedBy,
    string TopologySource,
    string SourceLiteralEvidenceNote,
    string BehaviorEvidenceNote,
    string ClassificationNote,
    IReadOnlyList<ClassificationRule> ClassificationRules,
    IReadOnlyList<SourceLiteralFileEntry> SourceLiteralFiles,
    InventorySummary Summary,
    IReadOnlyList<CommandEntry> Commands);

internal sealed record SourceLiteralFileEntry(
    string Id,
    string Label,
    string Path);

internal sealed record InventorySummary(
    int TotalCommands,
    int Both,
    int WpfOnly,
    int AvaloniaOnly,
    int MissingWpf,
    int MissingAvalonia,
    int ActionableMissingWpf,
    int ActionableMissingAvalonia,
    int SharedProfile,
    int ProfileShapeOnly,
    int CommandIdAliases,
    int PlatformOnly,
    int Deferred,
    int ActionableGaps,
    int BehaviorEvidenceRows);

internal sealed record CommandEntry(
    string CommandId,
    string Label,
    bool WpfPresent,
    bool AvaloniaPresent,
    string ProfileSurface,
    string MissingProfile,
    string Classification,
    string GapClassification,
    string GapClassificationRule,
    string Notes,
    IReadOnlyList<CommandLocation> WpfLocations,
    IReadOnlyList<CommandLocation> AvaloniaLocations,
    SourceLiteralEvidence SourceLiteralEvidence,
    CommandBehaviorEvidence? BehaviorEvidence);

internal sealed record CommandLocation(
    string Profile,
    string TabId,
    string Tab,
    string GroupId,
    string Group,
    string Label,
    string ControlType,
    string Layout);

internal sealed record SourceLiteralEvidence(
    bool WpfDefinitionSource,
    bool AvaloniaDefinitionSource,
    bool WpfRegistrySource,
    bool AvaloniaRegistrySource);

internal sealed record CommandBehaviorEvidence(
    string EvidenceId,
    string Slice,
    string Summary,
    BehaviorEvidenceLink WpfEvidence,
    BehaviorEvidenceLink AvaloniaEvidence);

internal sealed record BehaviorEvidenceLink(
    string Path,
    string Test);

internal sealed record Classification(string Name, string Notes);

internal sealed record GapClassification(string Name, string Rule, string Notes);

internal sealed record ClassificationRule(string Name, string Description);

internal sealed record SourceLiteralFile(string Id, string Label, string RelativePath);
'@)

    & dotnet run --project $projectPath --configuration Release -- $repoRoot $tempJsonPath $tempMarkdownPath
    if ($LASTEXITCODE -ne 0) {
        throw "FreeW command inventory generator failed."
    }

    if ($Check) {
        Test-FileContentMatches -ExpectedPath $tempJsonPath -ActualPath $resolvedJsonPath -Label $JsonPath
        Test-FileContentMatches -ExpectedPath $tempMarkdownPath -ActualPath $resolvedMarkdownPath -Label $MarkdownPath
        Write-Host "FreeW command inventory docs are up to date."
        return
    }

    $jsonDirectory = Split-Path -Parent $resolvedJsonPath
    $markdownDirectory = Split-Path -Parent $resolvedMarkdownPath
    New-Item -ItemType Directory -Path $jsonDirectory -Force | Out-Null
    New-Item -ItemType Directory -Path $markdownDirectory -Force | Out-Null
    Copy-Item -LiteralPath $tempJsonPath -Destination $resolvedJsonPath -Force
    Copy-Item -LiteralPath $tempMarkdownPath -Destination $resolvedMarkdownPath -Force
    Write-Host "Wrote $JsonPath and $MarkdownPath."
}
finally {
    if (Test-Path -LiteralPath $tempRoot) {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force
    }
}
