using System.Text;
using Free.Shared.Ribbon;
using Free.ToolsShared;
using FreeP.App.Compositor;
using FreeP.Core.Model;
using FreeP.Ribbon.Definitions;

return GeneratedEvidenceToolRunner.Run(
    args,
    new GeneratedEvidenceToolSpec(
        "FreeP.slnx",
        Path.Combine("docs", "parity", "freep-keyboard-context-parity-20260720.md"),
        BuildReport));

static string BuildReport()
{
    var presentation = Presentation.CreateEmpty();
    presentation.Slides.Add(new Slide { Title = "Second" });
    var section = new PresentationSection { Name = "Section 1" };
    section.SlideIds.Add(presentation.Slides[0].Id);
    presentation.Sections.Add(section);

    var slideMenu = FreePContextMenuCatalog.BuildSlideMenu(
        presentation.Slides,
        presentation.Sections,
        slideIndex: 0);
    var sectionMenu = FreePContextMenuCatalog.BuildSectionHeaderMenu(
        presentation.Sections,
        sectionIndex: 0,
        slideIndex: 0);
    var menuRows = new[] { slideMenu, sectionMenu }
        .SelectMany(entries => entries)
        .ToArray();
    var wpfKeyTips = CountKeyTips(FreePRibbon.Build(FreePRibbonCapabilities.Wpf));
    var avaloniaKeyTips = CountKeyTips(FreePRibbon.Build(FreePRibbonCapabilities.Avalonia));

    var builder = new StringBuilder();
    builder.AppendLine("# FreeP Keyboard and Context Parity Evidence");
    builder.AppendLine();
    builder.AppendLine("> Generated by `tools/FreeP.KeyboardContextEvidence` from `FreePKeyboardShortcutCatalog`, `FreePContextMenuCatalog`, and `FreePRibbon`. Do not edit by hand.");
    builder.AppendLine();
    builder.AppendLine("## Coverage");
    builder.AppendLine();
    builder.AppendLine($"- Shortcut gestures: {FreePKeyboardShortcutCatalog.All.Count}");
    builder.AppendLine($"- Semantic shortcut commands: {FreePKeyboardShortcutCatalog.All.Select(item => item.Command).Distinct().Count()}");
    builder.AppendLine("- Context-menu surfaces: 2");
    builder.AppendLine($"- Context-menu command rows: {menuRows.Count(item => item.Kind == FreePContextMenuEntryKind.Command)}");
    builder.AppendLine($"- Context-menu separators: {menuRows.Count(item => item.Kind == FreePContextMenuEntryKind.Separator)}");
    builder.AppendLine("- Keyboard context invocation routes: Apps, Shift+F10");
    builder.AppendLine("- Keyboard dismiss route: Escape");
    builder.AppendLine();
    builder.AppendLine("## Shortcuts");
    builder.AppendLine();
    builder.AppendLine("| Gesture | Semantic command |");
    builder.AppendLine("| --- | --- |");
    foreach (var shortcut in FreePKeyboardShortcutCatalog.All)
        builder.AppendLine($"| {FormatGesture(shortcut)} | {shortcut.Command} |");

    AppendMenu(builder, "Slide", slideMenu);
    AppendMenu(builder, "Section header", sectionMenu);

    builder.AppendLine("## KeyTips");
    builder.AppendLine();
    builder.AppendLine("| Profile | Tabs | Groups | Actionable controls | Nested menu commands | Total keyed entries |");
    builder.AppendLine("| --- | ---: | ---: | ---: | ---: | ---: |");
    AppendKeyTipRow(builder, "WPF", wpfKeyTips);
    AppendKeyTipRow(builder, "Avalonia", avaloniaKeyTips);
    builder.AppendLine();
    builder.AppendLine("All counted entries have non-empty KeyTips and every tab, group, control, and nested-menu scope is collision-free. Shared command KeyTips match between profiles except the declared `freep.new-slide` profile override.");
    builder.AppendLine();
    builder.AppendLine("## Authoritative Tests");
    builder.AppendLine();
    builder.AppendLine("- `FreePShellInteractionCatalogTests`: catalog completeness, dispatch, exact menu order/state, Apps/Shift+F10/Escape semantics.");
    builder.AppendLine("- `FreePKeyTipInventoryTests`: both complete ribbon profiles and scoped KeyTip uniqueness.");
    builder.AppendLine("- WPF and Avalonia `KeyboardContextParityTests`: installed host routes, real command effects, concrete menu state/effects, and Avalonia Alt/invocation/Escape lifecycle.");
    builder.AppendLine();
    builder.AppendLine("## External-only Gaps");
    builder.AppendLine();
    builder.AppendLine("- Foreground OS proof of the physical Apps key, native WPF menu focus behavior, Alt badge painting, and platform clipboard/dialog integration remains outside headless and in-process test automation.");
    builder.AppendLine("- There are no known in-process semantic shortcut or context-menu parity gaps.");
    return builder.ToString();
}

static void AppendMenu(
    StringBuilder builder,
    string surface,
    IReadOnlyList<FreePContextMenuEntryPlan> entries)
{
    builder.AppendLine();
    builder.AppendLine($"## {surface} Context Menu");
    builder.AppendLine();
    builder.AppendLine("| Position | Kind | Command | Label | Enabled | Checkable | Checked |");
    builder.AppendLine("| ---: | --- | --- | --- | --- | --- | --- |");
    for (var index = 0; index < entries.Count; index++)
    {
        var entry = entries[index];
        builder.AppendLine(
            $"| {index + 1} | {entry.Kind} | {entry.Command?.ToString() ?? "-"} | {EscapeCell(entry.Text)} | {entry.IsEnabled} | {entry.IsCheckable} | {entry.IsChecked} |");
    }
}

static string FormatGesture(FreePKeyboardShortcut shortcut)
{
    var parts = new List<string>();
    if (shortcut.Modifiers.HasFlag(FreePKeyboardModifiers.Control))
        parts.Add("Ctrl");
    if (shortcut.Modifiers.HasFlag(FreePKeyboardModifiers.Shift))
        parts.Add("Shift");
    if (shortcut.Modifiers.HasFlag(FreePKeyboardModifiers.Alt))
        parts.Add("Alt");
    parts.Add(shortcut.Key.ToString());
    return string.Join('+', parts);
}

static string EscapeCell(string value) =>
    string.IsNullOrEmpty(value) ? "-" : value.Replace("|", "\\|", StringComparison.Ordinal);

static KeyTipInventory CountKeyTips(RibbonDefinition definition)
{
    var tabs = definition.Tabs.Count;
    var groups = definition.Tabs.Sum(tab => tab.Groups.Count);
    var controls = definition.Tabs
        .SelectMany(tab => tab.Groups)
        .SelectMany(group => group.Controls)
        .Count(control => control is not RibbonSeparator and not RibbonComboBox);
    var menuCommands = definition.Tabs
        .SelectMany(tab => tab.Groups)
        .SelectMany(group => group.Controls)
        .Sum(CountMenuCommands);
    return new KeyTipInventory(tabs, groups, controls, menuCommands);
}

static int CountMenuCommands(RibbonControl control)
{
    var menu = control switch
    {
        RibbonSplitButton split => split.Menu,
        RibbonDropdown dropdown => dropdown.Menu,
        _ => null,
    };
    return menu is null ? 0 : CountMenuItems(menu.Items);
}

static int CountMenuItems(IEnumerable<RibbonMenuItem> items) =>
    items.Sum(item => (item.CommandId is null ? 0 : 1) + CountMenuItems(item.Children));

static void AppendKeyTipRow(StringBuilder builder, string profile, KeyTipInventory inventory) =>
    builder.AppendLine(
        $"| {profile} | {inventory.Tabs} | {inventory.Groups} | {inventory.Controls} | {inventory.MenuCommands} | {inventory.Total} |");

internal readonly record struct KeyTipInventory(
    int Tabs,
    int Groups,
    int Controls,
    int MenuCommands)
{
    public int Total => Tabs + Groups + Controls + MenuCommands;
}
