using System.IO.Compression;
using System.Xml.Linq;
using FreeX.Core.IO;
using FreeX.Core.Model;

namespace FreeX.Core.IO.Tests;

internal static partial class XlsxCorpusFixtureFactory
{
    private static readonly HashSet<string> SupportedIds = new(StringComparer.OrdinalIgnoreCase)
    {
        "generated-grid-basic-001",
        "generated-formulas-001",
        "generated-cross-sheet-001",
        "generated-formatting-001",
        "generated-structure-001",
        "generated-validation-001",
        "generated-conditional-formatting-001",
        "generated-color-scales-001",
        "generated-data-bars-001",
        "generated-icon-sets-001",
        "generated-text-boxes-shapes-001",
        "generated-images-sparklines-001",
        "generated-comments-hyperlinks-002",
        "generated-merged-freeze-002",
        "generated-print-titles-breaks-001",
        "generated-named-ranges-formulas-002",
        "generated-validation-custom-002",
        "generated-style-only-cells-002",
        "generated-charts-combo-002",
        "generated-pivots-filters-002",
        "generated-structured-table-totals-002",
        "generated-images-sparklines-002",
        "generated-objects-001",
        "generated-charts-001",
        "generated-pivots-001",
        "generated-structured-tables-001",
        "generated-protection-page-setup-001",
        "generated-named-ranges-deep-003",
        "generated-cf-multi-rules-003",
        "generated-charts-multi-series-003",
        "generated-dv-edge-cases-003",
        "generated-merged-cells-formulas-003",
        "generated-cross-sheet-refs-advanced-003",
        "generated-array-formulas-003",
        "generated-chart-scatter-bubble-003",
        "generated-pivot-calculated-fields-003",
        "generated-table-structured-refs-003",
        "generated-formatting-advanced-003",
        "generated-sparklines-advanced-003",
        "generated-protection-advanced-003",
        "generated-cf-with-dxf-styles-003",
        "generated-formulas-cached-003",
        "generated-chart-pie-doughnut-003",
        "generated-hyperlinks-advanced-003",
        "generated-comments-advanced-003",
        "generated-table-autofilter-003",
        "generated-multiple-sheets-003",
        "generated-number-formats-003",
        "generated-validation-messages-003",
        "generated-row-column-groups-003",
        "generated-mixed-chart-types-003",
        "generated-large-named-ranges-003"
    };

    public static bool CanCreate(string id) => SupportedIds.Contains(id);

    public static bool CanCreateKnownGapPackage(string id) => id switch
    {
        "generated-threaded-comments-001" => true,
        "generated-track-changes-001" => true,
        "generated-form-controls-001" => true,
        "generated-digital-signatures-001" => true,
        "generated-custom-ribbon-ui-001" => true,
        "generated-office-addins-001" => true,
        "generated-live-web-queries-001" => true,
        "generated-sensitivity-labels-001" => true,
        "generated-smartart-diagrams-001" => true,
        "generated-printer-settings-001" => true,
        "generated-calc-chain-001" => true,
        "generated-document-properties-001" => true,
        "generated-header-footer-legacy-drawing-001" => true,
        "generated-worksheet-legacy-drawing-001" => true,
        "generated-workbook-extension-list-001" => true,
        "generated-workbook-properties-001" => true,
        "generated-workbook-calculation-001" => true,
        "generated-workbook-file-version-001" => true,
        "generated-workbook-file-recovery-001" => true,
        "generated-workbook-file-sharing-001" => true,
        "generated-workbook-protection-native-001" => true,
        "generated-workbook-smart-tags-001" => true,
        "generated-workbook-function-groups-001" => true,
        "generated-workbook-views-001" => true,
        "generated-workbook-defined-names-native-001" => true,
        "generated-workbook-theme-native-schemes-001" => true,
        "generated-stylesheet-native-metadata-001" => true,
        "generated-worksheet-ignored-errors-001" => true,
        "generated-worksheet-cell-watches-001" => true,
        "generated-worksheet-single-xml-cells-001" => true,
        "generated-worksheet-calculation-properties-001" => true,
        "generated-worksheet-sheet-views-001" => true,
        "generated-worksheet-sheet-format-001" => true,
        "generated-worksheet-page-breaks-001" => true,
        "generated-worksheet-print-options-001" => true,
        "generated-worksheet-page-setup-native-001" => true,
        "generated-worksheet-header-footer-native-001" => true,
        "generated-worksheet-dimension-native-001" => true,
        "generated-worksheet-sheet-properties-001" => true,
        "generated-worksheet-protection-native-001" => true,
        "generated-worksheet-protected-ranges-001" => true,
        "generated-worksheet-cell-structure-native-001" => true,
        "generated-worksheet-phonetic-properties-001" => true,
        "generated-worksheet-sort-state-001" => true,
        "generated-worksheet-data-consolidation-001" => true,
        "generated-worksheet-auto-filter-metadata-001" => true,
        "generated-worksheet-custom-properties-001" => true,
        "generated-worksheet-smart-tags-001" => true,
        "generated-worksheet-scenarios-001" => true,
        "generated-worksheet-custom-sheet-views-001" => true,
        "generated-worksheet-extension-list-001" => true,
        "generated-unsupported-sheet-types-001" => true,
        "generated-unsupported-chart-001" => true,
        "generated-vba-macros-001" => true,
        "generated-power-query-001" => true,
        "generated-data-model-001" => true,
        "generated-linked-data-types-001" => true,
        "generated-slicers-001" => true,
        "generated-timelines-001" => true,
        "generated-external-links-001" => true,
        "generated-embedded-objects-001" => true,
        "generated-custom-xml-001" => true,
        "generated-custom-docprops-001" => true,
        "generated-cf-retention-package-003" => true,
        "generated-chart-series-count-003" => true,
        "generated-dv-count-package-003" => true,
        "generated-table-ref-formulas-package-003" => true,
        "generated-cross-sheet-range-package-003" => true,
        "generated-named-range-count-package-003" => true,
        _ => false
    };

    public static bool CanCreateKnownGapRetentionPackage(string id) => CanCreateKnownGapPackage(id);

    public static Workbook Create(string id) => id switch
    {
        "generated-grid-basic-001" => CreateGridBasic(),
        "generated-formulas-001" => CreateFormulas(),
        "generated-cross-sheet-001" => CreateCrossSheet(),
        "generated-formatting-001" => CreateFormatting(),
        "generated-structure-001" => CreateStructure(),
        "generated-validation-001" => CreateValidation(),
        "generated-conditional-formatting-001" => CreateConditionalFormatting(),
        "generated-color-scales-001" => CreateColorScales(),
        "generated-data-bars-001" => CreateDataBars(),
        "generated-icon-sets-001" => CreateIconSets(),
        "generated-text-boxes-shapes-001" => CreateTextBoxesAndShapes(),
        "generated-images-sparklines-001" => CreateImagesAndSparklines(),
        "generated-comments-hyperlinks-002" => CreateCommentsAndHyperlinks(),
        "generated-merged-freeze-002" => CreateMergedFreeze(),
        "generated-print-titles-breaks-001" => CreatePrintTitlesAndBreaks(),
        "generated-named-ranges-formulas-002" => CreateNamedRangesAndFormulas(),
        "generated-validation-custom-002" => CreateValidationCustom(),
        "generated-style-only-cells-002" => CreateStyleOnlyCells(),
        "generated-charts-combo-002" => CreateChartsCombo(),
        "generated-pivots-filters-002" => CreatePivotsWithFilters(),
        "generated-structured-table-totals-002" => CreateStructuredTableTotals(),
        "generated-images-sparklines-002" => CreateImagesAndSparklinesVariant(),
        "generated-objects-001" => CreateObjects(),
        "generated-charts-001" => CreateCharts(),
        "generated-pivots-001" => CreatePivots(),
        "generated-structured-tables-001" => CreateStructuredTables(),
        "generated-protection-page-setup-001" => CreateProtectionAndPageSetup(),
        "generated-named-ranges-deep-003" => CreateNamedRangesDeep(),
        "generated-cf-multi-rules-003" => CreateCfMultiRules(),
        "generated-charts-multi-series-003" => CreateChartsMultiSeries(),
        "generated-dv-edge-cases-003" => CreateDvEdgeCases(),
        "generated-merged-cells-formulas-003" => CreateMergedCellsFormulas(),
        "generated-cross-sheet-refs-advanced-003" => CreateCrossSheetRefsAdvanced(),
        "generated-array-formulas-003" => CreateArrayFormulas(),
        "generated-chart-scatter-bubble-003" => CreateChartScatterBubble(),
        "generated-pivot-calculated-fields-003" => CreatePivotCalculatedFields(),
        "generated-table-structured-refs-003" => CreateTableStructuredRefs(),
        "generated-formatting-advanced-003" => CreateFormattingAdvanced(),
        "generated-sparklines-advanced-003" => CreateSparklinesAdvanced(),
        "generated-protection-advanced-003" => CreateProtectionAdvanced(),
        "generated-cf-with-dxf-styles-003" => CreateCfWithDxfStyles(),
        "generated-formulas-cached-003" => CreateFormulasCached(),
        "generated-chart-pie-doughnut-003" => CreateChartPieDoughnut(),
        "generated-hyperlinks-advanced-003" => CreateHyperlinksAdvanced(),
        "generated-comments-advanced-003" => CreateCommentsAdvanced(),
        "generated-table-autofilter-003" => CreateTableAutoFilter(),
        "generated-multiple-sheets-003" => CreateMultipleSheets(),
        "generated-number-formats-003" => CreateNumberFormats(),
        "generated-validation-messages-003" => CreateValidationMessages(),
        "generated-row-column-groups-003" => CreateRowColumnGroups(),
        "generated-mixed-chart-types-003" => CreateMixedChartTypes(),
        "generated-large-named-ranges-003" => CreateLargeNamedRanges(),
        _ => throw new ArgumentOutOfRangeException(nameof(id), id, "No generated XLSX corpus fixture exists for this id.")
    };

}
